        {
          chapter: 10,
          sloka: 15,
          devanagari: "स्वयमेवात्मनात्मानं वेत्थ त्वं पुरुषोत्तम ।\nभूतभावन भूतेश देवदेव जगत्पते ॥१५॥",
          transliteration: "svayam evātmanātmānaṁ vettha tvaṁ puruṣottama |\nbhūta-bhāvana bhūteśa deva-deva jagat-pate ||15||",
          words: [
            { word: "स्वयम्", transliteration: "svayam", meaning: "Yourself" },
            { word: "एव", transliteration: "eva", meaning: "alone" },
            { word: "आत्मना", transliteration: "ātmanā", meaning: "by Your own Self" },
            { word: "आत्मानम्", transliteration: "ātmānam", meaning: "Yourself" },
            { word: "वेत्थ", transliteration: "vettha", meaning: "You know" },
            { word: "त्वम्", transliteration: "tvam", meaning: "You" },
            { word: "पुरुषोत्तम", transliteration: "puruṣottama", meaning: "O Supreme Person" },
            { word: "भूतभावन", transliteration: "bhūta-bhāvana", meaning: "O Source of all beings" },
            { word: "भूतेश", transliteration: "bhūteśa", meaning: "O Lord of all beings" },
            { word: "देवदेव", transliteration: "deva-deva", meaning: "O God of gods" },
            { word: "जगत्पते", transliteration: "jagat-pate", meaning: "O Ruler of the world" }
          ],
          translation: "You alone know Yourself by Your own Self, O Supreme Person, O Source of beings, O Lord of beings, O God of gods, O Ruler of the world.",
          modernInterpretation: "Arjuna just dropped FIVE titles in one verse — Purushottama, Bhuta-bhavana, Bhutesha, Deva-deva, Jagat-pate. That is not a prayer, that is a LinkedIn headline on steroids. But here is the REAL insight: Arjuna is saying YOU ALONE KNOW YOURSELF. Not Google. Not your guru. Not your therapist. Not that personality quiz you took at 2 AM. The deepest knowledge of who you truly are can only come from WITHIN. Think about it — we spend our whole lives asking others to define us. 'Am I good enough? Am I smart enough? What do people think of me?' We check Instagram likes for validation, refresh LinkedIn for endorsement notifications, ask our parents if they are proud. But Arjuna understood something most of us never will: the ULTIMATE REALITY can only be known by itself. No external framework can contain the infinite. It is like trying to explain the taste of water — you can only KNOW it by being it. This is not philosophy. This is the most practical advice you will ever get: STOP OUTSOURCING YOUR SELF-KNOWLEDGE. The algorithm does not know you. Your followers do not know you. Only the consciousness reading these words knows itself."
        },
        {
          chapter: 10,
          sloka: 16,
          devanagari: "वक्तुमर्हस्यशेषेण दिव्या ह्यात्मविभूतयः ।\nयाभिर्विभूतिभिर्लोकानिमांस्त्वं व्याप्य तिष्ठसि ॥१६॥",
          transliteration: "vaktum arhasy aśeṣeṇa divyā hy ātma-vibhūtayaḥ |\nyābhir vibhūtibhir lokān imāṁs tvaṁ vyāpya tiṣṭhasi ||16||",
          words: [
            { word: "वक्तुम्", transliteration: "vaktum", meaning: "to tell" },
            { word: "अर्हसि", transliteration: "arhasi", meaning: "You are able / please" },
            { word: "अशेषेण", transliteration: "aśeṣeṇa", meaning: "in full / without remainder" },
            { word: "दिव्याः", transliteration: "divyāḥ", meaning: "divine" },
            { word: "हि", transliteration: "hi", meaning: "indeed" },
            { word: "आत्मविभूतयः", transliteration: "ātma-vibhūtayaḥ", meaning: "Your own glories" },
            { word: "याभिः", transliteration: "yābhiḥ", meaning: "by which" },
            { word: "विभूतिभिः", transliteration: "vibhūtibhiḥ", meaning: "by glories / manifestations" },
            { word: "लोकान्", transliteration: "lokān", meaning: "worlds" },
            { word: "इमान्", transliteration: "imān", meaning: "these" },
            { word: "त्वम्", transliteration: "tvam", meaning: "You" },
            { word: "व्याप्य", transliteration: "vyāpya", meaning: "pervading" },
            { word: "तिष्ठसि", transliteration: "tiṣṭhasi", meaning: "You abide / remain" }
          ],
          translation: "Please tell me in detail Your divine glories by which You pervade all these worlds and abide in them.",
          modernInterpretation: "Arjuna is basically saying: 'Krishna, give me the FULL LIST. No summary. No TL;DR. I want the unabridged version.' This is the rare human who actually WANTS the long answer. In a world of reels and shorts, Arjuna is asking for the director's cut. And notice the word VYAPYA — pervading. Not sitting on top, not ruling from outside, but SOAKING THROUGH everything like chai seeping into a biscuit. The divine is not a CEO watching from the corner office. It is the WiFi signal — invisible, everywhere, and the reason anything works at all. Arjuna wants to know: where do I LOOK for You? What should I pay attention to? This is the most important question a seeker can ask — not 'Does God exist?' but 'WHERE does God exist?' And the answer Krishna is about to give will blow every circuit in your brain. Because the answer is: EVERYWHERE. In every excellence, every peak, every moment of beauty. You have been staring at the divine your whole life and calling it 'nature' or 'luck' or 'talent.' Arjuna just asked Krishna to remove the filter."
        },
        {
          chapter: 10,
          sloka: 17,
          devanagari: "कथं विद्यामहं योगिंस्त्वां सदा परिचिन्तयन् ।\nकेषु केषु च भावेषु चिन्त्योऽसि भगवन्मया ॥१७॥",
          transliteration: "kathaṁ vidyām ahaṁ yogiṁs tvāṁ sadā paricintayan |\nkeṣu keṣu ca bhāveṣu cintyo 'si bhagavan mayā ||17||",
          words: [
            { word: "कथम्", transliteration: "katham", meaning: "how" },
            { word: "विद्याम्", transliteration: "vidyām", meaning: "shall I know" },
            { word: "अहम्", transliteration: "aham", meaning: "I" },
            { word: "योगिन्", transliteration: "yogin", meaning: "O Yogin" },
            { word: "त्वाम्", transliteration: "tvām", meaning: "You" },
            { word: "सदा", transliteration: "sadā", meaning: "always / constantly" },
            { word: "परिचिन्तयन्", transliteration: "paricintayan", meaning: "meditating upon" },
            { word: "केषु केषु", transliteration: "keṣu keṣu", meaning: "in which various" },
            { word: "भावेषु", transliteration: "bhāveṣu", meaning: "aspects / forms" },
            { word: "चिन्त्यः", transliteration: "cintyaḥ", meaning: "to be thought of" },
            { word: "असि", transliteration: "asi", meaning: "are You" },
            { word: "भगवन्", transliteration: "bhagavan", meaning: "O Lord" },
            { word: "मया", transliteration: "mayā", meaning: "by me" }
          ],
          translation: "How shall I know You, O Yogin, by constant meditation? In what various aspects are You to be thought of by me, O Lord?",
          modernInterpretation: "This is Arjuna asking for the MEDITATION CHEAT CODE. 'Bro, when I sit down to meditate, what exactly am I supposed to think about? You are everywhere — that is great in theory, but I need SPECIFICS.' Every beginner meditator relates to this. You sit down, close your eyes, and then what? Think about the universe? A candle flame? Your breathing? That embarrassing thing you said in 2014? Arjuna is asking the most PRACTICAL spiritual question: how do I actually PRACTICE seeing You everywhere? It is like downloading an app but not knowing which button does what. Krishna is about to give him the user manual. And the genius of this question is the phrase SADA PARICINTAYAN — CONSTANTLY meditating. Not just on the yoga mat. Not just at the temple. ALWAYS. While stuck in Bangalore traffic. While waiting for your Swiggy order. While pretending to listen in a Zoom meeting. Arjuna wants a framework for 24/7 awareness. He is asking Krishna to turn the entire world into a meditation hall. And that, friends, is the real meaning of yoga — not flexibility of the body, but flexibility of PERCEPTION."
        },
        {
          chapter: 10,
          sloka: 18,
          devanagari: "विस्तरेणात्मनो योगं विभूतिं च जनार्दन ।\nभूयः कथय तृप्तिर्हि शृण्वतो नास्ति मेऽमृतम् ॥१८॥",
          transliteration: "vistareṇātmano yogaṁ vibhūtiṁ ca janārdana |\nbhūyaḥ kathaya tṛptir hi śṛṇvato nāsti me 'mṛtam ||18||",
          words: [
            { word: "विस्तरेण", transliteration: "vistareṇa", meaning: "in detail" },
            { word: "आत्मनः", transliteration: "ātmanaḥ", meaning: "Your own" },
            { word: "योगम्", transliteration: "yogam", meaning: "yoga power" },
            { word: "विभूतिम्", transliteration: "vibhūtim", meaning: "glories / manifestations" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "जनार्दन", transliteration: "janārdana", meaning: "O Janardana (Krishna)" },
            { word: "भूयः", transliteration: "bhūyaḥ", meaning: "again" },
            { word: "कथय", transliteration: "kathaya", meaning: "tell / narrate" },
            { word: "तृप्तिः", transliteration: "tṛptiḥ", meaning: "satisfaction / satiation" },
            { word: "हि", transliteration: "hi", meaning: "indeed" },
            { word: "शृण्वतः", transliteration: "śṛṇvataḥ", meaning: "of hearing" },
            { word: "न अस्ति", transliteration: "na asti", meaning: "there is not" },
            { word: "मे", transliteration: "me", meaning: "my" },
            { word: "अमृतम्", transliteration: "amṛtam", meaning: "nectar" }
          ],
          translation: "Tell me again in detail, O Janardana, of Your yoga power and glories, for I am never satiated hearing Your nectar-like words.",
          modernInterpretation: "Arjuna just said the most beautiful thing a student can say to a teacher: 'I CANNOT GET ENOUGH.' NASTI ME AMRITAM — there is no satiation in your nectar. This is not polite conversation. This is ADDICTION — but the only healthy kind. Most of us are addicted to things that leave us emptier after consumption — that third reel, that extra gulab jamun, that revenge-scrolling through an ex's profile at midnight. But Arjuna has found the one thing that FILLS you more the more you consume it: genuine wisdom. Notice he says BHUYAH — again! He has already heard Krishna speak for nine chapters. Any normal person would say 'Got it, bhai, let us move on.' But real knowledge is like a Netflix series where every rewatch reveals a new layer. You think you understood it, then you grow a little, and suddenly the same words hit differently. This is why your grandmother read the Gita every single day and never got bored. It was not repetition — it was DEPTH. The text did not change. SHE changed. And each new version of her found new nectar in the same old verses. That is AMRITAM — the content that never expires, unlike your Instagram stories."
        },
        {
          chapter: 10,
          sloka: 19,
          devanagari: "श्रीभगवानुवाच ।\nहन्त ते कथयिष्यामि दिव्या ह्यात्मविभूतयः ।\nप्राधान्यतः कुरुश्रेष्ठ नास्त्यन्तो विस्तरस्य मे ॥१९॥",
          transliteration: "śrī-bhagavān uvāca |\nhanta te kathayiṣyāmi divyā hy ātma-vibhūtayaḥ |\nprādhānyataḥ kuru-śreṣṭha nāsty anto vistarasya me ||19||",
          words: [
            { word: "श्रीभगवान्", transliteration: "śrī-bhagavān", meaning: "the Supreme Lord" },
            { word: "उवाच", transliteration: "uvāca", meaning: "said" },
            { word: "हन्त", transliteration: "hanta", meaning: "very well / yes" },
            { word: "ते", transliteration: "te", meaning: "to you" },
            { word: "कथयिष्यामि", transliteration: "kathayiṣyāmi", meaning: "I shall tell" },
            { word: "दिव्याः", transliteration: "divyāḥ", meaning: "divine" },
            { word: "हि", transliteration: "hi", meaning: "indeed" },
            { word: "आत्मविभूतयः", transliteration: "ātma-vibhūtayaḥ", meaning: "My own glories" },
            { word: "प्राधान्यतः", transliteration: "prādhānyataḥ", meaning: "chiefly / principally" },
            { word: "कुरुश्रेष्ठ", transliteration: "kuru-śreṣṭha", meaning: "O best of the Kurus" },
            { word: "न अस्ति", transliteration: "na asti", meaning: "there is not" },
            { word: "अन्तः", transliteration: "antaḥ", meaning: "end" },
            { word: "विस्तरस्य", transliteration: "vistarasya", meaning: "of the expanse" },
            { word: "मे", transliteration: "me", meaning: "My" }
          ],
          translation: "The Supreme Lord said: Very well, I shall tell you My divine glories — but only the chief ones, O best of the Kurus, for there is no end to My expanse.",
          modernInterpretation: "Krishna starts with the most FLEX line in all of scripture: 'Sure, I will tell you — but only the HIGHLIGHTS, because the full list would literally never end.' Imagine asking someone about their achievements and they say 'Bro, we would be here till the heat death of the universe.' That is not arrogance when it is LITERALLY TRUE. NASTY ANTO VISTARASYA ME — there is no end to My expanse. Let that sink in. Krishna is not showing off. He is stating a mathematical fact about infinity. You cannot list every expression of the divine any more than you can count every wave in the ocean. So He will give Arjuna a CURATED playlist — the greatest hits. PRADHANYATAH — only the principal ones. This is God saying 'I will give you the Top 100, but know that the actual playlist has infinite songs.' Every sunrise, every act of kindness, every perfectly timed joke, every moment of unexpected beauty — that is a vibhuti you will never see on this list. Krishna is about to drop the most epic 'About Me' section ever written. LinkedIn influencers could NEVER."
        },
        {
          chapter: 10,
          sloka: 20,
          devanagari: "अहमात्मा गुडाकेश सर्वभूताशयस्थितः ।\nअहमादिश्च मध्यं च भूतानामन्त एव च ॥२०॥",
          transliteration: "aham ātmā guḍākeśa sarva-bhūtāśaya-sthitaḥ |\naham ādiś ca madhyaṁ ca bhūtānām anta eva ca ||20||",
          words: [
            { word: "अहम्", transliteration: "aham", meaning: "I" },
            { word: "आत्मा", transliteration: "ātmā", meaning: "the Self" },
            { word: "गुडाकेश", transliteration: "guḍākeśa", meaning: "O Gudakesha (conqueror of sleep, Arjuna)" },
            { word: "सर्वभूताशयस्थितः", transliteration: "sarva-bhūtāśaya-sthitaḥ", meaning: "seated in the hearts of all beings" },
            { word: "अहम्", transliteration: "aham", meaning: "I" },
            { word: "आदिः", transliteration: "ādiḥ", meaning: "the beginning" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "मध्यम्", transliteration: "madhyam", meaning: "the middle" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "भूतानाम्", transliteration: "bhūtānām", meaning: "of all beings" },
            { word: "अन्तः", transliteration: "antaḥ", meaning: "the end" },
            { word: "एव", transliteration: "eva", meaning: "also / indeed" },
            { word: "च", transliteration: "ca", meaning: "and" }
          ],
          translation: "I am the Self, O Gudakesha, seated in the hearts of all beings. I am the beginning, the middle, and the end of all beings.",
          modernInterpretation: "This. This is the verse that BREAKS EVERYTHING OPEN. Before listing any specific glory, Krishna drops the FOUNDATION: I am the ATMA — the Self — sitting inside EVERY living being. Not in a temple. Not in the sky. IN YOU. Right now. Reading this. That voice in your head that just said 'wait, what?' — THAT is where Krishna says He lives. SARVA-BHUTA-ASHAYA-STHITAH. In the heart of ALL beings. The autorickshaw driver. The stray dog. The CEO. The chai wallah. The same divine presence, wearing seven billion human costumes and infinite animal ones. And then the knockout punch: I AM THE BEGINNING, THE MIDDLE, AND THE END. Your first breath — that was Him. This exact moment — that is Him. Your last breath — that will be Him too. Every startup that launched, scaled, and shut down. Every relationship that began with butterflies and ended with silence. Every IPL season — first match excitement, mid-season drama, final ball thriller. He is ALL OF IT. Not just the good parts. Not just the wins. The losses too. The failures. The endings. Because without the end, there is no beginning. Without death, birth means nothing. Krishna is not saying He is the BEST part of your story. He is saying He IS your story — every single page, including the ones you want to tear out. You cannot escape the divine because you ARE the divine, pretending to be a person with a PAN card and an EMI schedule."
        },
        {
          chapter: 10,
          sloka: 21,
          devanagari: "आदित्यानामहं विष्णुर्ज्योतिषां रविरंशुमान् ।\nमरीचिर्मरुतामस्मि नक्षत्राणामहं शशी ॥२१॥",
          transliteration: "ādityānām ahaṁ viṣṇur jyotiṣāṁ ravir aṁśumān |\nmarīcir marutām asmi nakṣatrāṇām ahaṁ śaśī ||21||",
          words: [
            { word: "आदित्यानाम्", transliteration: "ādityānām", meaning: "of the Adityas (twelve solar deities)" },
            { word: "अहम्", transliteration: "aham", meaning: "I am" },
            { word: "विष्णुः", transliteration: "viṣṇuḥ", meaning: "Vishnu" },
            { word: "ज्योतिषाम्", transliteration: "jyotiṣām", meaning: "of lights / luminaries" },
            { word: "रविः", transliteration: "raviḥ", meaning: "the sun" },
            { word: "अंशुमान्", transliteration: "aṁśumān", meaning: "radiant / full of rays" },
            { word: "मरीचिः", transliteration: "marīciḥ", meaning: "Marichi" },
            { word: "मरुताम्", transliteration: "marutām", meaning: "of the Maruts (wind gods)" },
            { word: "अस्मि", transliteration: "asmi", meaning: "I am" },
            { word: "नक्षत्राणाम्", transliteration: "nakṣatrāṇām", meaning: "of the stars / constellations" },
            { word: "अहम्", transliteration: "aham", meaning: "I am" },
            { word: "शशी", transliteration: "śaśī", meaning: "the moon" }
          ],
          translation: "Of the Adityas, I am Vishnu; of lights, the radiant sun; of the Maruts, I am Marichi; among the stars, I am the moon.",
          modernInterpretation: "Krishna starts the VIBHUTI PLAYLIST and goes straight to the TOP. Of solar deities, I am Vishnu — the one who PERVADES everything. Of all lights, I am the sun — not a tubelight, not an LED, the SUN. The original influencer with a reach of 150 million kilometres. Of the wind gods, I am Marichi — the first ray of light, the one who starts it all. Of stars, I am the moon. Now here is the pattern you need to catch: Krishna is not randomly listing things. In EVERY category, He identifies Himself with the PEAK — the one that represents the essence of the whole group. Of food delivery apps, He would be the 5-star rated biryani place. Of IPL bowlers, He would be the one who bowls the final over. Of UPI apps, He would be the one that actually works when the server is down. The teaching is THIS: wherever you see EXCELLENCE, wherever something rises above the ordinary and touches greatness — THAT is a glimpse of the divine. The sun does not try to shine. The moon does not apply for the job of lighting up the night. Excellence is NATURAL when something aligns with its divine nature. So the question for you is: in what category are YOU the vibhuti?"
        },
        {
          chapter: 10,
          sloka: 22,
          devanagari: "वेदानां सामवेदोऽस्मि देवानामस्मि वासवः ।\nइन्द्रियाणां मनश्चास्मि भूतानामस्मि चेतना ॥२२॥",
          transliteration: "vedānāṁ sāma-vedo 'smi devānām asmi vāsavaḥ |\nindriyāṇāṁ manaś cāsmi bhūtānām asmi cetanā ||22||",
          words: [
            { word: "वेदानाम्", transliteration: "vedānām", meaning: "of the Vedas" },
            { word: "सामवेदः", transliteration: "sāma-vedaḥ", meaning: "the Sama Veda" },
            { word: "अस्मि", transliteration: "asmi", meaning: "I am" },
            { word: "देवानाम्", transliteration: "devānām", meaning: "of the devas (gods)" },
            { word: "अस्मि", transliteration: "asmi", meaning: "I am" },
            { word: "वासवः", transliteration: "vāsavaḥ", meaning: "Vasava (Indra)" },
            { word: "इन्द्रियाणाम्", transliteration: "indriyāṇām", meaning: "of the senses" },
            { word: "मनः", transliteration: "manaḥ", meaning: "the mind" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "अस्मि", transliteration: "asmi", meaning: "I am" },
            { word: "भूतानाम्", transliteration: "bhūtānām", meaning: "of beings" },
            { word: "अस्मि", transliteration: "asmi", meaning: "I am" },
            { word: "चेतना", transliteration: "cetanā", meaning: "consciousness" }
          ],
          translation: "Of the Vedas, I am the Sama Veda; of the devas, I am Vasava (Indra); of the senses, I am the mind; in beings, I am consciousness.",
          modernInterpretation: "Of all the Vedas, Krishna picks the Sama Veda — the one set to MUSIC. Not the rituals, not the philosophy, but the one that SINGS. This tells you everything about the divine aesthetic: truth is best delivered through melody. Of playlists, He would be the one song that makes you pull over your car and just SIT there. Of the gods, He is Indra — the KING, the CEO of the celestial board. But the real bombshell is the last two: of senses, I am the MIND, and of beings, I am CONSCIOUSNESS. Read that again. Your eyes see, your ears hear, your tongue tastes — but it is the MIND that makes sense of it all. Without the mind, your senses are just hardware with no operating system. And CETANA — consciousness — is not just one quality among many. It is THE quality that makes you YOU. A rock has matter. A plant has life. But YOU have awareness of your own awareness. You can think ABOUT thinking. That recursive miracle — that is Krishna saying 'Hi, I live here.' Of all the tech in your body, consciousness is the app that came pre-installed and cannot be deleted. It is not a feature. It IS the phone. Every notification you receive, every thought you think, every feeling you feel — it all happens ON the screen of consciousness. And that screen? That is GOD. Not watching you. BEING you."
        },
        {
          chapter: 10,
          sloka: 23,
          devanagari: "रुद्राणां शङ्करश्चास्मि वित्तेशो यक्षरक्षसाम् ।\nवसूनां पावकश्चास्मि मेरुः शिखरिणामहम् ॥२३॥",
          transliteration: "rudrāṇāṁ śaṅkaraś cāsmi vitteśo yakṣa-rakṣasām |\nvasūnāṁ pāvakaś cāsmi meruḥ śikhariṇām aham ||23||",
          words: [
            { word: "रुद्राणाम्", transliteration: "rudrāṇām", meaning: "of the Rudras" },
            { word: "शङ्करः", transliteration: "śaṅkaraḥ", meaning: "Shankara (Shiva)" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "अस्मि", transliteration: "asmi", meaning: "I am" },
            { word: "वित्तेशः", transliteration: "vitteśaḥ", meaning: "lord of wealth (Kubera)" },
            { word: "यक्षरक्षसाम्", transliteration: "yakṣa-rakṣasām", meaning: "of Yakshas and Rakshasas" },
            { word: "वसूनाम्", transliteration: "vasūnām", meaning: "of the Vasus" },
            { word: "पावकः", transliteration: "pāvakaḥ", meaning: "fire (Agni)" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "अस्मि", transliteration: "asmi", meaning: "I am" },
            { word: "मेरुः", transliteration: "meruḥ", meaning: "Mount Meru" },
            { word: "शिखरिणाम्", transliteration: "śikhariṇām", meaning: "of the peaked mountains" },
            { word: "अहम्", transliteration: "aham", meaning: "I am" }
          ],
          translation: "Of the Rudras, I am Shankara; of the Yakshas and Rakshasas, I am Kubera; of the Vasus, I am Agni; of the mountains, I am Meru.",
          modernInterpretation: "Now Krishna is covering EVERY category — even the ones you would not expect. Of the Rudras (the fierce, destructive forces), He is SHANKARA — the one who brings auspiciousness even through destruction. Your startup failed? That destruction was Shankara clearing the ground for something better. Of Yakshas and Rakshasas — the supernatural beings, some good, some terrifying — He is KUBERA, the lord of wealth. Even among the demons and semi-divine creatures, the divine manifests as PROSPERITY. Of social media trolls, He would be the one who accidentally makes a valid point. Of the Vasus, He is AGNI — fire. The element that purifies, transforms, and cannot be contained. Your anger, properly channeled, is Agni. Your passion, burning for the right cause, is Agni. Of mountains, He is MERU — the cosmic axis, the center around which everything revolves. Not Everest (that is just tall). Meru is the mountain that the entire UNIVERSE orbits around. Of coworking spaces in Bangalore, He would be the one where the WiFi actually works and three unicorns were born. The PEAK. The center. The one that everything else is measured against. That is the vibhuti principle: in every category, there is ONE that defines the standard. Find it, and you have found a fingerprint of the divine."
        },
        {
          chapter: 10,
          sloka: 24,
          devanagari: "पुरोधसां च मुख्यं मां विद्धि पार्थ बृहस्पतिम् ।\nसेनानीनामहं स्कन्दः सरसामस्मि सागरः ॥२४॥",
          transliteration: "purodhasāṁ ca mukhyaṁ māṁ viddhi pārtha bṛhaspatim |\nsenānīnām ahaṁ skandaḥ sarasām asmi sāgaraḥ ||24||",
          words: [
            { word: "पुरोधसाम्", transliteration: "purodhasām", meaning: "of priests" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "मुख्यम्", transliteration: "mukhyam", meaning: "the chief" },
            { word: "माम्", transliteration: "mām", meaning: "Me" },
            { word: "विद्धि", transliteration: "viddhi", meaning: "know" },
            { word: "पार्थ", transliteration: "pārtha", meaning: "O Partha (Arjuna)" },
            { word: "बृहस्पतिम्", transliteration: "bṛhaspatim", meaning: "Brihaspati" },
            { word: "सेनानीनाम्", transliteration: "senānīnām", meaning: "of commanders" },
            { word: "अहम्", transliteration: "aham", meaning: "I am" },
            { word: "स्कन्दः", transliteration: "skandaḥ", meaning: "Skanda (Kartikeya)" },
            { word: "सरसाम्", transliteration: "sarasām", meaning: "of water bodies" },
            { word: "अस्मि", transliteration: "asmi", meaning: "I am" },
            { word: "सागरः", transliteration: "sāgaraḥ", meaning: "the ocean" }
          ],
          translation: "Of priests, know Me to be the chief, Brihaspati, O Partha. Of commanders, I am Skanda; of water bodies, I am the ocean.",
          modernInterpretation: "Three absolute UNITS in one verse. BRIHASPATI — the guru of the gods themselves. Not just any priest, but the one who advises the DIVINE BOARD OF DIRECTORS. Of mentors on LinkedIn, He would be the one whose advice actually works and not just sounds good in a carousel post. Then SKANDA — Kartikeya, the commander of the celestial army. Born specifically to lead, specifically to fight, specifically to WIN. Not a general who got promoted through seniority. A leader by NATURE. Of army commanders, He is not the guy with the most medals — He is the one the soldiers would follow into fire without being asked. Of project managers, He would be the one whose Jira board is actually updated. And then SAGARA — the ocean. Not a lake. Not a river. Not that water cooler in your office. The OCEAN. The place where all rivers eventually surrender. Every stream, every tributary, every monsoon drain in Mumbai — it all ends up at the ocean. The ocean does not chase water. It does not advertise. It does not run campaigns. It simply EXISTS at such a scale that everything flows toward it. Of careers, the ocean is that senior person who never job-hops because everyone comes to THEM. Be the ocean. Let the rivers find you."
        },
        {
          chapter: 10,
          sloka: 25,
          devanagari: "महर्षीणां भृगुरहं गिरामस्म्येकमक्षरम् ।\nयज्ञानां जपयज्ञोऽस्मि स्थावराणां हिमालयः ॥२५॥",
          transliteration: "maharṣīṇāṁ bhṛgur ahaṁ girām asmy ekam akṣaram |\nyajñānāṁ japa-yajño 'smi sthāvarāṇāṁ himālayaḥ ||25||",
          words: [
            { word: "महर्षीणाम्", transliteration: "maharṣīṇām", meaning: "of the great sages" },
            { word: "भृगुः", transliteration: "bhṛguḥ", meaning: "Bhrigu" },
            { word: "अहम्", transliteration: "aham", meaning: "I am" },
            { word: "गिराम्", transliteration: "girām", meaning: "of words / speech" },
            { word: "अस्मि", transliteration: "asmi", meaning: "I am" },
            { word: "एकम् अक्षरम्", transliteration: "ekam akṣaram", meaning: "the single syllable (Om)" },
            { word: "यज्ञानाम्", transliteration: "yajñānām", meaning: "of sacrifices" },
            { word: "जपयज्ञः", transliteration: "japa-yajñaḥ", meaning: "the sacrifice of silent repetition" },
            { word: "अस्मि", transliteration: "asmi", meaning: "I am" },
            { word: "स्थावराणाम्", transliteration: "sthāvarāṇām", meaning: "of immovable things" },
            { word: "हिमालयः", transliteration: "himālayaḥ", meaning: "the Himalayas" }
          ],
          translation: "Of the great sages, I am Bhrigu; of words, I am the single syllable Om; of sacrifices, I am japa (silent repetition); of immovable things, I am the Himalayas.",
          modernInterpretation: "This verse is DECEPTIVELY simple but contains one of the most RADICAL ideas in the Gita. Of all sacrifices — the grand fire rituals, the horse sacrifices, the elaborate Vedic ceremonies — Krishna says 'I am JAPA.' Silent repetition. No fire. No priest. No budget. Just you, sitting quietly, repeating a mantra in your mind. The MOST POWERFUL spiritual practice is also the CHEAPEST. No subscription required. No premium tier. No temple visit necessary. Just you and a word, repeated until the word disappears and only awareness remains. Of all words, He is OM — the single syllable that contains the entire universe. One sound. Not a paragraph, not a thesis, not a 47-slide deck. ONE SYLLABLE. The divine is not verbose. It is not that colleague who writes 2000-word emails. It is OM. Short. Complete. Infinite. And of immovable things — the HIMALAYAS. Not just a mountain. A RANGE so massive it changes the weather patterns of an entire continent. It has been there since before your civilization started and will be there long after your Instagram account is deactivated. The Himalayas do not trend. They do not need engagement. They just STAND there, being magnificent. Of all things that do not move, God chose the one that makes everything else move AROUND it. Be the Himalaya. Let the clouds come to you."
        },
        {
          chapter: 10,
          sloka: 26,
          devanagari: "अश्वत्थः सर्ववृक्षाणां देवर्षीणां च नारदः ।\nगन्धर्वाणां चित्ररथः सिद्धानां कपिलो मुनिः ॥२६॥",
          transliteration: "aśvatthaḥ sarva-vṛkṣāṇāṁ devarṣīṇāṁ ca nāradaḥ |\ngandharvāṇāṁ citrarathaḥ siddhānāṁ kapilo muniḥ ||26||",
          words: [
            { word: "अश्वत्थः", transliteration: "aśvatthaḥ", meaning: "the Ashvattha (sacred fig / peepal tree)" },
            { word: "सर्ववृक्षाणाम्", transliteration: "sarva-vṛkṣāṇām", meaning: "of all trees" },
            { word: "देवर्षीणाम्", transliteration: "devarṣīṇām", meaning: "of the divine sages" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "नारदः", transliteration: "nāradaḥ", meaning: "Narada" },
            { word: "गन्धर्वाणाम्", transliteration: "gandharvāṇām", meaning: "of the Gandharvas (celestial musicians)" },
            { word: "चित्ररथः", transliteration: "citrarathaḥ", meaning: "Chitraratha" },
            { word: "सिद्धानाम्", transliteration: "siddhānām", meaning: "of the perfected beings" },
            { word: "कपिलः", transliteration: "kapilaḥ", meaning: "Kapila" },
            { word: "मुनिः", transliteration: "muniḥ", meaning: "the sage" }
          ],
          translation: "Of all trees, I am the Ashvattha (sacred fig tree); of the divine sages, I am Narada; of the Gandharvas, I am Chitraratha; of the perfected beings, I am the sage Kapila.",
          modernInterpretation: "The ASHVATTHA — the peepal tree. The tree that gives oxygen 24 hours a day, not just during sunlight. While every other tree takes a night shift break, the peepal keeps working. Of trees, it is the IIT topper who also runs an NGO, plays guitar, AND has a six-pack. It is also the tree under which the Buddha got enlightened. No big deal. Just casual world-changing events under its branches. Then NARADA — the original gossip columnist, the OG WhatsApp uncle, except his gossip always serves a DIVINE PURPOSE. Every time Narada shows up in a story, he creates chaos that eventually leads to a greater good. He is the friend who says something uncomfortable at dinner that forces everyone to deal with the truth. Of podcast hosts, He would be the one whose uncomfortable questions go viral. CHITRARATHA among the Gandharvas — the BEST celestial musician. Of Spotify playlists, the one that makes you feel emotions you did not even know you had. And KAPILA — the founder of Sankhya philosophy, the original systematic thinker. He looked at the universe and said 'Let me categorize this.' Of startup founders, He would be the one who actually built the product before making the pitch deck. The pattern continues: in EVERY field, find the peak, and you have found where the divine chose to show itself most clearly."
        },
        {
          chapter: 10,
          sloka: 27,
          devanagari: "उच्चैःश्रवसमश्वानां विद्धि माममृतोद्भवम् ।\nऐरावतं गजेन्द्राणां नराणां च नराधिपम् ॥२७॥",
          transliteration: "uccaiḥśravasam aśvānāṁ viddhi mām amṛtodbhavam |\nairāvataṁ gajendrāṇāṁ narāṇāṁ ca narādhipam ||27||",
          words: [
            { word: "उच्चैःश्रवसम्", transliteration: "uccaiḥśravasam", meaning: "Ucchaihshravas (celestial horse)" },
            { word: "अश्वानाम्", transliteration: "aśvānām", meaning: "of horses" },
            { word: "विद्धि", transliteration: "viddhi", meaning: "know" },
            { word: "माम्", transliteration: "mām", meaning: "Me" },
            { word: "अमृतोद्भवम्", transliteration: "amṛtodbhavam", meaning: "born of the churning of nectar" },
            { word: "ऐरावतम्", transliteration: "airāvatam", meaning: "Airavata (Indra's elephant)" },
            { word: "गजेन्द्राणाम्", transliteration: "gajendrāṇām", meaning: "of lordly elephants" },
            { word: "नराणाम्", transliteration: "narāṇām", meaning: "of men / humans" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "नराधिपम्", transliteration: "narādhipam", meaning: "the king / monarch" }
          ],
          translation: "Of horses, know Me as Ucchaihshravas, born of nectar; of lordly elephants, Airavata; and among men, the monarch.",
          modernInterpretation: "UCCHAIHSHRAVAS — the divine horse that emerged from the churning of the cosmic ocean. Not bred, not trained, not bought at auction. BORN FROM THE PROCESS OF CREATION ITSELF. When gods and demons churned the ocean together, among the treasures that emerged was this seven-headed flying horse. Of things born from hustle and hard work, He is the UNEXPECTED MIRACLE — the thing you were not even looking for when you started the grind. Every founder who started building one thing and accidentally created something revolutionary — that is Ucchaihshravas energy. AIRAVATA — Indra's elephant. White. Massive. Majestic. The elephant that carries the king of gods. Not just any elephant — THE elephant. Of luxury cars in Mumbai, He would be that one Rolls Royce that makes traffic stop. And then — NARADHIPA — among humans, the KING. Not the richest. Not the most popular. The one who LEADS. The one who carries the RESPONSIBILITY. Being a king in Vedic terms is not about the crown — it is about the WEIGHT of the crown. Of all humans, the divine is most visible in the one who bears the burden of leadership for others. Not influencers. Not celebrities. LEADERS. The ones who lose sleep so others can sleep peacefully. That Zomato delivery guy in the rain at midnight? That is naradhipa energy. Anyone who serves others at personal cost."
        },
        {
          chapter: 10,
          sloka: 28,
          devanagari: "आयुधानामहं वज्रं धेनूनामस्मि कामधुक् ।\nप्रजनश्चास्मि कन्दर्पः सर्पाणामस्मि वासुकिः ॥२८॥",
          transliteration: "āyudhānām ahaṁ vajraṁ dhenūnām asmi kāmadhuk |\nprajanaś cāsmi kandarpaḥ sarpāṇām asmi vāsukiḥ ||28||",
          words: [
            { word: "आयुधानाम्", transliteration: "āyudhānām", meaning: "of weapons" },
            { word: "अहम्", transliteration: "aham", meaning: "I am" },
            { word: "वज्रम्", transliteration: "vajram", meaning: "the thunderbolt" },
            { word: "धेनूनाम्", transliteration: "dhenūnām", meaning: "of cows" },
            { word: "अस्मि", transliteration: "asmi", meaning: "I am" },
            { word: "कामधुक्", transliteration: "kāmadhuk", meaning: "Kamadhenu (wish-fulfilling cow)" },
            { word: "प्रजनः", transliteration: "prajanaḥ", meaning: "the cause of offspring / procreation" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "अस्मि", transliteration: "asmi", meaning: "I am" },
            { word: "कन्दर्पः", transliteration: "kandarpaḥ", meaning: "Kandarpa (Kamadeva, god of love)" },
            { word: "सर्पाणाम्", transliteration: "sarpāṇām", meaning: "of serpents" },
            { word: "अस्मि", transliteration: "asmi", meaning: "I am" },
            { word: "वासुकिः", transliteration: "vāsukiḥ", meaning: "Vasuki" }
          ],
          translation: "Of weapons, I am the thunderbolt; of cows, I am Kamadhuk (the wish-fulfilling cow). I am Kandarpa (the god of love) the cause of offspring; of serpents, I am Vasuki.",
          modernInterpretation: "Four vibhutis, four absolute BANGERS. VAJRA — the thunderbolt. Indra's weapon, made from the bones of a sage who willingly gave his life so the weapon could be forged. The most powerful weapon was born from the most selfless sacrifice. Of weapons in the modern world, it is not the nuclear bomb — it is the TRUTH spoken at the right moment that shatters everything false. KAMADHUK — the wish-fulfilling cow. Whatever you need, she provides. Endlessly. Without exhaustion. Of apps on your phone, she would be the one that somehow does everything — your UPI, your food delivery, your travel booking, your investments — except she never crashes and never charges a convenience fee. She is the original SUPER APP. Then KANDARPA — the god of LOVE and desire, the force behind procreation. Krishna is saying: that pull you feel toward another person, that inexplicable chemistry, that feeling when your eyes meet someone's across a crowded room — THAT IS ME. Not something to be ashamed of. Not something sinful. The very force that keeps humanity GOING is divine. Love is not the enemy of spirituality. Love IS spirituality wearing its most human costume. And finally VASUKI — the serpent king who became the rope for churning the cosmic ocean. Of serpents, not the one that bites, but the one that was USEFUL. The one that served a cosmic purpose. Even among the feared and misunderstood, the divine picks the one that contributed to creation. YOUR most feared quality — that thing about yourself that scares you — might just be your greatest cosmic contribution."
        }
