        {
          chapter: 10,
          sloka: 1,
          devanagari: "श्रीभगवानुवाच ।\nभूय एव महाबाहो शृणु मे परमं वचः ।\nयत्तेऽहं प्रीयमाणाय वक्ष्यामि हितकाम्यया ॥१॥",
          transliteration: "śrī-bhagavān uvāca |\nbhūya eva mahā-bāho śṛṇu me paramaṁ vacaḥ |\nyat te'haṁ prīyamāṇāya vakṣyāmi hita-kāmyayā ||1||",
          words: [
            { word: "श्रीभगवान्", transliteration: "śrī-bhagavān", meaning: "the Supreme Lord" },
            { word: "उवाच", transliteration: "uvāca", meaning: "said" },
            { word: "भूयः", transliteration: "bhūyaḥ", meaning: "again" },
            { word: "एव", transliteration: "eva", meaning: "indeed" },
            { word: "महाबाहो", transliteration: "mahā-bāho", meaning: "O mighty-armed one" },
            { word: "शृणु", transliteration: "śṛṇu", meaning: "hear" },
            { word: "मे", transliteration: "me", meaning: "My" },
            { word: "परमम्", transliteration: "paramam", meaning: "supreme" },
            { word: "वचः", transliteration: "vacaḥ", meaning: "word" },
            { word: "यत्", transliteration: "yat", meaning: "which" },
            { word: "ते", transliteration: "te", meaning: "to you" },
            { word: "अहम्", transliteration: "aham", meaning: "I" },
            { word: "प्रीयमाणाय", transliteration: "prīyamāṇāya", meaning: "to one who is beloved" },
            { word: "वक्ष्यामि", transliteration: "vakṣyāmi", meaning: "I shall declare" },
            { word: "हितकाम्यया", transliteration: "hita-kāmyayā", meaning: "for your benefit" }
          ],
          translation: "The Supreme Lord said: Again, O mighty-armed one, hear My supreme word, which I shall declare to you who are beloved, for your benefit.",
          modernInterpretation: "Welcome to Chapter 10, folks. VIBHUTI YOGA. The chapter where Krishna basically opens His cosmic LinkedIn profile and says 'Let me tell you about My endorsements.' But first — notice the tone. He says 'prīyamāṇāya' — to one who is BELOVED. This is not a lecture. This is not a boss giving a performance review. This is someone who LOVES you, pulling you aside and saying, 'Listen, I am going to tell you something important because I genuinely care about you.'\n\nThink about it — in your life, how many people give you advice because they actually want your good? Your parents sometimes. A real mentor, maybe. Most advice comes with an agenda — 'Do this course' (because I get a referral bonus), 'Join this startup' (because I need co-founders), 'Invest in this' (because I am already invested). But Krishna says 'hita-kāmyayā' — I am telling you this PURELY because I want your welfare. No commission. No affiliate link. No 'use my code KRISHNA10 for 10% off.'\n\nAlso notice — He says 'AGAIN.' He has already explained everything in chapters 7-9. But He is going AGAIN. Because REAL teaching is repetition. Your gym trainer does not tell you once and walk away. Your Carnatic music teacher makes you sing the same varnam 400 times. Krishna is the ultimate guru — He does not get frustrated that you did not get it the first time. He just says 'Cool, let me explain again, differently, with MORE detail.' This is the energy we need from every teacher, every parent, every manager. Not 'I already told you once.' But 'Let me tell you AGAIN, because you matter to me.' That is love. That is divine teaching. Chapter 10 starts HERE."
        },
        {
          chapter: 10,
          sloka: 2,
          devanagari: "न मे विदुः सुरगणाः प्रभवं न महर्षयः ।\nअहमादिर्हि देवानां महर्षीणां च सर्वशः ॥२॥",
          transliteration: "na me viduḥ sura-gaṇāḥ prabhavaṁ na maharṣayaḥ |\naham ādir hi devānāṁ maharṣīṇāṁ ca sarvaśaḥ ||2||",
          words: [
            { word: "न", transliteration: "na", meaning: "not" },
            { word: "मे", transliteration: "me", meaning: "My" },
            { word: "विदुः", transliteration: "viduḥ", meaning: "know" },
            { word: "सुरगणाः", transliteration: "sura-gaṇāḥ", meaning: "hosts of devas" },
            { word: "प्रभवम्", transliteration: "prabhavam", meaning: "origin" },
            { word: "महर्षयः", transliteration: "maharṣayaḥ", meaning: "great sages" },
            { word: "अहम्", transliteration: "aham", meaning: "I" },
            { word: "आदिः", transliteration: "ādiḥ", meaning: "the source/origin" },
            { word: "हि", transliteration: "hi", meaning: "indeed" },
            { word: "देवानाम्", transliteration: "devānām", meaning: "of the devas" },
            { word: "महर्षीणाम्", transliteration: "maharṣīṇām", meaning: "of the great sages" },
            { word: "सर्वशः", transliteration: "sarvaśaḥ", meaning: "in every way" }
          ],
          translation: "Neither the hosts of devas nor the great sages know My origin, for I am the source of the devas and the great sages in every way.",
          modernInterpretation: "This is the ultimate flex — but also the most humbling truth. Krishna says even the DEVAS — Indra, Brahma, the cosmic CEOs running the universe — do not fully know Him. Even the greatest RISHIS — Vasishtha, Vishwamitra, beings who have meditated for thousands of years — cannot fully comprehend His origin.\n\nWhy? Because YOU CANNOT KNOW WHAT CREATED YOU. The painting cannot fully understand the painter. The code cannot fully debug the programmer. Your iPhone does not know who Tim Cook is. The CREATION can never fully wrap its head around the CREATOR because the creator is always bigger than anything the creation can imagine.\n\nThis is why every time science discovers something, there is something deeper behind it. Atoms? Surprise — there are subatomic particles. Subatomic particles? Surprise — there is quantum foam. It is turtles all the way down. And Krishna is saying, 'I am the turtle at the VERY bottom — and even that is not the full picture.' No amount of IIT-level intellect, no UPSC topper's analytical brain, no PhD from MIT can fully grasp the ORIGIN of origins. Not because we are stupid, but because the INFINITE cannot be contained by the finite. And accepting that is actually the BEGINNING of wisdom."
        },
        {
          chapter: 10,
          sloka: 3,
          devanagari: "यो मामजमनादिं च वेत्ति लोकमहेश्वरम् ।\nअसम्मूढः स मर्त्येषु सर्वपापैः प्रमुच्यते ॥३॥",
          transliteration: "yo mām ajam anādiṁ ca vetti loka-maheśvaram |\nasammūḍhaḥ sa martyeṣu sarva-pāpaiḥ pramucyate ||3||",
          words: [
            { word: "यः", transliteration: "yaḥ", meaning: "he who" },
            { word: "माम्", transliteration: "mām", meaning: "Me" },
            { word: "अजम्", transliteration: "ajam", meaning: "unborn" },
            { word: "अनादिम्", transliteration: "anādim", meaning: "beginningless" },
            { word: "वेत्ति", transliteration: "vetti", meaning: "knows" },
            { word: "लोकमहेश्वरम्", transliteration: "loka-maheśvaram", meaning: "great Lord of the worlds" },
            { word: "असम्मूढः", transliteration: "asammūḍhaḥ", meaning: "undeluded" },
            { word: "सः", transliteration: "saḥ", meaning: "he" },
            { word: "मर्त्येषु", transliteration: "martyeṣu", meaning: "among mortals" },
            { word: "सर्वपापैः", transliteration: "sarva-pāpaiḥ", meaning: "from all sins" },
            { word: "प्रमुच्यते", transliteration: "pramucyate", meaning: "is freed" }
          ],
          translation: "He who knows Me as unborn, beginningless, and the great Lord of the worlds — he among mortals is undeluded and freed from all sins.",
          modernInterpretation: "This is the ultimate cheat code. Krishna says if you truly KNOW — not just intellectually accept, but deeply REALIZE — that He is UNBORN (aja), WITHOUT BEGINNING (anādi), and the SUPREME LORD of all worlds, then you become 'asammūḍha' — UNDELUDED. And when delusion goes, ALL sins go with it.\n\nThink about it. Why do we sin? Because we are CONFUSED about what matters. We cheat because we think money will make us happy. We lie because we think image is everything. We hurt others because we think 'me first' is the way. ALL sin comes from DELUSION — a wrong understanding of reality. So Krishna is saying: fix the ROOT and the entire tree corrects itself.\n\nIt is like debugging code — you can fix a hundred symptoms, or you can find the ONE root cause. Knowing Krishna as the Supreme Origin is that root fix. You do not have to individually fight greed, lust, anger, jealousy. Just understand WHO is running this show, and all those bugs get auto-patched. It is the spiritual equivalent of a factory reset — but instead of losing your data, you lose your delusions. And frankly, those delusions were the REAL viruses anyway."
        },
        {
          chapter: 10,
          sloka: 4,
          devanagari: "बुद्धिर्ज्ञानमसम्मोहः क्षमा सत्यं दमः शमः ।\nसुखं दुःखं भवोऽभावो भयं चाभयमेव च ॥४॥\nअहिंसा समता तुष्टिस्तपो दानं यशोऽयशः ।\nभवन्ति भावा भूतानां मत्त एव पृथग्विधाः ॥५॥",
          transliteration: "buddhir jñānam asammohaḥ kṣamā satyaṁ damaḥ śamaḥ |\nsukhaṁ duḥkhaṁ bhavo'bhāvo bhayaṁ cābhayam eva ca ||4||\nahiṁsā samatā tuṣṭis tapo dānaṁ yaśo'yaśaḥ |\nbhavanti bhāvā bhūtānāṁ matta eva pṛthag-vidhāḥ ||5||",
          words: [
            { word: "बुद्धिः", transliteration: "buddhiḥ", meaning: "intelligence" },
            { word: "ज्ञानम्", transliteration: "jñānam", meaning: "knowledge" },
            { word: "असम्मोहः", transliteration: "asammohaḥ", meaning: "freedom from delusion" },
            { word: "क्षमा", transliteration: "kṣamā", meaning: "forgiveness" },
            { word: "सत्यम्", transliteration: "satyam", meaning: "truth" },
            { word: "दमः", transliteration: "damaḥ", meaning: "self-control (of senses)" },
            { word: "शमः", transliteration: "śamaḥ", meaning: "calmness (of mind)" },
            { word: "सुखम्", transliteration: "sukham", meaning: "pleasure" },
            { word: "दुःखम्", transliteration: "duḥkham", meaning: "pain" },
            { word: "भवः", transliteration: "bhavaḥ", meaning: "birth/existence" },
            { word: "अभावः", transliteration: "abhāvaḥ", meaning: "death/non-existence" },
            { word: "भयम्", transliteration: "bhayam", meaning: "fear" },
            { word: "अभयम्", transliteration: "abhayam", meaning: "fearlessness" },
            { word: "अहिंसा", transliteration: "ahiṁsā", meaning: "non-violence" },
            { word: "समता", transliteration: "samatā", meaning: "equanimity" },
            { word: "तुष्टिः", transliteration: "tuṣṭiḥ", meaning: "contentment" },
            { word: "तपः", transliteration: "tapaḥ", meaning: "austerity" },
            { word: "दानम्", transliteration: "dānam", meaning: "charity" },
            { word: "यशः", transliteration: "yaśaḥ", meaning: "fame" },
            { word: "अयशः", transliteration: "ayaśaḥ", meaning: "infamy" },
            { word: "भवन्ति", transliteration: "bhavanti", meaning: "arise" },
            { word: "भावाः", transliteration: "bhāvāḥ", meaning: "qualities/states" },
            { word: "भूतानाम्", transliteration: "bhūtānām", meaning: "of beings" },
            { word: "मत्तः", transliteration: "mattaḥ", meaning: "from Me" },
            { word: "एव", transliteration: "eva", meaning: "alone" },
            { word: "पृथग्विधाः", transliteration: "pṛthag-vidhāḥ", meaning: "of various kinds" }
          ],
          translation: "Intelligence, knowledge, freedom from delusion, forgiveness, truth, self-control, calmness, pleasure, pain, birth, death, fear, fearlessness, non-violence, equanimity, contentment, austerity, charity, fame, infamy — all these various qualities of beings arise from Me alone.",
          modernInterpretation: "This is mind-blowing if you really let it sink in. Krishna is saying EVERYTHING comes from Him. Not just the good stuff — EVERYTHING. Intelligence AND confusion. Pleasure AND pain. Fame AND infamy. Fear AND fearlessness. He is not just the highlight reel — He is the behind-the-scenes footage too.\n\nWe love to say 'God gave me success' but when failure comes, we blame luck, horoscope, or Mercury retrograde. Krishna says NO — I am in ALL of it. The joy of your wedding day AND the pain of heartbreak. The thrill of your IPL team winning AND the crushing defeat. The contentment after a good meal AND the hunger that drives you to order on Swiggy at 2 AM.\n\nThis is RADICAL THEOLOGY. Most religions say God is only the good. Krishna says I am the FULL SPECTRUM. Because in a universe where everything is divine, nothing is truly outside the divine. Pain teaches. Fear protects. Even infamy has its purpose. The person who has never failed has never truly learned. So next time life hits you with something terrible, remember — even THAT quality, that experience, that state of being is arising from the same source as your greatest joy. It is ALL divine. Every bit of it."
        },
        {
          chapter: 10,
          sloka: 6,
          devanagari: "महर्षयः सप्त पूर्वे चत्वारो मनवस्तथा ।\nमद्भावा मानसा जाता येषां लोक इमाः प्रजाः ॥६॥",
          transliteration: "maharṣayaḥ sapta pūrve catvāro manavas tathā |\nmad-bhāvā mānasā jātā yeṣāṁ loka imāḥ prajāḥ ||6||",
          words: [
            { word: "महर्षयः", transliteration: "maharṣayaḥ", meaning: "the great sages" },
            { word: "सप्त", transliteration: "sapta", meaning: "seven" },
            { word: "पूर्वे", transliteration: "pūrve", meaning: "ancient" },
            { word: "चत्वारः", transliteration: "catvāraḥ", meaning: "four" },
            { word: "मनवः", transliteration: "manavaḥ", meaning: "Manus" },
            { word: "तथा", transliteration: "tathā", meaning: "also" },
            { word: "मद्भावाः", transliteration: "mad-bhāvāḥ", meaning: "born of My nature" },
            { word: "मानसाः", transliteration: "mānasāḥ", meaning: "from the mind" },
            { word: "जाताः", transliteration: "jātāḥ", meaning: "born" },
            { word: "येषाम्", transliteration: "yeṣām", meaning: "of whom" },
            { word: "लोके", transliteration: "loke", meaning: "in the world" },
            { word: "इमाः", transliteration: "imāḥ", meaning: "these" },
            { word: "प्रजाः", transliteration: "prajāḥ", meaning: "beings/creatures" }
          ],
          translation: "The seven great sages, the four ancient Manus, and all beings in the world are born from My mind.",
          modernInterpretation: "Krishna just casually drops that the seven Maharishis — Marichi, Atri, Angiras, Pulastya, Pulaha, Kratu, Vasishtha — and the four Manus (the progenitors of humanity) were all BORN FROM HIS MIND. Not from a factory. Not from a lab. From His THOUGHT. He literally THOUGHT them into existence.\n\nImagine if your THOUGHTS could create entire civilizations. You think about pizza and an entire pizza ecosystem comes into existence — farmers, chefs, Zomato delivery guys, the whole thing. That is what Krishna does, except with COSMIC BEINGS who then create everything else. He is the founder who created the founding team who built the company called 'Universe.'\n\nThe word 'mānasā' — from the mind — is key. It means creation is fundamentally a MENTAL act, not a physical one. The universe is not manufactured — it is IMAGINED. And every creature in every world traces back to that one cosmic imagination. You, me, your neighbor's annoying dog, the auto driver who takes the long route — all of us are thoughts in the mind of the Divine. Let that humble you next time you think you are self-made."
        },
        {
          chapter: 10,
          sloka: 7,
          devanagari: "एतां विभूतिं योगं च मम यो वेत्ति तत्त्वतः ।\nसोऽविकम्पेन योगेन युज्यते नात्र संशयः ॥७॥",
          transliteration: "etāṁ vibhūtiṁ yogaṁ ca mama yo vetti tattvataḥ |\nso'vikampena yogena yujyate nātra saṁśayaḥ ||7||",
          words: [
            { word: "एताम्", transliteration: "etām", meaning: "this" },
            { word: "विभूतिम्", transliteration: "vibhūtim", meaning: "glory/divine manifestation" },
            { word: "योगम्", transliteration: "yogam", meaning: "mystic power" },
            { word: "मम", transliteration: "mama", meaning: "My" },
            { word: "यः", transliteration: "yaḥ", meaning: "he who" },
            { word: "वेत्ति", transliteration: "vetti", meaning: "knows" },
            { word: "तत्त्वतः", transliteration: "tattvataḥ", meaning: "in truth" },
            { word: "सः", transliteration: "saḥ", meaning: "he" },
            { word: "अविकम्पेन", transliteration: "avikampena", meaning: "unwavering" },
            { word: "योगेन", transliteration: "yogena", meaning: "with yoga" },
            { word: "युज्यते", transliteration: "yujyate", meaning: "is united" },
            { word: "न", transliteration: "na", meaning: "not" },
            { word: "अत्र", transliteration: "atra", meaning: "here" },
            { word: "संशयः", transliteration: "saṁśayaḥ", meaning: "doubt" }
          ],
          translation: "He who truly knows this glory and power of Mine is endowed with unwavering yoga — of this there is no doubt.",
          modernInterpretation: "Krishna gives a GUARANTEE here — 'nātra saṁśayaḥ' — there is NO DOUBT about this. In a world where everything comes with terms and conditions — your Swiggy coupon, your insurance policy, your gym membership — Krishna gives an UNCONDITIONAL promise. Know My vibhūti (glory) and yoga (power) in TRUTH, and you get UNWAVERING connection.\n\nThe key word is 'tattvataḥ' — in TRUTH, in ESSENCE. Not surface-level knowledge. Not just reading about it on Instagram reels. TRULY knowing. The difference between knowing food recipes on YouTube and actually being a chef. Between reading about swimming and diving into the ocean.\n\nAnd the reward? 'Avikampena yogena' — UNSHAKABLE yoga. Not the yoga that wavers when your startup fails. Not the faith that crumbles when someone you love gets sick. UNWAVERING. Like a mountain that does not care about the weather. Markets crash? Unshaken. Health fails? Still connected. Career collapses? Still anchored. That is what real spiritual knowledge gives you — not immunity from life, but immunity from being DESTROYED by life."
        },
        {
          chapter: 10,
          sloka: 8,
          devanagari: "अहं सर्वस्य प्रभवो मत्तः सर्वं प्रवर्तते ।\nइति मत्वा भजन्ते मां बुधा भावसमन्विताः ॥८॥",
          transliteration: "ahaṁ sarvasya prabhavo mattaḥ sarvaṁ pravartate |\niti matvā bhajante māṁ budhā bhāva-samanvitāḥ ||8||",
          words: [
            { word: "अहम्", transliteration: "aham", meaning: "I" },
            { word: "सर्वस्य", transliteration: "sarvasya", meaning: "of everything" },
            { word: "प्रभवः", transliteration: "prabhavaḥ", meaning: "the source/origin" },
            { word: "मत्तः", transliteration: "mattaḥ", meaning: "from Me" },
            { word: "सर्वम्", transliteration: "sarvam", meaning: "everything" },
            { word: "प्रवर्तते", transliteration: "pravartate", meaning: "emerges/proceeds" },
            { word: "इति", transliteration: "iti", meaning: "thus" },
            { word: "मत्वा", transliteration: "matvā", meaning: "knowing" },
            { word: "भजन्ते", transliteration: "bhajante", meaning: "worship" },
            { word: "माम्", transliteration: "mām", meaning: "Me" },
            { word: "बुधाः", transliteration: "budhāḥ", meaning: "the wise" },
            { word: "भावसमन्विताः", transliteration: "bhāva-samanvitāḥ", meaning: "endowed with deep feeling/devotion" }
          ],
          translation: "I am the source of everything; from Me all creation emerges. Knowing this, the wise worship Me, endowed with deep feeling.",
          modernInterpretation: "THIS. This is the verse that should be tattooed on the soul of every seeker. 'Ahaṁ sarvasya prabhavaḥ' — I am the SOURCE of EVERYTHING. Not some things. Not just the temple bells and incense sticks. EVERYTHING. The algorithm that shows you that reel at 2 AM? It runs on physics, which runs on mathematics, which runs on logic, which runs on consciousness, which runs on HIM. The chai you had this morning? The tea leaf grew from soil, nourished by rain, powered by sun, held by gravity — all of which trace back to ONE source.\n\nAnd what do the WISE do when they realize this? They do not just intellectually nod. They worship with BHĀVA — with DEEP FEELING. Not mechanical ritual. Not transactional prayer ('God, give me promotion and I will break 108 coconuts'). But genuine, overflowing, heart-cracking DEVOTION. The kind where you see a sunset and your eyes fill with tears because you FEEL the presence behind the beauty. The kind where a baby's laugh makes you sense something INFINITE playing through something tiny.\n\n'Budhāḥ' — the WISE — not the rich, not the powerful, not the famous. The WISE. Because wisdom is not about what you know. It is about what you FEEL when you truly know. A scientist can study the ocean and write papers. A wise person studies the ocean and falls to their knees. THAT is bhāva-samanvitāḥ. That is the difference between information and TRANSFORMATION. Krishna is not asking for your rituals. He is asking for your HEART. And when you give it — when you truly see Him as the source of EVERYTHING — something inside you shifts permanently. You stop fighting life. You stop resisting. You start seeing every moment, every encounter, every breath as a conversation with the Divine. And THAT, my friends, is when religion ends and REAL spirituality begins."
        },
        {
          chapter: 10,
          sloka: 9,
          devanagari: "मच्चित्ता मद्गतप्राणा बोधयन्तः परस्परम् ।\nकथयन्तश्च मां नित्यं तुष्यन्ति च रमन्ति च ॥९॥",
          transliteration: "mac-cittā mad-gata-prāṇā bodhayantaḥ parasparam |\nkathayantaś ca māṁ nityaṁ tuṣyanti ca ramanti ca ||9||",
          words: [
            { word: "मच्चित्ताः", transliteration: "mac-cittāḥ", meaning: "minds fixed on Me" },
            { word: "मद्गतप्राणाः", transliteration: "mad-gata-prāṇāḥ", meaning: "lives surrendered to Me" },
            { word: "बोधयन्तः", transliteration: "bodhayantaḥ", meaning: "enlightening" },
            { word: "परस्परम्", transliteration: "parasparam", meaning: "one another" },
            { word: "कथयन्तः", transliteration: "kathayantaḥ", meaning: "speaking of" },
            { word: "माम्", transliteration: "mām", meaning: "Me" },
            { word: "नित्यम्", transliteration: "nityam", meaning: "always" },
            { word: "तुष्यन्ति", transliteration: "tuṣyanti", meaning: "are content" },
            { word: "रमन्ति", transliteration: "ramanti", meaning: "delight" }
          ],
          translation: "With their minds fixed on Me, their lives surrendered to Me, enlightening one another, always speaking of Me, they are content and delighted.",
          modernInterpretation: "This verse is the original description of SATSANG — spiritual community. Krishna describes devotees who are so absorbed in Him that they NATURALLY talk about Him, teach each other, and find joy in that connection. This is not forced Sunday school attendance. This is people who are genuinely OBSESSED — like a WhatsApp group where everyone actually WANTS to be there.\n\nThink about it — when you love cricket, you naturally find other cricket fans and talk for hours about Dhoni's helicopter shot. When you love food, you and your friends share restaurant discoveries without anyone forcing you. Krishna says His devotees do the same — they 'kathayantaḥ' (speak of Me) and 'bodhayantaḥ' (enlighten each other) NATURALLY, because it brings them 'tuṣṭi' (contentment) and 'rati' (delight).\n\nAnd notice — it is not a solo journey. 'Parasparam' — MUTUALLY. They uplift EACH OTHER. No guru sitting on a golden throne while disciples grovel. It is a community of equals, all pointing each other toward the Divine. The best satsang is not a lecture — it is a conversation where everyone leaves wiser than they came."
        },
        {
          chapter: 10,
          sloka: 10,
          devanagari: "तेषां सततयुक्तानां भजतां प्रीतिपूर्वकम् ।\nददामि बुद्धियोगं तं येन मामुपयान्ति ते ॥१०॥",
          transliteration: "teṣāṁ satata-yuktānāṁ bhajatāṁ prīti-pūrvakam |\ndadāmi buddhi-yogaṁ taṁ yena mām upayānti te ||10||",
          words: [
            { word: "तेषाम्", transliteration: "teṣām", meaning: "to them" },
            { word: "सततयुक्तानाम्", transliteration: "satata-yuktānām", meaning: "constantly united" },
            { word: "भजताम्", transliteration: "bhajatām", meaning: "who worship" },
            { word: "प्रीतिपूर्वकम्", transliteration: "prīti-pūrvakam", meaning: "with love" },
            { word: "ददामि", transliteration: "dadāmi", meaning: "I give" },
            { word: "बुद्धियोगम्", transliteration: "buddhi-yogam", meaning: "yoga of understanding" },
            { word: "तम्", transliteration: "tam", meaning: "that" },
            { word: "येन", transliteration: "yena", meaning: "by which" },
            { word: "माम्", transliteration: "mām", meaning: "Me" },
            { word: "उपयान्ति", transliteration: "upayānti", meaning: "come to" },
            { word: "ते", transliteration: "te", meaning: "they" }
          ],
          translation: "To those who are constantly united and who worship Me with love, I give the yoga of understanding (buddhi-yoga) by which they come to Me.",
          modernInterpretation: "This is the most PERSONAL promise Krishna makes. He says — you do YOUR part (love Me, stay connected), and I will PERSONALLY give you the intelligence to reach Me. 'Dadāmi' — I GIVE. First person. Not 'it will happen' or 'the universe will provide.' I, KRISHNA, PERSONALLY, will give you buddhi-yoga — the CLARITY of understanding that leads you HOME.\n\nTwo conditions: 'satata-yuktānām' — CONSTANTLY connected, not just when you are in trouble. And 'prīti-pūrvakam' — with LOVE, not with fear or greed. If you come to God only during board exams and job interviews, this deal does not apply. If you pray only because you are scared of hell, this deal does not apply. But if you genuinely, consistently, lovingly stay connected — He PERSONALLY upgrades your spiritual GPS.\n\nThis is like having a direct line to the CEO. Not through HR, not through a chatbot, not through a support ticket. DIRECT. And what does He give? Not money, not fame, not a better Instagram following. He gives BUDDHI — the understanding that dissolves all confusion. Because once you have THAT, you do not need anything else. You find your way HOME."
        },
        {
          chapter: 10,
          sloka: 11,
          devanagari: "तेषामेवानुकम्पार्थमहमज्ञानजं तमः ।\nनाशयाम्यात्मभावस्थो ज्ञानदीपेन भास्वता ॥११॥",
          transliteration: "teṣām evānukampārtham aham ajñāna-jaṁ tamaḥ |\nnāśayāmy ātma-bhāva-stho jñāna-dīpena bhāsvatā ||11||",
          words: [
            { word: "तेषाम्", transliteration: "teṣām", meaning: "for them" },
            { word: "एव", transliteration: "eva", meaning: "indeed" },
            { word: "अनुकम्पार्थम्", transliteration: "anukampārtham", meaning: "out of compassion" },
            { word: "अहम्", transliteration: "aham", meaning: "I" },
            { word: "अज्ञानजम्", transliteration: "ajñāna-jam", meaning: "born of ignorance" },
            { word: "तमः", transliteration: "tamaḥ", meaning: "darkness" },
            { word: "नाशयामि", transliteration: "nāśayāmi", meaning: "destroy" },
            { word: "आत्मभावस्थः", transliteration: "ātma-bhāva-sthaḥ", meaning: "dwelling in their hearts" },
            { word: "ज्ञानदीपेन", transliteration: "jñāna-dīpena", meaning: "with the lamp of knowledge" },
            { word: "भास्वता", transliteration: "bhāsvatā", meaning: "shining/radiant" }
          ],
          translation: "Out of compassion for them, I, dwelling in their hearts, destroy the darkness born of ignorance with the shining lamp of knowledge.",
          modernInterpretation: "Read this verse slowly. Then read it again. This might be the most BEAUTIFUL verse in the entire Gita.\n\nKrishna says — out of pure COMPASSION (anukampā), He does not send you a self-help book. He does not forward you a motivational quote. He HIMSELF — dwelling INSIDE your heart (ātma-bhāva-sthaḥ) — lights a LAMP of knowledge and burns away your darkness. He is not sitting in some distant heaven. He is RIGHT THERE, inside you, waiting with a lit diya in His hands.\n\nPicture this: you are in a dark room. You have been stumbling, hitting walls, tripping over furniture — confused, hurt, lost. And then someone who was ALWAYS in that room with you — someone you could not see — gently lights a lamp. Not a floodlight that blinds you. A DIYA. Warm. Gentle. Just enough to show you where you are and where the door is. That is what Krishna does.\n\nHe does not yell 'WHY ARE YOU IN THE DARK?' like your relatives at a family function. He does not post your darkness on social media. He does not judge. He simply LIGHTS THE LAMP. 'Jñāna-dīpena bhāsvatā' — with the RADIANT lamp of knowledge. And the darkness? It does not fight back. It does not argue. It simply CEASES TO EXIST. Because darkness was never a thing — it was just the absence of light.\n\nYour confusion, your pain, your years of wrong decisions — they are not permanent stains. They are just darkness. And the lamp is already inside you. Krishna is already holding it. You just need to stop insisting that the darkness is all there is."
        },
        {
          chapter: 10,
          sloka: 12,
          devanagari: "अर्जुन उवाच ।\nपरं ब्रह्म परं धाम पवित्रं परमं भवान् ।\nपुरुषं शाश्वतं दिव्यमादिदेवमजं विभुम् ॥१२॥",
          transliteration: "arjuna uvāca |\nparaṁ brahma paraṁ dhāma pavitraṁ paramaṁ bhavān |\npuruṣaṁ śāśvataṁ divyam ādi-devam ajaṁ vibhum ||12||",
          words: [
            { word: "अर्जुन", transliteration: "arjuna", meaning: "Arjuna" },
            { word: "उवाच", transliteration: "uvāca", meaning: "said" },
            { word: "परम्", transliteration: "param", meaning: "supreme" },
            { word: "ब्रह्म", transliteration: "brahma", meaning: "Brahman (Ultimate Reality)" },
            { word: "परम्", transliteration: "param", meaning: "supreme" },
            { word: "धाम", transliteration: "dhāma", meaning: "abode" },
            { word: "पवित्रम्", transliteration: "pavitram", meaning: "purifier" },
            { word: "परमम्", transliteration: "paramam", meaning: "supreme" },
            { word: "भवान्", transliteration: "bhavān", meaning: "You" },
            { word: "पुरुषम्", transliteration: "puruṣam", meaning: "Person/Being" },
            { word: "शाश्वतम्", transliteration: "śāśvatam", meaning: "eternal" },
            { word: "दिव्यम्", transliteration: "divyam", meaning: "divine" },
            { word: "आदिदेवम्", transliteration: "ādi-devam", meaning: "primal God" },
            { word: "अजम्", transliteration: "ajam", meaning: "unborn" },
            { word: "विभुम्", transliteration: "vibhum", meaning: "all-pervading" }
          ],
          translation: "Arjuna said: You are the Supreme Brahman, the supreme abode, the supreme purifier, the eternal divine Person, the primal God, unborn and all-pervading.",
          modernInterpretation: "Arjuna FINALLY gets it. After nine chapters of questions, doubts, confusion, and cosmic revelations, something has CLICKED. And when he speaks, he does not say 'I think You might be God.' He says it with FULL CONVICTION — param brahma, param dhāma, pavitram paramam. Supreme Brahman. Supreme Abode. Supreme Purifier. No hedging. No 'maybe.' No 'in my humble opinion.'\n\nThis is the moment in every spiritual journey when intellectual understanding becomes LIVED EXPERIENCE. It is like the difference between reading about Bangalore weather and actually standing in the rain on MG Road. Theory became reality. And once that shift happens, there is no going back.\n\nNotice the words Arjuna uses — ādi-devam (PRIMAL God, the first of all gods), ajam (UNBORN — never created), vibhum (ALL-PERVADING — everywhere at once). This is not casual praise. This is Arjuna deploying the most precise theological vocabulary available. He is not just impressed — he is TRANSFORMED. The warrior who was crying in Chapter 1 is now speaking like a philosopher-saint in Chapter 10. THAT is what proximity to truth does to you."
        },
        {
          chapter: 10,
          sloka: 13,
          devanagari: "आहुस्त्वामृषयः सर्वे देवर्षिर्नारदस्तथा ।\nअसितो देवलो व्यासः स्वयं चैव ब्रवीषि मे ॥१३॥",
          transliteration: "āhus tvām ṛṣayaḥ sarve devarṣir nāradas tathā |\nasito devalo vyāsaḥ svayaṁ caiva bravīṣi me ||13||",
          words: [
            { word: "आहुः", transliteration: "āhuḥ", meaning: "declare" },
            { word: "त्वाम्", transliteration: "tvām", meaning: "You" },
            { word: "ऋषयः", transliteration: "ṛṣayaḥ", meaning: "sages" },
            { word: "सर्वे", transliteration: "sarve", meaning: "all" },
            { word: "देवर्षिः", transliteration: "devarṣiḥ", meaning: "divine sage" },
            { word: "नारदः", transliteration: "nāradaḥ", meaning: "Narada" },
            { word: "तथा", transliteration: "tathā", meaning: "also" },
            { word: "असितः", transliteration: "asitaḥ", meaning: "Asita" },
            { word: "देवलः", transliteration: "devalaḥ", meaning: "Devala" },
            { word: "व्यासः", transliteration: "vyāsaḥ", meaning: "Vyasa" },
            { word: "स्वयम्", transliteration: "svayam", meaning: "Yourself" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "एव", transliteration: "eva", meaning: "indeed" },
            { word: "ब्रवीषि", transliteration: "bravīṣi", meaning: "You tell" },
            { word: "मे", transliteration: "me", meaning: "me" }
          ],
          translation: "All the sages declare this of You, as does the divine sage Narada, Asita, Devala, Vyasa — and now You Yourself tell me.",
          modernInterpretation: "Arjuna is doing something very smart here — he is CROSS-REFERENCING. He is saying, 'It is not just me saying this. ALL the sages say it. Narada says it. Asita says it. Devala says it. Vyasa — the greatest compiler of knowledge in history — says it. AND You Yourself are confirming it.' This is peer-reviewed spirituality.\n\nIn today's world, we would say Arjuna checked the Google reviews before committing. Five-star rating from Narada. Verified purchase review from Vyasa. Recommended by Asita and Devala. And then the PRODUCT ITSELF confirmed its own features. What more validation do you need?\n\nBut there is a deeper point. Arjuna is showing that TRUE faith is not blind. He has evidence from multiple independent sources — sages from different traditions, different time periods, all saying the same thing. And THEN Krishna Himself confirms it. This is not gullibility — this is CONVERGENT evidence. When every GPS system, every map, and the person who BUILT the road all tell you to turn right, you turn right. Arjuna has reached that point of clarity."
        },
        {
          chapter: 10,
          sloka: 14,
          devanagari: "सर्वमेतदृतं मन्ये यन्मां वदसि केशव ।\nन हि ते भगवन्व्यक्तिं विदुर्देवा न दानवाः ॥१४॥",
          transliteration: "sarvam etad ṛtaṁ manye yan māṁ vadasi keśava |\nna hi te bhagavan vyaktiṁ vidur devā na dānavāḥ ||14||",
          words: [
            { word: "सर्वम्", transliteration: "sarvam", meaning: "all" },
            { word: "एतत्", transliteration: "etat", meaning: "this" },
            { word: "ऋतम्", transliteration: "ṛtam", meaning: "true" },
            { word: "मन्ये", transliteration: "manye", meaning: "I hold/accept" },
            { word: "यत्", transliteration: "yat", meaning: "that which" },
            { word: "माम्", transliteration: "mām", meaning: "to me" },
            { word: "वदसि", transliteration: "vadasi", meaning: "You tell" },
            { word: "केशव", transliteration: "keśava", meaning: "O Keshava (Krishna)" },
            { word: "न", transliteration: "na", meaning: "not" },
            { word: "हि", transliteration: "hi", meaning: "indeed" },
            { word: "ते", transliteration: "te", meaning: "Your" },
            { word: "भगवन्", transliteration: "bhagavan", meaning: "O Lord" },
            { word: "व्यक्तिम्", transliteration: "vyaktim", meaning: "manifestation/personality" },
            { word: "विदुः", transliteration: "viduḥ", meaning: "know" },
            { word: "देवाः", transliteration: "devāḥ", meaning: "the devas" },
            { word: "दानवाः", transliteration: "dānavāḥ", meaning: "the danavas (demons)" }
          ],
          translation: "I hold all that You have told me to be true, O Keshava. Indeed, O Lord, neither the devas nor the danavas know Your manifestation.",
          modernInterpretation: "This is Arjuna's declaration of TOTAL FAITH. 'Sarvam etad ṛtaṁ manye' — I accept ALL of this as TRUE. Not 'most of it.' Not 'the parts that are convenient.' ALL of it. This is the moment the student fully SURRENDERS to the teaching. And there is something beautiful about the word 'ṛtam' — it does not just mean 'true' in a factual sense. It means TRUE in a cosmic sense — aligned with the fundamental order of reality.\n\nAnd then Arjuna adds the humbling coda — even the DEVAS (gods) and DANAVAS (demons) do not fully know Your manifestation. Think about that. The most powerful beings in existence, whether good or evil, whether divine or demonic — NONE of them can fully comprehend Krishna. Not because they are not smart enough, but because the INFINITE cannot be boxed by the finite.\n\nThis is Arjuna saying, 'I may not understand everything, but I TRUST everything You say.' And that trust is not weakness — it is the highest form of intelligence. Because sometimes the smartest thing you can do is admit that some things are beyond your comprehension and trust the one who DOES comprehend. Like a patient trusting a surgeon. You do not need to understand every step of the operation. You need to trust the hands that hold the scalpel. Arjuna trusts the hands that hold the universe."
        }