[
        {
          chapter: 14,
          sloka: 1,
          devanagari: "श्रीभगवानुवाच ।\nपरं भूयः प्रवक्ष्यामि ज्ञानानां ज्ञानमुत्तमम् ।\nयज्ज्ञात्वा मुनयः सर्वे परां सिद्धिमितो गताः ॥१॥",
          transliteration: "śrī-bhagavān uvāca |\nparaṁ bhūyaḥ pravakṣyāmi jñānānāṁ jñānam uttamam |\nyaj jñātvā munayaḥ sarve parāṁ siddhim ito gatāḥ ||1||",
          words: [
            { word: "श्रीभगवान्", transliteration: "śrī-bhagavān", meaning: "the Supreme Lord" },
            { word: "उवाच", transliteration: "uvāca", meaning: "said" },
            { word: "परम्", transliteration: "param", meaning: "supreme/transcendental" },
            { word: "भूयः", transliteration: "bhūyaḥ", meaning: "again" },
            { word: "प्रवक्ष्यामि", transliteration: "pravakṣyāmi", meaning: "I shall declare" },
            { word: "ज्ञानानाम्", transliteration: "jñānānām", meaning: "of all knowledge" },
            { word: "ज्ञानम्", transliteration: "jñānam", meaning: "knowledge" },
            { word: "उत्तमम्", transliteration: "uttamam", meaning: "the highest" },
            { word: "यत्", transliteration: "yat", meaning: "which" },
            { word: "ज्ञात्वा", transliteration: "jñātvā", meaning: "having known" },
            { word: "मुनयः", transliteration: "munayaḥ", meaning: "the sages" },
            { word: "सर्वे", transliteration: "sarve", meaning: "all" },
            { word: "पराम्", transliteration: "parām", meaning: "supreme" },
            { word: "सिद्धिम्", transliteration: "siddhim", meaning: "perfection" },
            { word: "इतः", transliteration: "itaḥ", meaning: "from this (world)" },
            { word: "गताः", transliteration: "gatāḥ", meaning: "have attained" }
          ],
          translation: "The Supreme Lord said: I shall again declare that supreme knowledge, the best of all knowledge, having known which all the sages have attained the highest perfection from this world.",
          modernInterpretation: "Welcome to Chapter 14, folks — GUNATRAYA VIBHAGA YOGA — The Yoga of the Three Gunas. And Krishna opens with what is essentially the ULTIMATE sales pitch. He says, 'I am going to tell you the BEST knowledge there is — the KNOWLEDGE of all knowledges.' Not good knowledge. Not great knowledge. UTTAMAM — the SUPREME knowledge. The kind of knowledge that every sage who ever existed used to reach PERFECTION.\n\nThink about it. If someone told you, 'I know the one thing that every successful person in history knew — every Buddha, every Rishi, every enlightened being — and I am about to tell you for FREE,' would you not lean in? That is exactly what Krishna is doing. He is saying this knowledge is so powerful that EVERYONE who has ever truly understood it has achieved the highest state of existence. Not some of them. ALL of them. A 100% success rate. No coaching institute in Kota can promise that.\n\nAnd notice He says 'BHUYAH' — AGAIN. This is not the first time He is sharing deep knowledge. He has been dropping wisdom since Chapter 2. But He keeps coming back to say, 'Wait, there is MORE.' It is like a TV show that keeps getting better each season. Chapter 13 was about the field and the knower. Now Chapter 14 is about the three FORCES that operate within that field. If Chapter 13 gave you the MAP, Chapter 14 gives you the WEATHER REPORT. And trust me, you NEED to know the weather before you step outside."
        },
        {
          chapter: 14,
          sloka: 2,
          devanagari: "इदं ज्ञानमुपाश्रित्य मम साधर्म्यमागताः ।\nसर्गेऽपि नोपजायन्ते प्रलये न व्यथन्ति च ॥२॥",
          transliteration: "idaṁ jñānam upāśritya mama sādharmyam āgatāḥ |\nsarge 'pi nopajāyante pralaye na vyathanti ca ||2||",
          words: [
            { word: "इदम्", transliteration: "idam", meaning: "this" },
            { word: "ज्ञानम्", transliteration: "jñānam", meaning: "knowledge" },
            { word: "उपाश्रित्य", transliteration: "upāśritya", meaning: "taking refuge in" },
            { word: "मम", transliteration: "mama", meaning: "My" },
            { word: "साधर्म्यम्", transliteration: "sādharmyam", meaning: "same nature/identity" },
            { word: "आगताः", transliteration: "āgatāḥ", meaning: "having attained" },
            { word: "सर्गे", transliteration: "sarge", meaning: "in creation" },
            { word: "अपि", transliteration: "api", meaning: "even" },
            { word: "न", transliteration: "na", meaning: "not" },
            { word: "उपजायन्ते", transliteration: "upajāyante", meaning: "are born" },
            { word: "प्रलये", transliteration: "pralaye", meaning: "in dissolution" },
            { word: "व्यथन्ति", transliteration: "vyathanti", meaning: "are disturbed" },
            { word: "च", transliteration: "ca", meaning: "and" }
          ],
          translation: "By taking refuge in this knowledge and attaining My nature, they are not born again even at the time of creation, nor are they disturbed at the time of dissolution.",
          modernInterpretation: "Krishna just raised the stakes to INFINITY. He says, 'Those who truly grasp this knowledge attain MY nature — SADHARMYAM — and after that, they are not reborn even when the entire UNIVERSE is created again, and they are not destroyed even when the entire universe DISSOLVES.' That is not just moksha. That is PERMANENT cosmic VIP status.\n\nLet that sink in. Hindu cosmology talks about cycles — Srishti (creation) and Pralaya (dissolution). The universe is born, lives, dies, and is reborn. Like a cosmic heartbeat. Even the GODS are recycled in this process. But the one who has this knowledge? They are EXEMPT. They have stepped OFF the merry-go-round entirely. No more birth at creation time. No more panic at destruction time. They have merged with Krishna's own nature.\n\nIt is like the difference between being a CHARACTER in a video game and being the DEVELOPER. Characters live and die when the game runs and resets. But the developer? The developer exists OUTSIDE the game. Creation and destruction are just buttons on their keyboard. Krishna is saying, 'Learn what I am about to teach you, and you graduate from PLAYER to DEVELOPER.' That is the promise of Chapter 14."
        },
        {
          chapter: 14,
          sloka: 3,
          devanagari: "मम योनिर्महद्ब्रह्म तस्मिन्गर्भं दधाम्यहम् ।\nसम्भवः सर्वभूतानां ततो भवति भारत ॥३॥",
          transliteration: "mama yonir mahad brahma tasmin garbhaṁ dadhāmy aham |\nsambhavaḥ sarva-bhūtānāṁ tato bhavati bhārata ||3||",
          words: [
            { word: "मम", transliteration: "mama", meaning: "My" },
            { word: "योनिः", transliteration: "yoniḥ", meaning: "womb/source" },
            { word: "महत्", transliteration: "mahat", meaning: "great/total" },
            { word: "ब्रह्म", transliteration: "brahma", meaning: "Brahman/material nature" },
            { word: "तस्मिन्", transliteration: "tasmin", meaning: "in that" },
            { word: "गर्भम्", transliteration: "garbham", meaning: "seed/embryo" },
            { word: "दधामि", transliteration: "dadhāmi", meaning: "I place" },
            { word: "अहम्", transliteration: "aham", meaning: "I" },
            { word: "सम्भवः", transliteration: "sambhavaḥ", meaning: "the birth/origin" },
            { word: "सर्वभूतानाम्", transliteration: "sarva-bhūtānām", meaning: "of all living beings" },
            { word: "ततः", transliteration: "tataḥ", meaning: "thereafter" },
            { word: "भवति", transliteration: "bhavati", meaning: "becomes possible" },
            { word: "भारत", transliteration: "bhārata", meaning: "O descendant of Bharata" }
          ],
          translation: "The great Brahman (material nature) is My womb. In that I place the seed. From that, O Bharata, is the birth of all living beings.",
          modernInterpretation: "This is one of the most PROFOUND cosmological verses in the entire Gita. Krishna describes the creation of the universe as a cosmic act of CONCEPTION. MAHAD BRAHMA — the great material nature — is the WOMB. And Krishna places the GARBHA — the seed of consciousness — into it. From this union, ALL living beings are born.\n\nThink of it like this — Prakriti (material nature) is like the HARDWARE of the universe. The atoms, molecules, elements, forces — all the raw material. But raw material alone does not produce LIFE. You need SOFTWARE — consciousness, awareness, the spark of existence. Krishna is the one who INSTALLS the software into the hardware. Without Him, Prakriti is just dead matter floating in space. With His seed of consciousness, suddenly there are BEINGS — ants, trees, humans, galaxies of living things.\n\nThis is also a radical verse because Krishna is calling Himself the FATHER of all creation. Not the father of just humans. Not the father of just Hindus. The father of ALL living beings — sarva-bhutanam. Every creature that has ever existed or will ever exist traces its origin to this one act — Krishna placing the seed of consciousness into the womb of material nature. THAT is the moment the universe became ALIVE."
        },
        {
          chapter: 14,
          sloka: 4,
          devanagari: "सर्वयोनिषु कौन्तेय मूर्तयः सम्भवन्ति याः ।\nतासां ब्रह्म महद्योनिरहं बीजप्रदः पिता ॥४॥",
          transliteration: "sarva-yoniṣu kaunteya mūrtayaḥ sambhavanti yāḥ |\ntāsāṁ brahma mahad yonir ahaṁ bīja-pradaḥ pitā ||4||",
          words: [
            { word: "सर्वयोनिषु", transliteration: "sarva-yoniṣu", meaning: "in all species/wombs" },
            { word: "कौन्तेय", transliteration: "kaunteya", meaning: "O son of Kunti" },
            { word: "मूर्तयः", transliteration: "mūrtayaḥ", meaning: "forms/bodies" },
            { word: "सम्भवन्ति", transliteration: "sambhavanti", meaning: "are produced" },
            { word: "याः", transliteration: "yāḥ", meaning: "which" },
            { word: "तासाम्", transliteration: "tāsām", meaning: "of all of them" },
            { word: "ब्रह्म", transliteration: "brahma", meaning: "Brahman/material nature" },
            { word: "महत्", transliteration: "mahat", meaning: "great/total" },
            { word: "योनिः", transliteration: "yoniḥ", meaning: "womb/source" },
            { word: "अहम्", transliteration: "aham", meaning: "I" },
            { word: "बीजप्रदः", transliteration: "bīja-pradaḥ", meaning: "the seed-giving" },
            { word: "पिता", transliteration: "pitā", meaning: "father" }
          ],
          translation: "Whatever forms are produced in all the wombs, O son of Kunti, the great Brahman (material nature) is their womb, and I am the seed-giving father.",
          modernInterpretation: "Krishna makes it CRYSTAL clear now. He says, 'Every form of life — in EVERY species, in EVERY womb — whatever body takes shape anywhere in creation — the MOTHER is Prakriti (material nature), and the FATHER is ME.' BIJA-PRADAH PITA — I am the seed-giving father. This is Krishna declaring cosmic PARENTHOOD.\n\nThe implications are STAGGERING. That dog on the street? Krishna is its father. That mosquito buzzing around your ear at 3 AM? Same father. That tree in your garden? Same father. The bacteria in your gut? Same father. Krishna does not discriminate between species. He does not say 'I am the father of humans' or 'I am the father of the devatas.' He says SARVA-YONISHU — in ALL wombs. Every living being is His child.\n\nIf you TRULY internalize this, your entire relationship with the world changes. You cannot look at ANY creature with contempt anymore. That stray cat is your sibling. That earthworm in the mud is your sibling. We all share the same FATHER — Krishna — and the same MOTHER — Prakriti. This is not some feel-good environmentalist slogan. This is ONTOLOGICAL truth according to the Gita. We are literally ONE FAMILY. Vasudhaiva Kutumbakam is not just a nice saying — it is a SCIENTIFIC FACT of spiritual cosmology."
        },
        {
          chapter: 14,
          sloka: 5,
          devanagari: "सत्त्वं रजस्तम इति गुणाः प्रकृतिसम्भवाः ।\nनिबध्नन्ति महाबाहो देहे देहिनमव्ययम् ॥५॥",
          transliteration: "sattvaṁ rajas tama iti guṇāḥ prakṛti-sambhavāḥ |\nnibadhnanti mahā-bāho dehe dehinam avyayam ||5||",
          words: [
            { word: "सत्त्वम्", transliteration: "sattvam", meaning: "goodness/purity" },
            { word: "रजः", transliteration: "rajaḥ", meaning: "passion/activity" },
            { word: "तमः", transliteration: "tamaḥ", meaning: "ignorance/inertia" },
            { word: "इति", transliteration: "iti", meaning: "thus" },
            { word: "गुणाः", transliteration: "guṇāḥ", meaning: "qualities/modes" },
            { word: "प्रकृतिसम्भवाः", transliteration: "prakṛti-sambhavāḥ", meaning: "born of material nature" },
            { word: "निबध्नन्ति", transliteration: "nibadhnanti", meaning: "bind" },
            { word: "महाबाहो", transliteration: "mahā-bāho", meaning: "O mighty-armed one" },
            { word: "देहे", transliteration: "dehe", meaning: "in the body" },
            { word: "देहिनम्", transliteration: "dehinam", meaning: "the embodied soul" },
            { word: "अव्ययम्", transliteration: "avyayam", meaning: "imperishable" }
          ],
          translation: "Sattva, Rajas, and Tamas — these three gunas (qualities) born of Prakriti (material nature) bind the imperishable embodied soul in the body, O mighty-armed one.",
          modernInterpretation: "HERE IT IS. The MAIN EVENT of Chapter 14. Krishna introduces the THREE GUNAS — the three fundamental forces that run EVERYTHING in material existence. SATTVA (goodness, light, knowledge), RAJAS (passion, activity, restlessness), and TAMAS (ignorance, inertia, darkness). These three are born from Prakriti — material nature — and they BIND the soul to the body.\n\nThink of it like this. The soul is like a BIRD — free, imperishable, meant to soar. But the three gunas are like three different types of CAGES. Sattva is a golden cage — comfortable, beautiful, but still a cage. Rajas is a spinning hamster wheel — you are always running but going nowhere. Tamas is a locked dark room — you cannot even SEE the door. Different cages, different experiences, but ALL of them keep the bird trapped.\n\nThis is the KEY insight. Even SATTVA binds you. Most people think, 'If I become sattvic, I am free.' NO. Sattva is BETTER than rajas and tamas, absolutely, but it is still a guna. It is still a mode of PRAKRITI. True liberation means going BEYOND all three. But first, you need to UNDERSTAND them. You cannot escape a prison you do not even know you are in. And that is what the next few verses are going to do — give you the BLUEPRINT of your prison."
        },
        {
          chapter: 14,
          sloka: 6,
          devanagari: "तत्र सत्त्वं निर्मलत्वात्प्रकाशकमनामयम् ।\nसुखसङ्गेन बध्नाति ज्ञानसङ्गेन चानघ ॥६॥",
          transliteration: "tatra sattvaṁ nirmalatvāt prakāśakam anāmayam |\nsukha-saṅgena badhnāti jñāna-saṅgena cānagha ||6||",
          words: [
            { word: "तत्र", transliteration: "tatra", meaning: "among these" },
            { word: "सत्त्वम्", transliteration: "sattvam", meaning: "the mode of goodness" },
            { word: "निर्मलत्वात्", transliteration: "nirmalatvāt", meaning: "being purest" },
            { word: "प्रकाशकम्", transliteration: "prakāśakam", meaning: "illuminating" },
            { word: "अनामयम्", transliteration: "anāmayam", meaning: "free from disease/distress" },
            { word: "सुखसङ्गेन", transliteration: "sukha-saṅgena", meaning: "by attachment to happiness" },
            { word: "बध्नाति", transliteration: "badhnāti", meaning: "binds" },
            { word: "ज्ञानसङ्गेन", transliteration: "jñāna-saṅgena", meaning: "by attachment to knowledge" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "अनघ", transliteration: "anagha", meaning: "O sinless one" }
          ],
          translation: "Of these, Sattva, being pure, is illuminating and free from distress. It binds by attachment to happiness and by attachment to knowledge, O sinless one.",
          modernInterpretation: "Now Krishna gives us the DETAILED PROFILE of Sattva guna. It is NIRMALA — pure, clean. It is PRAKASHAKA — illuminating, like switching on the lights in a dark room. And it is ANAMAYA — free from disease and suffering. Sounds AMAZING, right? Who would not want to be sattvic? It is the guna of clarity, peace, wisdom. It is the state you are in when you meditate perfectly, when you read something profound and it just CLICKS, when you feel genuinely at peace with the world.\n\nBUT — and this is the BRILLIANT twist — it STILL binds you. How? Through SUKHA-SANGA — attachment to happiness — and JNANA-SANGA — attachment to knowledge. You become so addicted to the FEELING of peace that you cannot function without it. You become so proud of your WISDOM that you start looking down at others. 'I do yoga, I eat organic, I read Vedanta — I am better than you.' THAT is sattva binding you.\n\nIt is like the person who becomes so obsessed with their meditation practice that they get ANGRY when someone disturbs their meditation. Ironic, right? Or the intellectual who reads 500 books on spirituality but cannot have a normal conversation with their neighbor. Sattva is the SILK rope. It does not cut your wrists like rajas or tamas, but it still keeps you tied. The golden handcuffs of the spiritual world. You are comfortable, sure, but you are still not FREE."
        },
        {
          chapter: 14,
          sloka: 7,
          devanagari: "रजो रागात्मकं विद्धि तृष्णासङ्गसमुद्भवम् ।\nतन्निबध्नाति कौन्तेय कर्मसङ्गेन देहिनम् ॥७॥",
          transliteration: "rajo rāgātmakaṁ viddhi tṛṣṇā-saṅga-samudbhavam |\ntan nibadhnāti kaunteya karma-saṅgena dehinam ||7||",
          words: [
            { word: "रजः", transliteration: "rajaḥ", meaning: "the mode of passion" },
            { word: "रागात्मकम्", transliteration: "rāgātmakam", meaning: "of the nature of passion/desire" },
            { word: "विद्धि", transliteration: "viddhi", meaning: "know" },
            { word: "तृष्णा", transliteration: "tṛṣṇā", meaning: "craving/thirst" },
            { word: "सङ्ग", transliteration: "saṅga", meaning: "attachment" },
            { word: "समुद्भवम्", transliteration: "samudbhavam", meaning: "born of" },
            { word: "तत्", transliteration: "tat", meaning: "that" },
            { word: "निबध्नाति", transliteration: "nibadhnāti", meaning: "binds" },
            { word: "कौन्तेय", transliteration: "kaunteya", meaning: "O son of Kunti" },
            { word: "कर्मसङ्गेन", transliteration: "karma-saṅgena", meaning: "by attachment to action" },
            { word: "देहिनम्", transliteration: "dehinam", meaning: "the embodied soul" }
          ],
          translation: "Know that Rajas is of the nature of passion, born of craving and attachment. It binds the embodied soul by attachment to action, O son of Kunti.",
          modernInterpretation: "Now meet RAJAS — the guna that runs the MODERN WORLD. Krishna says rajas is RAGITMAKAM — its very ESSENCE is desire, passion, longing. It is born from TRISHNA (craving) and SANGA (attachment). And it binds you through KARMA-SANGA — attachment to action, attachment to DOING things.\n\nRajas is the energy behind every startup founder working 18-hour days. It is the fire behind every student pulling all-nighters for CAT preparation. It is the force that makes you check your phone 200 times a day, refresh Instagram, swipe on dating apps, chase the next promotion. Rajas says, 'MORE. You need MORE. More money, more fame, more followers, more experience.' It is the guna of HUSTLE CULTURE.\n\nAnd here is the trap — rajas FEELS productive. You feel like you are making progress. You feel ALIVE when you are hustling. But Krishna says it BINDS you through karma-sanga — attachment to action. You become so addicted to DOING that you cannot just BE. You cannot sit still for five minutes without feeling guilty. You cannot take a vacation without checking your email. You define yourself by your OUTPUT — your salary, your designation, your achievements. Take those away, and you have an identity crisis. THAT is rajas binding you. The hamster wheel is spinning, you are running fast, and you THINK you are going somewhere. But look up — you are still in the same cage."
        },
        {
          chapter: 14,
          sloka: 8,
          devanagari: "तमस्त्वज्ञानजं विद्धि मोहनं सर्वदेहिनाम् ।\nप्रमादालस्यनिद्राभिस्तन्निबध्नाति भारत ॥८॥",
          transliteration: "tamas tv ajñāna-jaṁ viddhi mohanaṁ sarva-dehinām |\npramādālasya-nidrābhis tan nibadhnāti bhārata ||8||",
          words: [
            { word: "तमः", transliteration: "tamaḥ", meaning: "the mode of ignorance/darkness" },
            { word: "तु", transliteration: "tu", meaning: "but/indeed" },
            { word: "अज्ञानजम्", transliteration: "ajñāna-jam", meaning: "born of ignorance" },
            { word: "विद्धि", transliteration: "viddhi", meaning: "know" },
            { word: "मोहनम्", transliteration: "mohanam", meaning: "deluding" },
            { word: "सर्वदेहिनाम्", transliteration: "sarva-dehinām", meaning: "of all embodied beings" },
            { word: "प्रमाद", transliteration: "pramāda", meaning: "negligence/heedlessness" },
            { word: "आलस्य", transliteration: "ālasya", meaning: "laziness" },
            { word: "निद्राभिः", transliteration: "nidrābhiḥ", meaning: "by sleep" },
            { word: "तत्", transliteration: "tat", meaning: "that" },
            { word: "निबध्नाति", transliteration: "nibadhnāti", meaning: "binds" },
            { word: "भारत", transliteration: "bhārata", meaning: "O descendant of Bharata" }
          ],
          translation: "But know that Tamas is born of ignorance and deludes all embodied beings. It binds through negligence, laziness, and sleep, O Bharata.",
          modernInterpretation: "And now — TAMAS. The DARK guna. Krishna says tamas is AJNANA-JAM — born of ignorance — and MOHANAM — it DELUDES everyone. And its weapons? PRAMADA (negligence, carelessness), ALASYA (laziness), and NIDRA (excessive sleep). This is the guna of 'I will do it tomorrow,' of binge-watching twelve episodes while your deadline screams, of sleeping until noon on a Tuesday and feeling nothing about it.\n\nTamas is not just physical laziness — it is MENTAL and SPIRITUAL darkness. It is the state where you do not even CARE that you do not care. A rajasic person at least has AMBITION, even if misdirected. A sattvic person has CLARITY. But a tamasic person has NOTHING — no drive, no curiosity, no desire to grow. They are not even trying to escape the cage. They have DECORATED the cage and called it home.\n\nWe ALL know tamas. It is that Sunday afternoon when you scroll mindlessly through reels for three hours, feeling progressively WORSE, but you cannot stop. It is the procrastination that makes you avoid important tasks for WEEKS. It is the emotional numbness where nothing excites you, nothing motivates you, and you just EXIST. Tamas does not attack you with pain like rajas — it sedates you. It is not a wound — it is ANESTHESIA. And the worst part? You do not even realize you are under it because the very NATURE of tamas is DELUSION. You cannot see the darkness when you ARE the darkness."
        },
        {
          chapter: 14,
          sloka: 9,
          devanagari: "सत्त्वं सुखे सञ्जयति रजः कर्मणि भारत ।\nज्ञानमावृत्य तु तमः प्रमादे सञ्जयत्युत ॥९॥",
          transliteration: "sattvaṁ sukhe sañjayati rajaḥ karmaṇi bhārata |\njñānam āvṛtya tu tamaḥ pramāde sañjayaty uta ||9||",
          words: [
            { word: "सत्त्वम्", transliteration: "sattvam", meaning: "mode of goodness" },
            { word: "सुखे", transliteration: "sukhe", meaning: "to happiness" },
            { word: "सञ्जयति", transliteration: "sañjayati", meaning: "attaches" },
            { word: "रजः", transliteration: "rajaḥ", meaning: "mode of passion" },
            { word: "कर्मणि", transliteration: "karmaṇi", meaning: "to action" },
            { word: "भारत", transliteration: "bhārata", meaning: "O descendant of Bharata" },
            { word: "ज्ञानम्", transliteration: "jñānam", meaning: "knowledge" },
            { word: "आवृत्य", transliteration: "āvṛtya", meaning: "covering/veiling" },
            { word: "तु", transliteration: "tu", meaning: "but" },
            { word: "तमः", transliteration: "tamaḥ", meaning: "mode of ignorance" },
            { word: "प्रमादे", transliteration: "pramāde", meaning: "to negligence/heedlessness" },
            { word: "सञ्जयति", transliteration: "sañjayati", meaning: "attaches" },
            { word: "उत", transliteration: "uta", meaning: "indeed" }
          ],
          translation: "Sattva attaches one to happiness, Rajas to action, O Bharata; but Tamas, veiling knowledge, attaches one to negligence.",
          modernInterpretation: "Krishna gives us the SUMMARY FORMULA in one clean verse. Three gunas, three attachments. Sattva hooks you to SUKHA (happiness). Rajas hooks you to KARMA (action). Tamas hooks you to PRAMADA (negligence). It is like three different drugs — sattva is the high of meditation and peace, rajas is the adrenaline of ambition and achievement, tamas is the numbing comfort of doing absolutely nothing.\n\nBut notice what tamas does DIFFERENTLY. Krishna adds the phrase JNANAM AVRITYA — tamas COVERS knowledge first, THEN attaches you to negligence. It does not just make you lazy — it first makes you BLIND and THEN makes you lazy. It is like someone putting a blindfold on you and THEN asking you to walk through a minefield. You do not even know you are in danger. At least with sattva and rajas, you are AWARE of what is happening. With tamas, the awareness itself is destroyed.\n\nThink of the three gunas as three management styles. Sattva is the CEO who loves brainstorming and strategy meetings so much that they never actually LAUNCH anything — paralysis by analysis. Rajas is the CEO who launches ten products a month but burns out the entire team and none of the products are well-built. Tamas is the CEO who never shows up to work and the company slowly dies while they are on a permanent vacation. Different styles, all problematic, all keeping the company from TRUE success."
        },
        {
          chapter: 14,
          sloka: 10,
          devanagari: "रजस्तमश्चाभिभूय सत्त्वं भवति भारत ।\nरजः सत्त्वं तमश्चैव तमः सत्त्वं रजस्तथा ॥१०॥",
          transliteration: "rajas tamaś cābhibhūya sattvaṁ bhavati bhārata |\nrajaḥ sattvaṁ tamaś caiva tamaḥ sattvaṁ rajas tathā ||10||",
          words: [
            { word: "रजः", transliteration: "rajaḥ", meaning: "passion" },
            { word: "तमः", transliteration: "tamaḥ", meaning: "ignorance" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "अभिभूय", transliteration: "abhibhūya", meaning: "overpowering" },
            { word: "सत्त्वम्", transliteration: "sattvam", meaning: "goodness" },
            { word: "भवति", transliteration: "bhavati", meaning: "becomes predominant" },
            { word: "भारत", transliteration: "bhārata", meaning: "O descendant of Bharata" },
            { word: "रजः", transliteration: "rajaḥ", meaning: "passion" },
            { word: "सत्त्वम्", transliteration: "sattvam", meaning: "goodness" },
            { word: "तमः", transliteration: "tamaḥ", meaning: "ignorance" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "एव", transliteration: "eva", meaning: "indeed" },
            { word: "तथा", transliteration: "tathā", meaning: "similarly" }
          ],
          translation: "Sometimes Sattva prevails, overpowering Rajas and Tamas, O Bharata. Sometimes Rajas prevails over Sattva and Tamas, and sometimes Tamas prevails over Sattva and Rajas.",
          modernInterpretation: "This verse explains WHY you are a DIFFERENT person at different times of the day. In the morning after meditation, you feel sattvic — clear, peaceful, wise. By afternoon, rajas kicks in — you are ambitious, restless, checking your to-do list. By midnight, tamas dominates — you are binge-eating chips and watching random YouTube videos. SAME person. Three different states. The gunas are constantly COMPETING for dominance inside you.\n\nIt is like a wrestling match with three fighters in the ring simultaneously. Sometimes Sattva pins down the other two and you feel GREAT — you meditate, you read, you feel compassion for everyone. Then Rajas body-slams Sattva and suddenly you are back to chasing money, status, that promotion. Then Tamas sneaks up behind both and puts them in a chokehold — now you cannot get off the couch and your phone battery dies from scrolling.\n\nThis is deeply VALIDATING if you think about it. You are not 'fake' for feeling spiritual in the morning and lazy at night. You are not 'hypocritical' for meditating at 6 AM and losing your temper at 6 PM. The gunas are CONSTANTLY shifting. The key is not to NEVER have rajas or tamas — that is impossible while you are in a material body. The key is to RECOGNIZE which guna is currently driving and to gradually, consciously, increase the time sattva spends in the driver's seat."
        },
        {
          chapter: 14,
          sloka: 11,
          devanagari: "सर्वद्वारेषु देहेऽस्मिन्प्रकाश उपजायते ।\nज्ञानं यदा तदा विद्याद्विवृद्धं सत्त्वमित्युत ॥११॥",
          transliteration: "sarva-dvāreṣu dehe 'smin prakāśa upajāyate |\njñānaṁ yadā tadā vidyād vivṛddhaṁ sattvam ity uta ||11||",
          words: [
            { word: "सर्वद्वारेषु", transliteration: "sarva-dvāreṣu", meaning: "in all the gates (senses)" },
            { word: "देहे", transliteration: "dehe", meaning: "in the body" },
            { word: "अस्मिन्", transliteration: "asmin", meaning: "in this" },
            { word: "प्रकाशः", transliteration: "prakāśaḥ", meaning: "illumination/light" },
            { word: "उपजायते", transliteration: "upajāyate", meaning: "arises" },
            { word: "ज्ञानम्", transliteration: "jñānam", meaning: "knowledge" },
            { word: "यदा", transliteration: "yadā", meaning: "when" },
            { word: "तदा", transliteration: "tadā", meaning: "then" },
            { word: "विद्यात्", transliteration: "vidyāt", meaning: "one should know" },
            { word: "विवृद्धम्", transliteration: "vivṛddham", meaning: "has increased" },
            { word: "सत्त्वम्", transliteration: "sattvam", meaning: "the mode of goodness" },
            { word: "इति", transliteration: "iti", meaning: "thus" },
            { word: "उत", transliteration: "uta", meaning: "indeed" }
          ],
          translation: "When the light of knowledge shines through all the gates (senses) of the body, then it should be known that Sattva is predominant.",
          modernInterpretation: "Krishna gives you a DIAGNOSTIC TOOL. He says, 'Want to know if sattva is dominant in you right now? Check if LIGHT is shining through all your senses.' SARVA-DVARESHU — through ALL the gates of the body. The gates are your senses — eyes, ears, nose, mouth, skin, and mind.\n\nWhen sattva is dominant, your eyes see BEAUTY in ordinary things. Your ears hear MEANING in words. Your mind grasps CONCEPTS with clarity. Everything feels BRIGHT, not because the external world changed, but because YOUR internal lens is clean. It is like cleaning a dirty window — the sun was always shining, but now you can actually SEE it.\n\nYou know those rare mornings when you wake up and everything just MAKES SENSE? When you feel sharp, focused, grateful, and somehow the same commute that usually annoys you feels peaceful? That is sattva being VIVRUDDHA — increased, dominant. Your perception is not clouded by desire (rajas) or delusion (tamas). You are seeing things AS THEY ARE. This is why ancient rishis recommended sattvic food, sattvic company, sattvic environments — not because they were health freaks, but because they understood that your INNER state determines your OUTER experience. The world does not change. YOUR guna changes. And everything follows."
        },
        {
          chapter: 14,
          sloka: 12,
          devanagari: "लोभः प्रवृत्तिरारम्भः कर्मणामशमः स्पृहा ।\nरजस्येतानि जायन्ते विवृद्धे भरतर्षभ ॥१२॥",
          transliteration: "lobhaḥ pravṛttir ārambhaḥ karmaṇām aśamaḥ spṛhā |\nrajasy etāni jāyante vivṛddhe bharatarṣabha ||12||",
          words: [
            { word: "लोभः", transliteration: "lobhaḥ", meaning: "greed" },
            { word: "प्रवृत्तिः", transliteration: "pravṛttiḥ", meaning: "activity/inclination" },
            { word: "आरम्भः", transliteration: "ārambhaḥ", meaning: "undertaking/initiation" },
            { word: "कर्मणाम्", transliteration: "karmaṇām", meaning: "of actions" },
            { word: "अशमः", transliteration: "aśamaḥ", meaning: "restlessness/unrest" },
            { word: "स्पृहा", transliteration: "spṛhā", meaning: "longing/desire" },
            { word: "रजसि", transliteration: "rajasi", meaning: "in the mode of passion" },
            { word: "एतानि", transliteration: "etāni", meaning: "these" },
            { word: "जायन्ते", transliteration: "jāyante", meaning: "arise" },
            { word: "विवृद्धे", transliteration: "vivṛddhe", meaning: "when increased/predominant" },
            { word: "भरतर्षभ", transliteration: "bharatarṣabha", meaning: "O best of the Bharatas" }
          ],
          translation: "Greed, activity, the undertaking of actions, restlessness, and longing — these arise when Rajas is predominant, O best of the Bharatas.",
          modernInterpretation: "Now Krishna gives you the RAJAS CHECKLIST. Five symptoms: LOBHA (greed — wanting more), PRAVRITTI (constant activity — cannot sit still), ARAMBHA (always starting new projects), ASHAMA (restlessness — inner unease), and SPRIHA (craving — longing for things you do not have). If you have three or more of these right now, congratulations — rajas is running your operating system.\n\nDoes this sound familiar? It should. Because this is the DEFAULT MODE of modern civilization. The entire global economy runs on rajas. Advertising creates SPRIHA (longing). Capitalism rewards PRAVRITTI (activity). Startup culture celebrates ARAMBHA (starting things). Social media amplifies ASHAMA (restlessness). And the whole system is fueled by LOBHA (greed). We have built an ENTIRE WORLD on rajasic energy and then wonder why everyone is anxious and burned out.\n\nNotice Krishna does not say rajas is EVIL. He says these things JĀYANTE — they ARISE. It is just what happens when rajas is dominant. Like how rain happens when clouds gather. It is not moral judgment — it is METEOROLOGY of the soul. But if you are AWARE that rajas is dominant, you can take steps. You can slow down. You can question your cravings. You can ask, 'Do I REALLY need this, or is rajas just doing its thing?' Awareness is the first step toward CHOICE."
        },
        {
          chapter: 14,
          sloka: 13,
          devanagari: "अप्रकाशोऽप्रवृत्तिश्च प्रमादो मोह एव च ।\nतमस्येतानि जायन्ते विवृद्धे कुरुनन्दन ॥१३॥",
          transliteration: "aprakāśo 'pravṛttiś ca pramādo moha eva ca |\ntamasy etāni jāyante vivṛddhe kuru-nandana ||13||",
          words: [
            { word: "अप्रकाशः", transliteration: "aprakāśaḥ", meaning: "darkness/lack of illumination" },
            { word: "अप्रवृत्तिः", transliteration: "apravṛttiḥ", meaning: "inactivity/stagnation" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "प्रमादः", transliteration: "pramādaḥ", meaning: "negligence/carelessness" },
            { word: "मोहः", transliteration: "mohaḥ", meaning: "delusion" },
            { word: "एव", transliteration: "eva", meaning: "indeed" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "तमसि", transliteration: "tamasi", meaning: "in the mode of darkness/ignorance" },
            { word: "एतानि", transliteration: "etāni", meaning: "these" },
            { word: "जायन्ते", transliteration: "jāyante", meaning: "arise" },
            { word: "विवृद्धे", transliteration: "vivṛddhe", meaning: "when increased/predominant" },
            { word: "कुरुनन्दन", transliteration: "kuru-nandana", meaning: "O joy of the Kurus" }
          ],
          translation: "Darkness, inactivity, negligence, and delusion — these arise when Tamas is predominant, O joy of the Kurus.",
          modernInterpretation: "And here is the TAMAS CHECKLIST. Four symptoms: APRAKASHA (darkness — lack of clarity, everything feels grey and meaningless), APRAVRITTI (inactivity — zero motivation to do ANYTHING), PRAMADA (negligence — not caring about things that matter), and MOHA (delusion — confused thinking, wrong conclusions, inability to distinguish right from wrong).\n\nThis is the description of CLINICAL depression in 5000-year-old language. When tamas dominates, the lights go OUT. Not just physically — MENTALLY. You lose the ability to see meaning in anything. Your passions die. Your ambitions vanish. You stop caring about your health, your relationships, your goals. And the cruelest part? MOHA — delusion — convinces you that THIS state is REALITY. That life really IS meaningless. That nothing really MATTERS. That everyone who seems happy is just faking it.\n\nContrast this with verse 11 and 12. When sattva increases — LIGHT through all senses. When rajas increases — ACTIVITY, desire, projects. When tamas increases — DARKNESS, inaction, negligence, delusion. Krishna is giving you a REAL-TIME self-assessment framework that is more accurate than any personality test on the internet. Forget Myers-Briggs. Forget your zodiac sign. Ask yourself RIGHT NOW — am I experiencing light, activity, or darkness? THAT tells you which guna is in charge. And once you know who is in charge, you can start a REVOLUTION from within."
        },
        {
          chapter: 14,
          sloka: 14,
          devanagari: "यदा सत्त्वे प्रवृद्धे तु प्रलयं याति देहभृत् ।\nतदोत्तमविदां लोकानमलान्प्रतिपद्यते ॥१४॥",
          transliteration: "yadā sattve pravṛddhe tu pralayaṁ yāti deha-bhṛt |\ntadottama-vidāṁ lokān amalān pratipadyate ||14||",
          words: [
            { word: "यदा", transliteration: "yadā", meaning: "when" },
            { word: "सत्त्वे", transliteration: "sattve", meaning: "in the mode of goodness" },
            { word: "प्रवृद्धे", transliteration: "pravṛddhe", meaning: "being predominant" },
            { word: "तु", transliteration: "tu", meaning: "indeed" },
            { word: "प्रलयम्", transliteration: "pralayam", meaning: "dissolution/death" },
            { word: "याति", transliteration: "yāti", meaning: "goes to/meets" },
            { word: "देहभृत्", transliteration: "deha-bhṛt", meaning: "the embodied being" },
            { word: "तदा", transliteration: "tadā", meaning: "then" },
            { word: "उत्तमविदाम्", transliteration: "uttama-vidām", meaning: "of the knowers of the highest" },
            { word: "लोकान्", transliteration: "lokān", meaning: "worlds/realms" },
            { word: "अमलान्", transliteration: "amalān", meaning: "pure/spotless" },
            { word: "प्रतिपद्यते", transliteration: "pratipadyate", meaning: "attains" }
          ],
          translation: "When the embodied soul meets death while Sattva is predominant, then it attains the pure worlds of those who know the highest.",
          modernInterpretation: "Now Krishna drops the CONSEQUENCES. He says if you die when sattva is dominant — when your last breath is taken in a state of clarity, knowledge, and inner light — you go to the AMALA LOKA — the pure, spotless realms. The worlds of the UTTAMA-VIDA — those who know the highest truths. This is the express elevator going UP.\n\nThis is why Hindu tradition places so much emphasis on the MOMENT of death. It is not superstition — it is based on THIS verse. Your last thought, your last state of consciousness, the guna that is dominant when you leave the body — THAT determines where you go next. It is like your FINAL EXAM. You might have studied all semester, but what matters is what you write in those three hours. Similarly, you might have lived a decent life, but the guna dominant at the MOMENT of death determines your next destination.\n\nBut here is the deeper insight — you do not accidentally become sattvic at the time of death. You cannot live a tamasic life and suddenly switch to sattva in your last moment. It does not work like that. Your death state is the CULMINATION of your life practice. If you have cultivated sattva throughout your life — through pure food, good company, selfless action, meditation, knowledge — then sattva will naturally be dominant when you leave. The time of death is not a LOTTERY. It is a RESULT. Start your sattva practice NOW, because the final exam date is unknown."
        },
]
