[
        {
          chapter: 14,
          sloka: 15,
          devanagari: "रजसि प्रलयं गत्वा कर्मसङ्गिषु जायते ।\nतथा प्रलीनस्तमसि मूढयोनिषु जायते ॥१५॥",
          transliteration: "rajasi pralayaṁ gatvā karma-saṅgiṣu jāyate |\ntathā pralīnas tamasi mūḍha-yoniṣu jāyate ||15||",
          words: [
            { word: "रजसि", transliteration: "rajasi", meaning: "in the mode of passion" },
            { word: "प्रलयम्", transliteration: "pralayam", meaning: "dissolution/death" },
            { word: "गत्वा", transliteration: "gatvā", meaning: "having attained" },
            { word: "कर्मसङ्गिषु", transliteration: "karma-saṅgiṣu", meaning: "among those attached to action" },
            { word: "जायते", transliteration: "jāyate", meaning: "is born" },
            { word: "तथा", transliteration: "tathā", meaning: "similarly" },
            { word: "प्रलीनः", transliteration: "pralīnaḥ", meaning: "being dissolved/dying" },
            { word: "तमसि", transliteration: "tamasi", meaning: "in the mode of ignorance" },
            { word: "मूढयोनिषु", transliteration: "mūḍha-yoniṣu", meaning: "in the wombs of the deluded (lower species)" },
            { word: "जायते", transliteration: "jāyate", meaning: "is born" }
          ],
          translation: "Dying in the mode of passion, one is born among those attached to action. Dying in the mode of ignorance, one is born in the wombs of the deluded (lower species).",
          modernInterpretation: "Krishna continues the CONSEQUENCES framework. Verse 14 told us sattva takes you UP to pure realms. Now He reveals the other two exits. Die in rajas? You are reborn among KARMA-SANGI people — folks obsessed with work, hustle, achievement. You come back into a family, culture, or species where the GRIND never stops. Think of it as being reborn into a hyper-competitive environment — maybe a family that measures everything by salary, or a society that never lets you rest.\n\nDie in tamas? MUDHA-YONISHU — you are born in the wombs of the deluded. Lower species. Animals. Beings that operate purely on instinct without self-awareness. This is not Krishna being cruel — it is just the LAW of consciousness. If you spent your human life in a state of utter darkness, ignorance, and delusion, your consciousness RESONATES with that frequency. And at death, you are tuned to that channel. You get what you VIBRATE at.\n\nThree exits. Three escalators. Sattva takes you UP to pure realms. Rajas keeps you on the SAME FLOOR — human birth, but back on the treadmill. Tamas takes you DOWN to lower species. This is not a threat — it is a NAVIGATION SYSTEM. Krishna is telling you which exit leads where so you can CHOOSE your direction while you still have time. The GPS is showing all routes. Which one are you going to take?"
        },
        {
          chapter: 14,
          sloka: 16,
          devanagari: "कर्मणः सुकृतस्याहुः सात्त्विकं निर्मलं फलम् ।\nरजसस्तु फलं दुःखमज्ञानं तमसः फलम् ॥१६॥",
          transliteration: "karmaṇaḥ sukṛtasyāhuḥ sāttvikaṁ nirmalaṁ phalam |\nrajasas tu phalaṁ duḥkham ajñānaṁ tamasaḥ phalam ||16||",
          words: [
            { word: "कर्मणः", transliteration: "karmaṇaḥ", meaning: "of action" },
            { word: "सुकृतस्य", transliteration: "sukṛtasya", meaning: "of righteous/well-done" },
            { word: "आहुः", transliteration: "āhuḥ", meaning: "they say" },
            { word: "सात्त्विकम्", transliteration: "sāttvikam", meaning: "sattvic/pure" },
            { word: "निर्मलम्", transliteration: "nirmalam", meaning: "pure/spotless" },
            { word: "फलम्", transliteration: "phalam", meaning: "fruit/result" },
            { word: "रजसः", transliteration: "rajasaḥ", meaning: "of passion" },
            { word: "तु", transliteration: "tu", meaning: "but" },
            { word: "फलम्", transliteration: "phalam", meaning: "fruit/result" },
            { word: "दुःखम्", transliteration: "duḥkham", meaning: "sorrow/pain" },
            { word: "अज्ञानम्", transliteration: "ajñānam", meaning: "ignorance" },
            { word: "तमसः", transliteration: "tamasaḥ", meaning: "of darkness/ignorance" },
            { word: "फलम्", transliteration: "phalam", meaning: "fruit/result" }
          ],
          translation: "The fruit of righteous action performed in Sattva is said to be pure and spotless. The fruit of Rajas is sorrow, and the fruit of Tamas is ignorance.",
          modernInterpretation: "Krishna now reveals the FRUIT each guna produces. Sattvic action yields NIRMALA PHALA — pure, spotless results. Rajasic action yields DUHKHA — pain and suffering. Tamasic action yields AJNANA — more ignorance. Notice the PRECISION here. He is not saying sattvic action gives you money. He is saying it gives you PURITY. The reward of doing something right is not material gain — it is INNER CLARITY.\n\nThis explains so much about life. Why does the guy who hustled 24/7 and made crores still feel EMPTY inside? Because rajasic action produces DUHKHA. The money came, but so did the anxiety, the broken relationships, the health issues. The FRUIT of rajas is always bittersweet — you get what you chased, but you also get pain as a free bonus. It is a BOGO deal you did not sign up for — buy one ambition, get one suffering free.\n\nAnd tamas? Its fruit is MORE tamas. Ignorance breeds ignorance. When you waste a day doing nothing, you do not feel refreshed — you feel MORE lethargic the next day. When you avoid a difficult conversation, the problem does not disappear — it gets WORSE and harder to see clearly. Tamas is a DOWNWARD SPIRAL. The less you do, the less you CAN do. The less you know, the less you WANT to know. Only sattva gives you a reward that does not come with a hangover."
        },
        {
          chapter: 14,
          sloka: 17,
          devanagari: "सत्त्वात्सञ्जायते ज्ञानं रजसो लोभ एव च ।\nप्रमादमोहौ तमसो भवतोऽज्ञानमेव च ॥१७॥",
          transliteration: "sattvāt sañjāyate jñānaṁ rajaso lobha eva ca |\npramāda-mohau tamaso bhavato 'jñānam eva ca ||17||",
          words: [
            { word: "सत्त्वात्", transliteration: "sattvāt", meaning: "from sattva/goodness" },
            { word: "सञ्जायते", transliteration: "sañjāyate", meaning: "is born/arises" },
            { word: "ज्ञानम्", transliteration: "jñānam", meaning: "knowledge" },
            { word: "रजसः", transliteration: "rajasaḥ", meaning: "from rajas/passion" },
            { word: "लोभः", transliteration: "lobhaḥ", meaning: "greed" },
            { word: "एव", transliteration: "eva", meaning: "indeed" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "प्रमाद", transliteration: "pramāda", meaning: "negligence" },
            { word: "मोहौ", transliteration: "mohau", meaning: "and delusion" },
            { word: "तमसः", transliteration: "tamasaḥ", meaning: "from tamas/ignorance" },
            { word: "भवतः", transliteration: "bhavataḥ", meaning: "arise" },
            { word: "अज्ञानम्", transliteration: "ajñānam", meaning: "ignorance" },
            { word: "एव", transliteration: "eva", meaning: "indeed" },
            { word: "च", transliteration: "ca", meaning: "and" }
          ],
          translation: "From Sattva arises knowledge, from Rajas arises greed, and from Tamas arise negligence, delusion, and ignorance.",
          modernInterpretation: "This verse is the CAUSAL chain. Krishna is not just telling you the symptoms anymore — He is telling you the OFFSPRING of each guna. Sattva PRODUCES knowledge. Rajas PRODUCES greed. Tamas PRODUCES negligence, delusion, and ignorance. Each guna is a FACTORY and these are its products.\n\nThink about what you PRODUCE in your daily life. When you are sattvic — after a good meditation, a meaningful conversation, deep study — what comes out of you? INSIGHT. Understanding. Wisdom. Ideas that help people. But when rajas takes over — after hours on social media, after comparing yourself to others — what comes out? GREED. Wanting what others have. Planning how to get MORE. And when tamas is in charge — after a week of junk food, zero exercise, and mindless entertainment — what comes out? CONFUSION. Bad decisions. Inability to think clearly.\n\nYour INPUT determines your OUTPUT. Sattvic inputs (good food, good books, good company) produce knowledge. Rajasic inputs (competitive environments, materialistic goals, constant stimulation) produce greed. Tamasic inputs (junk food, toxic media, inactivity) produce ignorance. This is not philosophy — it is ENGINEERING. You are a MACHINE, and the gunas are the FUEL. Put premium fuel in, you get premium performance. Put garbage in, you get garbage out. Krishna figured out GIGO — Garbage In, Garbage Out — five thousand years before computer science."
        },
        {
          chapter: 14,
          sloka: 18,
          devanagari: "ऊर्ध्वं गच्छन्ति सत्त्वस्था मध्ये तिष्ठन्ति राजसाः ।\nजघन्यगुणवृत्तिस्था अधो गच्छन्ति तामसाः ॥१८॥",
          transliteration: "ūrdhvaṁ gacchanti sattva-sthā madhye tiṣṭhanti rājasāḥ |\njaghanya-guṇa-vṛtti-sthā adho gacchanti tāmasāḥ ||18||",
          words: [
            { word: "ऊर्ध्वम्", transliteration: "ūrdhvam", meaning: "upward" },
            { word: "गच्छन्ति", transliteration: "gacchanti", meaning: "go" },
            { word: "सत्त्वस्थाः", transliteration: "sattva-sthāḥ", meaning: "those situated in sattva" },
            { word: "मध्ये", transliteration: "madhye", meaning: "in the middle" },
            { word: "तिष्ठन्ति", transliteration: "tiṣṭhanti", meaning: "remain" },
            { word: "राजसाः", transliteration: "rājasāḥ", meaning: "those in rajas" },
            { word: "जघन्यगुणवृत्तिस्थाः", transliteration: "jaghanya-guṇa-vṛtti-sthāḥ", meaning: "those in the lowest quality/activity" },
            { word: "अधः", transliteration: "adhaḥ", meaning: "downward" },
            { word: "गच्छन्ति", transliteration: "gacchanti", meaning: "go" },
            { word: "तामसाः", transliteration: "tāmasāḥ", meaning: "those in tamas" }
          ],
          translation: "Those situated in Sattva go upward, those in Rajas remain in the middle, and those abiding in the lowest quality of Tamas go downward.",
          modernInterpretation: "This is the ELEVATOR verse. Three directions. Three destinies. URDHVAM GACCHANTI — those in sattva go UP. Higher realms, higher consciousness, eventually liberation. MADHYE TISHTHANTI — those in rajas stay in the MIDDLE. Same floor. Human plane. Back on the wheel. ADHO GACCHANTI — those in tamas go DOWN. Lower realms, lower species, deeper ignorance.\n\nIt is like a building with infinite floors. Sattva is the UP button. Rajas is the STOP button — the elevator just stays where it is, doors opening and closing, going nowhere. Tamas is the DOWN button. And here is the uncomfortable truth — most of us are pressing all three buttons at different times throughout the day. Morning meditation presses UP. Office politics presses STOP. Late-night junk food and doomscrolling presses DOWN. The net direction depends on which button you press MOST.\n\nThis verse also demolishes the idea that all paths lead to the same destination. Krishna is very clear — your GUNA determines your DIRECTION. It is not enough to be a 'good person' in some vague sense. You need to actively cultivate sattva if you want to go UP. Passive existence — even comfortable, rajasic, ambitious existence — keeps you in the MIDDLE at best. And if tamas dominates, you are actively moving BACKWARD. The universe is not a flat road. It is a STAIRCASE. And the gunas determine which direction you are walking on it."
        },
        {
          chapter: 14,
          sloka: 19,
          devanagari: "नान्यं गुणेभ्यः कर्तारं यदा द्रष्टानुपश्यति ।\nगुणेभ्यश्च परं वेत्ति मद्भावं सोऽधिगच्छति ॥१९॥",
          transliteration: "nānyaṁ guṇebhyaḥ kartāraṁ yadā draṣṭānupaśyati |\nguṇebhyaś ca paraṁ vetti mad-bhāvaṁ so 'dhigacchati ||19||",
          words: [
            { word: "न", transliteration: "na", meaning: "not" },
            { word: "अन्यम्", transliteration: "anyam", meaning: "other" },
            { word: "गुणेभ्यः", transliteration: "guṇebhyaḥ", meaning: "than the gunas" },
            { word: "कर्तारम्", transliteration: "kartāram", meaning: "doer/agent" },
            { word: "यदा", transliteration: "yadā", meaning: "when" },
            { word: "द्रष्टा", transliteration: "draṣṭā", meaning: "the seer/witness" },
            { word: "अनुपश्यति", transliteration: "anupaśyati", meaning: "sees properly" },
            { word: "गुणेभ्यः", transliteration: "guṇebhyaḥ", meaning: "than the gunas" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "परम्", transliteration: "param", meaning: "beyond/higher" },
            { word: "वेत्ति", transliteration: "vetti", meaning: "knows" },
            { word: "मद्भावम्", transliteration: "mad-bhāvam", meaning: "My nature/divine state" },
            { word: "सः", transliteration: "saḥ", meaning: "he" },
            { word: "अधिगच्छति", transliteration: "adhigacchati", meaning: "attains" }
          ],
          translation: "When the seer perceives no doer other than the gunas, and knows that which is beyond the gunas, he attains My divine nature.",
          modernInterpretation: "THIS is the TURNING POINT of the entire chapter. Krishna says, 'When a person TRULY sees that the gunas alone are the doers of ALL actions — and simultaneously knows that the SELF is BEYOND the gunas — that person attains MY nature.' Two realizations in one. First: the gunas are doing everything. Second: the real YOU is beyond them.\n\nThis is LIBERATION IN ONE VERSE. Think about what happens when you get angry. Usually you say, 'I am angry.' But Krishna says the TRUTH is: 'Rajas guna is activated in this body-mind system.' When you feel lazy: 'Tamas guna is dominant right now.' When you feel peaceful: 'Sattva guna is currently in charge.' The real YOU — the DRASHTA, the witness, the seer — is NONE of these. You are the one WATCHING all three gunas perform their dance.\n\nIt is like watching a movie. The screen shows action scenes (rajas), dark horror scenes (tamas), and beautiful serene landscapes (sattva). But the SCREEN itself is none of these. The screen is unchanged regardless of what movie plays. YOU are the screen. The gunas are the movie. When you TRULY get this — not intellectually but EXPERIENTIALLY — when you can watch anger arise and think 'Oh, rajas is acting up' instead of 'I AM angry' — that is when you attain MAD-BHAVA, Krishna's own nature. You step out of the movie and realize you were the screen all along."
        },
        {
          chapter: 14,
          sloka: 20,
          devanagari: "गुणानेतानतीत्य त्रीन्देही देहसमुद्भवान् ।\nजन्ममृत्युजरादुःखैर्विमुक्तोऽमृतमश्नुते ॥२०॥",
          transliteration: "guṇān etān atītya trīn dehī deha-samudbhavān |\njanma-mṛtyu-jarā-duḥkhair vimukto 'mṛtam aśnute ||20||",
          words: [
            { word: "गुणान्", transliteration: "guṇān", meaning: "the qualities/modes" },
            { word: "एतान्", transliteration: "etān", meaning: "these" },
            { word: "अतीत्य", transliteration: "atītya", meaning: "having transcended" },
            { word: "त्रीन्", transliteration: "trīn", meaning: "three" },
            { word: "देही", transliteration: "dehī", meaning: "the embodied soul" },
            { word: "देहसमुद्भवान्", transliteration: "deha-samudbhavān", meaning: "arising from the body" },
            { word: "जन्म", transliteration: "janma", meaning: "birth" },
            { word: "मृत्यु", transliteration: "mṛtyu", meaning: "death" },
            { word: "जरा", transliteration: "jarā", meaning: "old age" },
            { word: "दुःखैः", transliteration: "duḥkhaiḥ", meaning: "from sorrows" },
            { word: "विमुक्तः", transliteration: "vimuktaḥ", meaning: "being freed" },
            { word: "अमृतम्", transliteration: "amṛtam", meaning: "immortality/nectar" },
            { word: "अश्नुते", transliteration: "aśnute", meaning: "attains/enjoys" }
          ],
          translation: "When the embodied soul transcends these three gunas that arise from the body, it is freed from birth, death, old age, and sorrow, and attains immortality.",
          modernInterpretation: "Krishna reveals the ULTIMATE PRIZE. Transcend all three gunas and you become FREE from the four fundamental sufferings — JANMA (birth), MRITYU (death), JARA (old age), and DUHKHA (sorrow). And what do you GET instead? AMRITAM — immortality. Not just a long life. DEATHLESSNESS. The nectar of eternal existence.\n\nNotice He says the gunas are DEHA-SAMUDBHAVAN — they arise from the BODY. They are not part of the soul. They are like weather patterns — clouds form, rain falls, sun shines — but the SKY itself is untouched by all of it. The sky does not get wet when it rains. The sky does not burn when the sun blazes. Similarly, your soul does not become sattvic, rajasic, or tamasic. Only your body-mind complex does. Transcendence means REMEMBERING this permanently.\n\nThis verse is the MISSION STATEMENT of all spiritual practice. Why do we meditate? To transcend the gunas. Why do we study scripture? To transcend the gunas. Why do we practice detachment? To transcend the gunas. Every spiritual tool ever invented has ONE goal — to help you step BEYOND these three modes and taste AMRITA, the nectar of your own immortal nature. Birth, death, old age, sorrow — these are not inevitable for the SOUL. They are inevitable only for one who is IDENTIFIED with the gunas. Dis-identify, and you are free. PERMANENTLY."
        },
        {
          chapter: 14,
          sloka: 21,
          devanagari: "अर्जुन उवाच ।\nकैर्लिङ्गैस्त्रीन्गुणानेतानतीतो भवति प्रभो ।\nकिमाचारः कथं चैतांस्त्रीन्गुणानतिवर्तते ॥२१॥",
          transliteration: "arjuna uvāca |\nkair liṅgais trīn guṇān etān atīto bhavati prabho |\nkim ācāraḥ kathaṁ caitāṁs trīn guṇān ativartate ||21||",
          words: [
            { word: "अर्जुन", transliteration: "arjuna", meaning: "Arjuna" },
            { word: "उवाच", transliteration: "uvāca", meaning: "said" },
            { word: "कैः", transliteration: "kaiḥ", meaning: "by what" },
            { word: "लिङ्गैः", transliteration: "liṅgaiḥ", meaning: "signs/marks" },
            { word: "त्रीन्", transliteration: "trīn", meaning: "three" },
            { word: "गुणान्", transliteration: "guṇān", meaning: "gunas/qualities" },
            { word: "एतान्", transliteration: "etān", meaning: "these" },
            { word: "अतीतः", transliteration: "atītaḥ", meaning: "transcended" },
            { word: "भवति", transliteration: "bhavati", meaning: "becomes" },
            { word: "प्रभो", transliteration: "prabho", meaning: "O Lord" },
            { word: "किम्", transliteration: "kim", meaning: "what" },
            { word: "आचारः", transliteration: "ācāraḥ", meaning: "conduct/behavior" },
            { word: "कथम्", transliteration: "katham", meaning: "how" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "एतान्", transliteration: "etān", meaning: "these" },
            { word: "अतिवर्तते", transliteration: "ativartate", meaning: "transcends/goes beyond" }
          ],
          translation: "Arjuna said: By what signs is one who has transcended the three gunas recognized, O Lord? What is his conduct? And how does he transcend the three gunas?",
          modernInterpretation: "Arjuna asks the THREE most practical questions possible. And this is why Arjuna is the PERFECT student. He does not just say 'Oh wow, transcend the gunas, cool bro.' He asks: ONE — what are the SIGNS? How do I IDENTIFY such a person if I meet them on the street? TWO — what is their CONDUCT? How do they actually BEHAVE in daily life? THREE — what is the METHOD? HOW does one actually transcend the gunas?\n\nThese are the questions of a PRACTITIONER, not a philosopher. A philosopher would ask, 'What is the ontological nature of guna-transcendence?' Arjuna asks, 'What does it LOOK like, and how do I DO it?' This is the difference between reading about swimming and actually jumping into the pool. Arjuna wants SWIMMING LESSONS, not a TED talk about water.\n\nAnd notice — he asks all three questions in ONE verse. Efficient. Focused. No rambling. Compare this to Chapter 1 Arjuna who went on for an entire chapter about his confusion. This is a man who has been TRANSFORMED by the teaching. He knows exactly what to ask and asks it cleanly. Three questions, three words essentially — LINGAIH (signs), ACHARAH (conduct), KATHAM (how). This is a student who is READY. And Krishna is about to give him one of the most beautiful answers in the entire Gita."
        },
        {
          chapter: 14,
          sloka: 22,
          devanagari: "श्रीभगवानुवाच ।\nप्रकाशं च प्रवृत्तिं च मोहमेव च पाण्डव ।\nन द्वेष्टि सम्प्रवृत्तानि न निवृत्तानि काङ्क्षति ॥२२॥",
          transliteration: "śrī-bhagavān uvāca |\nprakāśaṁ ca pravṛttiṁ ca moham eva ca pāṇḍava |\nna dveṣṭi sampravṛttāni na nivṛttāni kāṅkṣati ||22||",
          words: [
            { word: "श्रीभगवान्", transliteration: "śrī-bhagavān", meaning: "the Supreme Lord" },
            { word: "उवाच", transliteration: "uvāca", meaning: "said" },
            { word: "प्रकाशम्", transliteration: "prakāśam", meaning: "illumination (sattva)" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "प्रवृत्तिम्", transliteration: "pravṛttim", meaning: "activity (rajas)" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "मोहम्", transliteration: "moham", meaning: "delusion (tamas)" },
            { word: "एव", transliteration: "eva", meaning: "indeed" },
            { word: "पाण्डव", transliteration: "pāṇḍava", meaning: "O son of Pandu" },
            { word: "न", transliteration: "na", meaning: "not" },
            { word: "द्वेष्टि", transliteration: "dveṣṭi", meaning: "hates" },
            { word: "सम्प्रवृत्तानि", transliteration: "sampravṛttāni", meaning: "when present" },
            { word: "न", transliteration: "na", meaning: "not" },
            { word: "निवृत्तानि", transliteration: "nivṛttāni", meaning: "when absent/ceased" },
            { word: "काङ्क्षति", transliteration: "kāṅkṣati", meaning: "desires/longs for" }
          ],
          translation: "The Supreme Lord said: He who does not hate illumination (sattva), activity (rajas), or delusion (tamas) when they arise, O Pandava, nor longs for them when they cease.",
          modernInterpretation: "Krishna begins His answer with the most COUNTERINTUITIVE sign. The guna-transcended person does not FIGHT the gunas. When sattva arises — clarity, peace, knowledge — they do not CLING to it. When rajas arises — activity, desire, restlessness — they do not HATE it. When tamas arises — lethargy, confusion, sleep — they do not PANIC about it. And when any of these STOPS, they do not desperately try to get it back.\n\nThis is RADICAL. Most spiritual seekers spend their entire lives trying to INCREASE sattva and DESTROY rajas and tamas. They fight a war against their own gunas. But Krishna says the truly transcended person has NO war. They watch the gunas come and go like weather. Oh, sattva is here today — nice. Oh, tamas is visiting — okay. Oh, rajas showed up — noted. No clinging, no rejecting. Just WITNESSING.\n\nIt is like living in a house with three roommates. Sattva is the neat, organized roommate who keeps the house clean. Rajas is the hyperactive roommate who is always cooking, working, making noise. Tamas is the roommate who sleeps all day and leaves pizza boxes everywhere. The WISE person does not try to kick anyone out. They just observe, smile, and remember — 'I am not any of these roommates. I am the LANDLORD. They come and go. I stay.' That equanimity, that unshakeable NEUTRALITY toward your own inner states — THAT is the sign of transcendence."
        },
        {
          chapter: 14,
          sloka: 23,
          devanagari: "उदासीनवदासीनो गुणैर्यो न विचाल्यते ।\nगुणा वर्तन्त इत्येव योऽवतिष्ठति नेङ्गते ॥२३॥",
          transliteration: "udāsīna-vad āsīno guṇair yo na vicālyate |\nguṇā vartanta ity evaṁ yo 'vatiṣṭhati neṅgate ||23||",
          words: [
            { word: "उदासीनवत्", transliteration: "udāsīna-vat", meaning: "as if indifferent/neutral" },
            { word: "आसीनः", transliteration: "āsīnaḥ", meaning: "seated/situated" },
            { word: "गुणैः", transliteration: "guṇaiḥ", meaning: "by the gunas" },
            { word: "यः", transliteration: "yaḥ", meaning: "who" },
            { word: "न", transliteration: "na", meaning: "not" },
            { word: "विचाल्यते", transliteration: "vicālyate", meaning: "is disturbed/shaken" },
            { word: "गुणाः", transliteration: "guṇāḥ", meaning: "the gunas" },
            { word: "वर्तन्ते", transliteration: "vartante", meaning: "are operating" },
            { word: "इति", transliteration: "iti", meaning: "thus" },
            { word: "एवम्", transliteration: "evam", meaning: "in this way" },
            { word: "यः", transliteration: "yaḥ", meaning: "who" },
            { word: "अवतिष्ठति", transliteration: "avatiṣṭhati", meaning: "remains firm" },
            { word: "न", transliteration: "na", meaning: "not" },
            { word: "इङ्गते", transliteration: "iṅgate", meaning: "wavers" }
          ],
          translation: "He who sits like one unconcerned, undisturbed by the gunas, who knows that the gunas alone are acting and remains firm without wavering.",
          modernInterpretation: "This verse paints the PERFECT picture of inner freedom. UDASINA-VAT ASINAH — seated as if UNCONCERNED. Not agitated. Not desperate. Not running around trying to control everything. Just SITTING in their own center while the storm of the gunas rages around them. And the key phrase — GUNA VARTANTA ITI — 'the gunas are merely doing their thing.' That is their inner dialogue. Not 'I am happy,' not 'I am sad,' not 'I am lazy' — just 'the gunas are operating.'\n\nThis is the ULTIMATE upgrade in self-talk. Imagine replacing every emotional reaction with this awareness. Instead of 'I am anxious about the exam' — 'Rajas is activated regarding the exam.' Instead of 'I cannot get out of bed' — 'Tamas is currently dominant in the body.' Instead of 'I feel so blissful today' — 'Sattva is having a good day.' You DEPERSONALIZE every experience. You stop making everything about YOU and start seeing it as NATURE doing its job.\n\nNA INGATE — does not WAVER. This person is like a MOUNTAIN in the middle of changing seasons. Summer comes — the mountain does not sweat. Winter comes — the mountain does not shiver. Rain pours — the mountain does not complain. The seasons are the gunas. The mountain is the SELF. Unmoving. Unmoved. UNSHAKEABLE. Not because they are suppressing emotions, but because they genuinely KNOW that they are not those emotions. The gunas are weather. They are the sky."
        },
        {
          chapter: 14,
          sloka: 24,
          devanagari: "समदुःखसुखः स्वस्थः समलोष्टाश्मकाञ्चनः ।\nतुल्यप्रियाप्रियो धीरस्तुल्यनिन्दात्मसंस्तुतिः ॥२४॥",
          transliteration: "sama-duḥkha-sukhaḥ svasthaḥ sama-loṣṭāśma-kāñcanaḥ |\ntulya-priyāpriyo dhīras tulya-nindātma-saṁstutiḥ ||24||",
          words: [
            { word: "समदुःखसुखः", transliteration: "sama-duḥkha-sukhaḥ", meaning: "equal in pleasure and pain" },
            { word: "स्वस्थः", transliteration: "svasthaḥ", meaning: "self-situated/self-poised" },
            { word: "समलोष्टाश्मकाञ्चनः", transliteration: "sama-loṣṭāśma-kāñcanaḥ", meaning: "equal toward a lump of earth, stone, and gold" },
            { word: "तुल्यप्रियाप्रियः", transliteration: "tulya-priyāpriyaḥ", meaning: "equal toward the pleasant and unpleasant" },
            { word: "धीरः", transliteration: "dhīraḥ", meaning: "steady/wise" },
            { word: "तुल्यनिन्दात्मसंस्तुतिः", transliteration: "tulya-nindātma-saṁstutiḥ", meaning: "equal in blame and self-praise" }
          ],
          translation: "He who is equal in pleasure and pain, self-poised, to whom a lump of earth, a stone, and gold are alike, who is the same toward the pleasant and unpleasant, who is wise, and equal in blame and praise.",
          modernInterpretation: "Krishna now lists the QUALITIES in rapid fire. SAMA-DUHKHA-SUKHA — equal in pain and pleasure. Not that they do not FEEL — they feel everything — but their inner STABILITY does not depend on what they feel. SVASTHA — established in the Self. This word is BEAUTIFUL — in Sanskrit, 'svastha' literally means 'situated in one's own Self.' It is the same word used for 'healthy' in Hindi/Sanskrit. True HEALTH, according to Krishna, is being established in your own nature.\n\nSAMA-LOSHTA-ASHMA-KANCHANA — a lump of dirt, a stone, and GOLD are the same to them. This does not mean they cannot tell the difference between dirt and gold. They are not STUPID. It means the gold does not make them EXCITED and the dirt does not make them REPULSED. They see the material reality clearly but are not MOVED by it. Try this experiment — put a pile of gold coins and a pile of mud in front of anyone. Watch their eyes. Watch their body language. THAT involuntary reaction? That is the guna. The transcended person has NO involuntary reaction. They see both with perfect equanimity.\n\nTULYA-NINDA-ATMA-SAMSTUTI — equal when BLAMED and when PRAISED. This is the HARDEST one. Most of us can handle pain better than criticism. Most of us can handle poverty better than insult. But this person? You can praise them to the heavens or drag their name through the mud — their inner state DOES NOT CHANGE. Not because they are arrogant. Not because they do not hear you. Because their sense of identity is not built on other people's OPINIONS. They are SVASTHA — rooted in THEMSELVES. And when you are rooted in the infinite Self, what can any finite opinion add or take away?"
        },
        {
          chapter: 14,
          sloka: 25,
          devanagari: "मानापमानयोस्तुल्यस्तुल्यो मित्रारिपक्षयोः ।\nसर्वारम्भपरित्यागी गुणातीतः स उच्यते ॥२५॥",
          transliteration: "mānāpamānayos tulyas tulyo mitrāri-pakṣayoḥ |\nsarvārambha-parityāgī guṇātītaḥ sa ucyate ||25||",
          words: [
            { word: "मानापमानयोः", transliteration: "mānāpamānayoḥ", meaning: "in honor and dishonor" },
            { word: "तुल्यः", transliteration: "tulyaḥ", meaning: "equal" },
            { word: "तुल्यः", transliteration: "tulyaḥ", meaning: "equal" },
            { word: "मित्रारिपक्षयोः", transliteration: "mitrāri-pakṣayoḥ", meaning: "toward friend and foe factions" },
            { word: "सर्वारम्भपरित्यागी", transliteration: "sarvārambha-parityāgī", meaning: "renouncer of all selfish undertakings" },
            { word: "गुणातीतः", transliteration: "guṇātītaḥ", meaning: "one who has transcended the gunas" },
            { word: "सः", transliteration: "saḥ", meaning: "he" },
            { word: "उच्यते", transliteration: "ucyate", meaning: "is said to be" }
          ],
          translation: "He who is equal in honor and dishonor, equal toward friend and foe, who has renounced all selfish undertakings — he is said to have transcended the gunas.",
          modernInterpretation: "Krishna completes the portrait. MANA-APAMANA — honor and dishonor are the SAME to this person. Award them a Padma Shri or throw tomatoes at them — their inner poise does not shift. MITRA-ARI-PAKSHA — they are equal toward the FACTION of friends and the faction of enemies. They do not have 'sides.' They do not maintain a mental list of allies and opponents. Everyone is just consciousness wearing different costumes.\n\nAnd then the CLINCHER — SARVARAMBHA-PARITYAGI — they have RENOUNCED all selfish undertakings. Not all action — Krishna already established in Chapter 3 that action cannot be avoided. But all SELFISH initiation of action. They do not START things for personal gain anymore. They act only as instruments of the divine, or in response to genuine need. No hidden agendas. No 'what is in it for me.' No networking with an ulterior motive.\n\nAnd then the LABEL — GUNATITA. Beyond the gunas. This is the official TITLE. If you can be equal in honor and dishonor, friend and enemy, and have given up selfish ambitions — you are GUNATITA. Notice how BEHAVIORAL these signs are. Krishna does not say 'the one who can levitate' or 'the one who glows in the dark.' The signs of transcendence are completely PRACTICAL — equanimity, evenness, selflessness. You do not need supernatural powers to be beyond the gunas. You need MATURITY of consciousness. And that is available to ANYONE who sincerely practices."
        },
        {
          chapter: 14,
          sloka: 26,
          devanagari: "मां च योऽव्यभिचारेण भक्तियोगेन सेवते ।\nस गुणान्समतीत्यैतान्ब्रह्मभूयाय कल्पते ॥२६॥",
          transliteration: "māṁ ca yo 'vyabhicāreṇa bhakti-yogena sevate |\nsa guṇān samatītyaitān brahma-bhūyāya kalpate ||26||",
          words: [
            { word: "माम्", transliteration: "mām", meaning: "Me" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "यः", transliteration: "yaḥ", meaning: "who" },
            { word: "अव्यभिचारेण", transliteration: "avyabhicāreṇa", meaning: "unfailing/exclusive" },
            { word: "भक्तियोगेन", transliteration: "bhakti-yogena", meaning: "by the yoga of devotion" },
            { word: "सेवते", transliteration: "sevate", meaning: "serves/worships" },
            { word: "सः", transliteration: "saḥ", meaning: "he" },
            { word: "गुणान्", transliteration: "guṇān", meaning: "the gunas" },
            { word: "समतीत्य", transliteration: "samatītya", meaning: "completely transcending" },
            { word: "एतान्", transliteration: "etān", meaning: "these" },
            { word: "ब्रह्मभूयाय", transliteration: "brahma-bhūyāya", meaning: "for becoming Brahman" },
            { word: "कल्पते", transliteration: "kalpate", meaning: "is fit/qualified" }
          ],
          translation: "And he who serves Me with unfailing devotion through the yoga of devotion, he, transcending these gunas, is fit for becoming one with Brahman.",
          modernInterpretation: "After describing what a guna-transcended person LOOKS like, Krishna now answers Arjuna's third question — HOW do you actually transcend the gunas? And the answer is devastatingly simple: AVYABHICHARENA BHAKTI-YOGENA — through UNFAILING, EXCLUSIVE devotion to Krishna. Not wavering devotion. Not 'I will be spiritual on weekends' devotion. Not 'I will try multiple approaches and see which one works' devotion. AVYABHICHARA — unwavering, undivided, total.\n\nThis is the METHOD. After an entire chapter of complex philosophy about three gunas, their symptoms, their fruits, their destinations — the SOLUTION is breathtakingly simple. DEVOTE yourself to the Divine. Not partially. Not occasionally. COMPLETELY. And what happens then? BRAHMA-BHUYAYA KALPATE — you become QUALIFIED for Brahman-realization. You do not just transcend the gunas — you become FIT for merging with the Absolute Reality itself.\n\nIt is like studying for the most important exam of existence. The gunas are the syllabus — understanding them is necessary. But the PREPARATION method? Bhakti. Devotion. Love for God. Not because God has an ego that needs flattering. But because devotion is the only force STRONG enough to pull you out of the gravitational field of the three gunas. Sattva pulls you toward happiness. Rajas pulls you toward action. Tamas pulls you toward sleep. But BHAKTI pulls you toward the INFINITE — and the infinite is stronger than all three gunas combined."
        },
        {
          chapter: 14,
          sloka: 27,
          devanagari: "ब्रह्मणो हि प्रतिष्ठाहममृतस्याव्ययस्य च ।\nशाश्वतस्य च धर्मस्य सुखस्यैकान्तिकस्य च ॥२७॥",
          transliteration: "brahmaṇo hi pratiṣṭhāham amṛtasyāvyayasya ca |\nśāśvatasya ca dharmasya sukhasyaikāntikasya ca ||27||",
          words: [
            { word: "ब्रह्मणः", transliteration: "brahmaṇaḥ", meaning: "of Brahman" },
            { word: "हि", transliteration: "hi", meaning: "indeed" },
            { word: "प्रतिष्ठा", transliteration: "pratiṣṭhā", meaning: "the foundation/abode" },
            { word: "अहम्", transliteration: "aham", meaning: "I am" },
            { word: "अमृतस्य", transliteration: "amṛtasya", meaning: "of the immortal" },
            { word: "अव्ययस्य", transliteration: "avyayasya", meaning: "of the imperishable" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "शाश्वतस्य", transliteration: "śāśvatasya", meaning: "of the eternal" },
            { word: "धर्मस्य", transliteration: "dharmasya", meaning: "of dharma/righteousness" },
            { word: "सुखस्य", transliteration: "sukhasya", meaning: "of happiness" },
            { word: "ऐकान्तिकस्य", transliteration: "aikāntikasya", meaning: "absolute/ultimate" },
            { word: "च", transliteration: "ca", meaning: "and" }
          ],
          translation: "For I am the abode of Brahman — the immortal, the imperishable, the eternal dharma, and absolute bliss.",
          modernInterpretation: "The FINAL verse. The GRAND FINALE of Chapter 14. And Krishna ends with one of the most POWERFUL declarations in the entire Gita. He says, 'I am the PRATISHTHA — the foundation, the resting place, the ABODE — of Brahman.' Not 'I am part of Brahman.' Not 'I point toward Brahman.' I AM the foundation upon which the ENTIRE Absolute Reality rests. Brahman — the formless, infinite, ultimate reality — has its HOME in Krishna.\n\nAnd He does not stop there. He says He is the foundation of AMRITA (immortality), AVYAYA (the imperishable), SHASHVATA DHARMA (eternal righteousness), and AIKANTIKA SUKHA (absolute, unconditional bliss). Everything that every human being has ever WANTED — to never die, to never lose anything, to always be righteous, to always be happy — all of that rests in HIM.\n\nThis is the ultimate COMING HOME verse. The entire chapter started with the three gunas binding you — sattva with golden chains, rajas with fiery chains, tamas with iron chains. And it ends with Krishna saying, 'Come to ME, and you will find what is beyond ALL chains — immortality, imperishability, eternal dharma, and absolute bliss.' The gunas are the PROBLEM. Bhakti is the METHOD. Krishna is the DESTINATION. And when you arrive at the destination, you realize it was never about escaping the gunas at all — it was about FINDING the one in whom the gunas themselves find their ultimate rest. Chapter 14 complete. The three gunas explained, their prison revealed, and the escape route laid bare. All you need to do now is WALK it."
        },
]
