[
        {
          chapter: 17,
          sloka: 1,
          devanagari: "अर्जुन उवाच ।\nये शास्त्रविधिमुत्सृज्य यजन्ते श्रद्धयान्विताः ।\nतेषां निष्ठा तु का कृष्ण सत्त्वमाहो रजस्तमः ॥१॥",
          transliteration: "arjuna uvāca |\nye śāstra-vidhim utsṛjya yajante śraddhayānvitāḥ |\nteṣāṁ niṣṭhā tu kā kṛṣṇa sattvam āho rajas tamaḥ ||1||",
          words: [
            { word: "अर्जुन", transliteration: "arjuna", meaning: "Arjuna" },
            { word: "उवाच", transliteration: "uvāca", meaning: "said" },
            { word: "ये", transliteration: "ye", meaning: "those who" },
            { word: "शास्त्रविधिम्", transliteration: "śāstra-vidhim", meaning: "the injunctions of scripture" },
            { word: "उत्सृज्य", transliteration: "utsṛjya", meaning: "giving up/disregarding" },
            { word: "यजन्ते", transliteration: "yajante", meaning: "worship" },
            { word: "श्रद्धया", transliteration: "śraddhayā", meaning: "with faith" },
            { word: "अन्विताः", transliteration: "anvitāḥ", meaning: "endowed" },
            { word: "तेषाम्", transliteration: "teṣām", meaning: "their" },
            { word: "निष्ठा", transliteration: "niṣṭhā", meaning: "faith/position" },
            { word: "तु", transliteration: "tu", meaning: "but" },
            { word: "का", transliteration: "kā", meaning: "what" },
            { word: "कृष्ण", transliteration: "kṛṣṇa", meaning: "O Krishna" },
            { word: "सत्त्वम्", transliteration: "sattvam", meaning: "goodness" },
            { word: "आहो", transliteration: "āho", meaning: "or" },
            { word: "रजः", transliteration: "rajaḥ", meaning: "passion" },
            { word: "तमः", transliteration: "tamaḥ", meaning: "ignorance" }
          ],
          translation: "Arjuna said: Those who, setting aside the injunctions of scripture, perform worship endowed with faith — what is their position, O Krishna? Is it in goodness, passion, or ignorance?",
          modernInterpretation: "Welcome to Chapter 17 — SHRADDHATRAYA VIBHAGA YOGA — The Yoga of the Three Divisions of Faith. And Arjuna opens with an absolutely BRILLIANT question. He is basically asking: 'Krishna, what about people who DO have faith, who DO worship sincerely, but they are NOT following the scriptural rulebook? Where do THEY stand?'\n\nThis is SUCH a relevant question for our times. Think about it — how many people in your life are genuinely spiritual, genuinely devoted, but they are doing their OWN thing? They do not go to temples, they do not follow rituals, but they meditate in their own way, they pray in their own style, they have REAL faith. Are they sattvic? Rajasic? Tamasic? Where do they FIT?\n\nIt is like asking — if someone never went to IIT coaching but is a GENIUS at engineering, are they an engineer or not? If someone never went to culinary school but cooks INCREDIBLE food, are they a chef or not? Arjuna is essentially asking about the relationship between FORMAL structure and INNER conviction. Does the faith ITSELF matter, or does the METHOD of expressing it matter? And Krishna, as always, is about to give an answer that covers EVERY possible angle."
        },
        {
          chapter: 17,
          sloka: 2,
          devanagari: "श्रीभगवानुवाच ।\nत्रिविधा भवति श्रद्धा देहिनां सा स्वभावजा ।\nसात्त्विकी राजसी चैव तामसी चेति तां शृणु ॥२॥",
          transliteration: "śrī-bhagavān uvāca |\ntrividhā bhavati śraddhā dehināṁ sā svabhāva-jā |\nsāttvikī rājasī caiva tāmasī ceti tāṁ śṛṇu ||2||",
          words: [
            { word: "श्रीभगवान्", transliteration: "śrī-bhagavān", meaning: "the Supreme Lord" },
            { word: "उवाच", transliteration: "uvāca", meaning: "said" },
            { word: "त्रिविधा", transliteration: "tri-vidhā", meaning: "three kinds" },
            { word: "भवति", transliteration: "bhavati", meaning: "becomes/is" },
            { word: "श्रद्धा", transliteration: "śraddhā", meaning: "faith" },
            { word: "देहिनाम्", transliteration: "dehinām", meaning: "of the embodied" },
            { word: "सा", transliteration: "sā", meaning: "that" },
            { word: "स्वभावजा", transliteration: "svabhāva-jā", meaning: "born of one's own nature" },
            { word: "सात्त्विकी", transliteration: "sāttvikī", meaning: "sattvic (in goodness)" },
            { word: "राजसी", transliteration: "rājasī", meaning: "rajasic (in passion)" },
            { word: "तामसी", transliteration: "tāmasī", meaning: "tamasic (in ignorance)" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "इति", transliteration: "iti", meaning: "thus" },
            { word: "ताम्", transliteration: "tām", meaning: "that" },
            { word: "शृणु", transliteration: "śṛṇu", meaning: "hear" }
          ],
          translation: "The Supreme Lord said: The faith of embodied beings is of three kinds, born of their own nature — sattvic (goodness), rajasic (passion), and tamasic (ignorance). Hear about it.",
          modernInterpretation: "Krishna IMMEDIATELY sets up the framework. Faith is not ONE thing — it is THREE things. And here is the key phrase: 'svabhāva-jā' — born of one's OWN NATURE. Your faith is not random. It is a PRODUCT of your accumulated tendencies, your past actions, your mental conditioning. You do not CHOOSE your faith in a vacuum — your faith REFLECTS who you already are.\n\nThis is EXACTLY like your taste in music. Nobody sits down and logically decides, 'I shall now enjoy classical music.' Your taste EMERGES from your nature. Someone with a refined, calm disposition gravitates toward classical. Someone energetic and ambitious gravitates toward hip-hop or EDM. Someone who just wants to zone out gravitates toward whatever requires zero mental engagement. Your PREFERENCES reveal your NATURE.\n\nSo Krishna is saying — do not just look at WHETHER someone has faith. Look at WHAT KIND of faith they have. Two people can both go to a temple. One goes seeking inner peace. Another goes seeking a promotion. A third goes because his mother dragged him there and he is scrolling Instagram during the aarti. SAME action, THREE completely different faiths behind it. And THAT is what determines the result."
        },
        {
          chapter: 17,
          sloka: 3,
          devanagari: "सत्त्वानुरूपा सर्वस्य श्रद्धा भवति भारत ।\nश्रद्धामयोऽयं पुरुषो यो यच्छ्रद्धः स एव सः ॥३॥",
          transliteration: "sattvānurūpā sarvasya śraddhā bhavati bhārata |\nśraddhā-mayo'yaṁ puruṣo yo yac-chraddhaḥ sa eva saḥ ||3||",
          words: [
            { word: "सत्त्वानुरूपा", transliteration: "sattva-anurūpā", meaning: "according to one's nature/existence" },
            { word: "सर्वस्य", transliteration: "sarvasya", meaning: "of everyone" },
            { word: "श्रद्धा", transliteration: "śraddhā", meaning: "faith" },
            { word: "भवति", transliteration: "bhavati", meaning: "is" },
            { word: "भारत", transliteration: "bhārata", meaning: "O descendant of Bharata" },
            { word: "श्रद्धामयः", transliteration: "śraddhā-mayaḥ", meaning: "full of faith" },
            { word: "अयम्", transliteration: "ayam", meaning: "this" },
            { word: "पुरुषः", transliteration: "puruṣaḥ", meaning: "person" },
            { word: "यः", transliteration: "yaḥ", meaning: "who" },
            { word: "यत्", transliteration: "yat", meaning: "whatever" },
            { word: "श्रद्धः", transliteration: "śraddhaḥ", meaning: "faith" },
            { word: "सः", transliteration: "saḥ", meaning: "he" },
            { word: "एव", transliteration: "eva", meaning: "indeed" },
            { word: "सः", transliteration: "saḥ", meaning: "he (is that)" }
          ],
          translation: "The faith of each person conforms to their nature, O Bharata. A person is made of their faith — whatever their faith is, that indeed they are.",
          modernInterpretation: "THIS verse is one of the most PSYCHOLOGICALLY profound statements in the entire Gita. 'Yo yac-chraddhaḥ sa eva saḥ' — You ARE your faith. Not you HAVE faith. You ARE faith. What you believe in, what you put your trust in, what you commit to DEEPLY — that is not something you possess. That IS you.\n\nThink about this. Two people look at the same world. One sees OPPORTUNITY everywhere — that is their faith. The other sees CONSPIRACY everywhere — that is their faith. One investor looks at a falling market and sees a buying opportunity. Another sees doom. SAME data, completely different responses. Why? Because 'śraddhā-mayaḥ ayaṁ puruṣaḥ' — a person IS their faith.\n\nThis is basically what modern psychology calls CORE BELIEFS. Your deepest assumptions about reality — 'the world is safe' versus 'the world is dangerous,' 'people are basically good' versus 'everyone is selfish' — these are not just opinions. They SHAPE everything. Your career choices, your relationships, your health decisions, your reaction to stress. You are not a person who HOLDS beliefs. You are a WALKING, BREATHING expression of your beliefs. Change your faith, and you literally change who you ARE. That is why Krishna spends an entire chapter on this."
        },
        {
          chapter: 17,
          sloka: 4,
          devanagari: "यजन्ते सात्त्विका देवान्यक्षरक्षांसि राजसाः ।\nप्रेतान्भूतगणांश्चान्ये यजन्ते तामसा जनाः ॥४॥",
          transliteration: "yajante sāttvikā devān yakṣa-rakṣāṁsi rājasāḥ |\npretān bhūta-gaṇāṁś cānye yajante tāmasā janāḥ ||4||",
          words: [
            { word: "यजन्ते", transliteration: "yajante", meaning: "worship" },
            { word: "सात्त्विकाः", transliteration: "sāttvikāḥ", meaning: "those in goodness" },
            { word: "देवान्", transliteration: "devān", meaning: "the gods/devas" },
            { word: "यक्षरक्षांसि", transliteration: "yakṣa-rakṣāṁsi", meaning: "yakshas and rakshasas (demons)" },
            { word: "राजसाः", transliteration: "rājasāḥ", meaning: "those in passion" },
            { word: "प्रेतान्", transliteration: "pretān", meaning: "spirits of the dead" },
            { word: "भूतगणान्", transliteration: "bhūta-gaṇān", meaning: "ghosts and spirits" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "अन्ये", transliteration: "anye", meaning: "others" },
            { word: "यजन्ते", transliteration: "yajante", meaning: "worship" },
            { word: "तामसाः", transliteration: "tāmasāḥ", meaning: "those in ignorance" },
            { word: "जनाः", transliteration: "janāḥ", meaning: "people" }
          ],
          translation: "Those in goodness worship the gods; those in passion worship yakshas and rakshasas; and others — those in ignorance — worship ghosts and spirits of the dead.",
          modernInterpretation: "Now Krishna gets SPECIFIC. He is saying — show me what you worship and I will tell you what guna dominates you. Sattvic people worship DEVAS — forces of light, knowledge, nature, divinity. They are drawn to things that ELEVATE. Rajasic people worship YAKSHAS and RAKSHASAS — beings of power, wealth, and domination. They are not seeking peace — they are seeking CONTROL. Tamasic people worship GHOSTS and SPIRITS — they are drawn to the dark, the dead, the occult.\n\nNow translate this to modern life. What do people WORSHIP today? The sattvic person worships KNOWLEDGE — they read books, seek wisdom, practice meditation, admire great teachers. The rajasic person worships SUCCESS and POWER — they follow billionaires on Twitter, read every hustle-culture book, worship at the altar of productivity and achievement. Nothing wrong with ambition, but when it becomes your GOD, it is rajasic faith.\n\nAnd the tamasic person? They worship DESTRUCTION and NEGATIVITY. They are drawn to doom-scrolling, conspiracy theories, toxic gossip, destructive habits. They do not build anything — they tear things down and call it entertainment. Your social media feed IS your temple. What you follow, what you consume, what you give your ATTENTION to — that is your worship. And it tells you EXACTLY which guna is running the show."
        },
        {
          chapter: 17,
          sloka: 5,
          devanagari: "अशास्त्रविहितं घोरं तप्यन्ते ये तपो जनाः ।\nदम्भाहंकारसंयुक्ताः कामरागबलान्विताः ॥५॥",
          transliteration: "aśāstra-vihitaṁ ghoraṁ tapyante ye tapo janāḥ |\ndambhāhaṁkāra-saṁyuktāḥ kāma-rāga-balānvitāḥ ||5||",
          words: [
            { word: "अशास्त्रविहितम्", transliteration: "aśāstra-vihitam", meaning: "not ordained by scripture" },
            { word: "घोरम्", transliteration: "ghoram", meaning: "terrible/severe" },
            { word: "तप्यन्ते", transliteration: "tapyante", meaning: "undergo/practise" },
            { word: "ये", transliteration: "ye", meaning: "those who" },
            { word: "तपः", transliteration: "tapaḥ", meaning: "austerity" },
            { word: "जनाः", transliteration: "janāḥ", meaning: "people" },
            { word: "दम्भ", transliteration: "dambha", meaning: "hypocrisy" },
            { word: "अहंकार", transliteration: "ahaṁkāra", meaning: "ego" },
            { word: "संयुक्ताः", transliteration: "saṁyuktāḥ", meaning: "endowed with" },
            { word: "काम", transliteration: "kāma", meaning: "desire" },
            { word: "राग", transliteration: "rāga", meaning: "attachment" },
            { word: "बलान्विताः", transliteration: "balānvitāḥ", meaning: "impelled by force" }
          ],
          translation: "Those who practise terrible austerities not ordained by scripture, possessed by hypocrisy and egoism, driven by the force of desire and attachment —",
          modernInterpretation: "Verses 5 and 6 go together, and Krishna is about to drop a BOMB. He starts describing people who do EXTREME spiritual practices — but for all the WRONG reasons. They are not prescribed by any legitimate tradition. They are GHORA — terrible, severe, extreme. And notice the motivation: DAMBHA (hypocrisy), AHANKARA (ego), KAMA (desire), and RAGA (attachment).\n\nYou have DEFINITELY seen these people. The person who posts their 40-day juice fast on Instagram every single day. The guy who does extreme yoga poses not for spiritual growth but for the PHOTO. People who turn spirituality into a PERFORMANCE — 'Look how spiritual I am, look how much I can endure, look at MY devotion.' The austerity is real, but the motivation is 100% ego.\n\nThis is the spiritual equivalent of TOXIC hustle culture. Just like there are people who destroy their health working 18 hours a day not because they love the work but because they want to POST about the grind — there are people who destroy their bodies through extreme fasts, sleep deprivation, and harsh practices not because they seek God, but because they seek ATTENTION. The pain is real. The suffering is real. But the PURPOSE is completely inverted. They are torturing themselves for likes and validation, not for liberation."
        },
        {
          chapter: 17,
          sloka: 6,
          devanagari: "कर्शयन्तः शरीरस्थं भूतग्राममचेतसः ।\nमां चैवान्तःशरीरस्थं तान्विद्ध्यासुरनिश्चयान् ॥६॥",
          transliteration: "karśayantaḥ śarīra-sthaṁ bhūta-grāmam acetasaḥ |\nmāṁ caivāntaḥ-śarīra-sthaṁ tān viddhyāsura-niścayān ||6||",
          words: [
            { word: "कर्शयन्तः", transliteration: "karśayantaḥ", meaning: "tormenting/emaciated" },
            { word: "शरीरस्थम्", transliteration: "śarīra-stham", meaning: "situated in the body" },
            { word: "भूतग्रामम्", transliteration: "bhūta-grāmam", meaning: "the aggregate of elements" },
            { word: "अचेतसः", transliteration: "acetasaḥ", meaning: "senseless/without understanding" },
            { word: "माम्", transliteration: "mām", meaning: "Me" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "एव", transliteration: "eva", meaning: "also" },
            { word: "अन्तःशरीरस्थम्", transliteration: "antaḥ-śarīra-stham", meaning: "dwelling within the body" },
            { word: "तान्", transliteration: "tān", meaning: "them" },
            { word: "विद्धि", transliteration: "viddhi", meaning: "know" },
            { word: "आसुरनिश्चयान्", transliteration: "āsura-niścayān", meaning: "of demoniac resolve" }
          ],
          translation: "Senselessly torturing the elements of the body and also Me who dwells within — know them to be of demoniac resolve.",
          modernInterpretation: "HERE is the bomb. Krishna says — when you TORTURE your body through misguided austerities, you are not just hurting your physical elements. You are tormenting ME. Because 'antaḥ-śarīra-stham' — Krishna DWELLS within your body. The Paramatma, the Supreme Soul, is RIGHT THERE in your heart. So when you starve yourself to look spiritual, when you beat yourself up physically or mentally in the name of devotion, you are literally HURTING GOD.\n\nThis is REVOLUTIONARY. Most religions in the world have traditions of self-mortification — whipping yourself, extreme fasting, lying on beds of nails. Krishna calls this ASURIC — demoniac. Not divine. DEMONIAC. Because the body is a TEMPLE, and God lives IN it. You do not demolish a temple to prove your devotion to the deity inside it.\n\nThink of your body as a rented apartment where the LANDLORD also lives. If you trash the apartment — break the walls, flood the bathroom, set the kitchen on fire — you are not just damaging property. You are making your LANDLORD miserable. Krishna is that landlord. He says 'I am IN there with you. Stop destroying the house we BOTH live in.' This verse should be quoted every time someone promotes dangerous crash diets, extreme deprivation, or any form of self-harm disguised as spirituality. Your body is sacred because GOD is in it. Treat it accordingly."
        },
        {
          chapter: 17,
          sloka: 7,
          devanagari: "आहारस्त्वपि सर्वस्य त्रिविधो भवति प्रियः ।\nयज्ञस्तपस्तथा दानं तेषां भेदमिमं शृणु ॥७॥",
          transliteration: "āhāras tv api sarvasya tri-vidho bhavati priyaḥ |\nyajñas tapas tathā dānaṁ teṣāṁ bhedam imaṁ śṛṇu ||7||",
          words: [
            { word: "आहारः", transliteration: "āhāraḥ", meaning: "food" },
            { word: "तु", transliteration: "tu", meaning: "indeed" },
            { word: "अपि", transliteration: "api", meaning: "also" },
            { word: "सर्वस्य", transliteration: "sarvasya", meaning: "of everyone" },
            { word: "त्रिविधः", transliteration: "tri-vidhaḥ", meaning: "of three kinds" },
            { word: "भवति", transliteration: "bhavati", meaning: "is" },
            { word: "प्रियः", transliteration: "priyaḥ", meaning: "dear/preferred" },
            { word: "यज्ञः", transliteration: "yajñaḥ", meaning: "sacrifice" },
            { word: "तपः", transliteration: "tapaḥ", meaning: "austerity" },
            { word: "तथा", transliteration: "tathā", meaning: "also" },
            { word: "दानम्", transliteration: "dānam", meaning: "charity" },
            { word: "तेषाम्", transliteration: "teṣām", meaning: "of them" },
            { word: "भेदम्", transliteration: "bhedam", meaning: "difference" },
            { word: "इमम्", transliteration: "imam", meaning: "this" },
            { word: "शृणु", transliteration: "śṛṇu", meaning: "hear" }
          ],
          translation: "The food that is preferred by everyone is also of three kinds. So too are sacrifice, austerity, and charity. Hear now the distinction between them.",
          modernInterpretation: "Krishna now expands the THREE-GUNA framework into the most PRACTICAL domains of life. He is about to classify FOUR major areas of human activity — food, sacrifice, austerity, and charity — each into three categories. This is like a spiritual PERSONALITY TEST, and it covers everything from what you eat for breakfast to how you donate money.\n\nNotice the GENIUS of starting with food. Not meditation. Not prayer. FOOD. Because food is the most BASIC, most UNIVERSAL, most DAILY activity of every human being. You eat three times a day (some of us more, no judgment). And Krishna is saying — even THAT is not neutral. The food you choose, the food you PREFER, the food you naturally gravitate toward — it is a MIRROR of your inner nature.\n\nThis is Krishna being an INCREDIBLE teacher. He does not start with abstract philosophy. He starts with your PLATE. Because if you cannot understand the gunas in your dal and roti, how will you understand them in your meditation and worship? He is grounding cosmic truth in your kitchen. And honestly? This section of the Gita has influenced Indian dietary philosophy for THOUSANDS of years. Every time your grandmother told you to eat fresh food and avoid stale leftovers, she was channeling Chapter 17."
        },
        {
          chapter: 17,
          sloka: 8,
          devanagari: "आयुःसत्त्वबलारोग्यसुखप्रीतिविवर्धनाः ।\nरस्याः स्निग्धाः स्थिरा हृद्या आहाराः सात्त्विकप्रियाः ॥८॥",
          transliteration: "āyuḥ-sattva-balārogya-sukha-prīti-vivardhanāḥ |\nrasyāḥ snigdhāḥ sthirā hṛdyā āhārāḥ sāttvika-priyāḥ ||8||",
          words: [
            { word: "आयुः", transliteration: "āyuḥ", meaning: "life span" },
            { word: "सत्त्व", transliteration: "sattva", meaning: "vitality/purity" },
            { word: "बल", transliteration: "bala", meaning: "strength" },
            { word: "आरोग्य", transliteration: "ārogya", meaning: "health" },
            { word: "सुख", transliteration: "sukha", meaning: "happiness" },
            { word: "प्रीति", transliteration: "prīti", meaning: "satisfaction" },
            { word: "विवर्धनाः", transliteration: "vivardhanāḥ", meaning: "increasing" },
            { word: "रस्याः", transliteration: "rasyāḥ", meaning: "juicy/flavorful" },
            { word: "स्निग्धाः", transliteration: "snigdhāḥ", meaning: "oleaginous/nourishing" },
            { word: "स्थिराः", transliteration: "sthirāḥ", meaning: "substantial/lasting" },
            { word: "हृद्याः", transliteration: "hṛdyāḥ", meaning: "pleasing to the heart" },
            { word: "आहाराः", transliteration: "āhārāḥ", meaning: "foods" },
            { word: "सात्त्विकप्रियाः", transliteration: "sāttvika-priyāḥ", meaning: "dear to the sattvic" }
          ],
          translation: "Foods that promote longevity, vitality, strength, health, happiness, and satisfaction, which are juicy, nourishing, substantial, and pleasing to the heart — such foods are dear to those in goodness.",
          modernInterpretation: "LOOK at this description. Sattvic food increases AYUH (lifespan), SATTVA (purity), BALA (strength), AROGYA (health), SUKHA (happiness), and PRITI (satisfaction). And the qualities? RASYA (juicy, flavorful), SNIGDHA (nourishing, with healthy fats), STHIRA (substantial, sustaining), HRIDYA (pleasing to the heart). This is not boring health food. This is DELICIOUS, WHOLESOME, SATISFYING food.\n\nForget every fad diet you have ever heard of. Krishna literally described the PERFECT diet 5000 years ago. Fresh fruits, wholesome grains, ghee, milk, nuts, fresh vegetables — food that makes you feel ALIVE after eating it, not sluggish. Food that you enjoy WHILE eating AND feel good AFTER eating. That post-meal feeling of contentment without heaviness? THAT is sattvic food.\n\nThe modern equivalent is simple. After eating sattvic food, you feel ENERGIZED. After a good home-cooked meal of dal, rice, sabzi, and roti with a little ghee — you feel satisfied, nourished, and ready to work or think clearly. Compare this to how you feel after a massive pizza or deep-fried binge. Your body KNOWS the difference. Sattvic food does not need a nutritionist to validate it — your own BODY gives you the feedback. If it makes you feel clean, clear, strong, and happy — it is sattvic. Period."
        },
        {
          chapter: 17,
          sloka: 9,
          devanagari: "कट्वम्ललवणात्युष्णतीक्ष्णरूक्षविदाहिनः ।\nआहारा राजसस्येष्टा दुःखशोकामयप्रदाः ॥९॥",
          transliteration: "kaṭv-amla-lavaṇāty-uṣṇa-tīkṣṇa-rūkṣa-vidāhinaḥ |\nāhārā rājasasyeṣṭā duḥkha-śokāmaya-pradāḥ ||9||",
          words: [
            { word: "कटु", transliteration: "kaṭu", meaning: "bitter" },
            { word: "अम्ल", transliteration: "amla", meaning: "sour" },
            { word: "लवण", transliteration: "lavaṇa", meaning: "salty" },
            { word: "अत्युष्ण", transliteration: "ati-uṣṇa", meaning: "very hot" },
            { word: "तीक्ष्ण", transliteration: "tīkṣṇa", meaning: "pungent/sharp" },
            { word: "रूक्ष", transliteration: "rūkṣa", meaning: "dry" },
            { word: "विदाहिनः", transliteration: "vidāhinaḥ", meaning: "burning" },
            { word: "आहाराः", transliteration: "āhārāḥ", meaning: "foods" },
            { word: "राजसस्य", transliteration: "rājasasya", meaning: "of the rajasic person" },
            { word: "इष्टाः", transliteration: "iṣṭāḥ", meaning: "desired" },
            { word: "दुःख", transliteration: "duḥkha", meaning: "pain" },
            { word: "शोक", transliteration: "śoka", meaning: "grief" },
            { word: "आमय", transliteration: "āmaya", meaning: "disease" },
            { word: "प्रदाः", transliteration: "pradāḥ", meaning: "causing" }
          ],
          translation: "Foods that are bitter, sour, salty, excessively hot, pungent, dry, and burning are preferred by those in passion. They cause pain, grief, and disease.",
          modernInterpretation: "Rajasic food is the food of INTENSITY. It is not bad-tasting — in fact, it is often EXTREMELY tasty in the moment. But notice the pattern: bitter, sour, SALTY, excessively hot, pungent, dry, burning. This is the food that ASSAULTS your taste buds. It creates a RUSH of sensation followed by a CRASH.\n\nThink about it — the extra-spicy vindaloo that makes you sweat, the bag of chips so salty you cannot stop eating, the food so loaded with chili that you need three glasses of water. It is EXCITING while you eat it. But what comes after? 'Duḥkha-śoka-āmaya-pradāḥ' — it causes pain, grief, and DISEASE. Your stomach burns, you get acidity, you feel restless, you cannot sleep properly.\n\nThis is the junk food culture, the street food addiction, the 'I need FLAVOR at any cost' mentality. And look — there is nothing wrong with enjoying spicy food occasionally. But when your DAILY diet is defined by excess — excess salt, excess spice, excess oil, excess everything — that is rajasic eating. It mirrors the rajasic personality: always needing MORE stimulation, more intensity, more excitement. The person who needs five espressos a day, the one who puts extra chili on everything, the one whose meal is not complete without something fried and burning — rajasic faith expressing through rajasic food."
        },
        {
          chapter: 17,
          sloka: 10,
          devanagari: "यातयामं गतरसं पूति पर्युषितं च यत् ।\nउच्छिष्टमपि चामेध्यं भोजनं तामसप्रियम् ॥१०॥",
          transliteration: "yāta-yāmaṁ gata-rasaṁ pūti paryuṣitaṁ ca yat |\nucchiṣṭam api cāmedhyaṁ bhojanaṁ tāmasa-priyam ||10||",
          words: [
            { word: "यातयामम्", transliteration: "yāta-yāmam", meaning: "stale/cooked long ago" },
            { word: "गतरसम्", transliteration: "gata-rasam", meaning: "tasteless" },
            { word: "पूति", transliteration: "pūti", meaning: "putrid/foul-smelling" },
            { word: "पर्युषितम्", transliteration: "paryuṣitam", meaning: "leftover/decomposed" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "यत्", transliteration: "yat", meaning: "which" },
            { word: "उच्छिष्टम्", transliteration: "ucchiṣṭam", meaning: "remnants/leftover" },
            { word: "अपि", transliteration: "api", meaning: "also" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "अमेध्यम्", transliteration: "amedhyam", meaning: "impure/unfit for offering" },
            { word: "भोजनम्", transliteration: "bhojanam", meaning: "food" },
            { word: "तामसप्रियम्", transliteration: "tāmasa-priyam", meaning: "dear to the tamasic" }
          ],
          translation: "Food that is stale, tasteless, putrid, leftover, and impure is dear to those in the mode of ignorance.",
          modernInterpretation: "Tamasic food is the food of DECAY. Yata-yamam — cooked too long ago, sitting out for hours. Gata-rasam — all the nutrition and flavor GONE. Puti — literally SMELLING bad. Paryushitam — leftover and decomposed. Ucchishtam — already eaten from, someone else's plate. Amedhyam — unfit even to be offered to God.\n\nNow this does not mean every leftover is tamasic. Krishna is describing a PATTERN — people who consistently prefer food that is dead, processed beyond recognition, or essentially garbage. The modern equivalent? Think of the person who lives on instant noodles, week-old takeout containers, heavily processed packaged food with zero nutritional value, or food they KNOW has gone bad but eat anyway because they cannot be bothered to cook.\n\nTamasic food creates TAMAS in the mind — dullness, lethargy, confusion, depression. Have you ever noticed how after eating really bad food — stale, greasy, or processed — your MIND also goes dull? You cannot think clearly, you feel heavy and lazy, you just want to lie down and scroll your phone mindlessly. That is not coincidence. That is TAMAS feeding TAMAS. Your body and mind are a SYSTEM. Garbage in, garbage out. Feed the system dead food, and the system starts to feel dead. This is not just ancient wisdom — modern nutritional science confirms that ultra-processed foods are linked to depression, brain fog, and low energy. Krishna knew this five millennia before any clinical trial."
        },
        {
          chapter: 17,
          sloka: 11,
          devanagari: "अफलाकाङ्क्षिभिर्यज्ञो विधिदृष्टो य इज्यते ।\nयष्टव्यमेवेति मनः समाधाय स सात्त्विकः ॥११॥",
          transliteration: "aphalākāṅkṣibhir yajño vidhi-diṣṭo ya ijyate |\nyaṣṭavyam eveti manaḥ samādhāya sa sāttvikaḥ ||11||",
          words: [
            { word: "अफलाकाङ्क्षिभिः", transliteration: "aphala-ākāṅkṣibhiḥ", meaning: "by those who desire no fruit" },
            { word: "यज्ञः", transliteration: "yajñaḥ", meaning: "sacrifice" },
            { word: "विधिदिष्टः", transliteration: "vidhi-diṣṭaḥ", meaning: "according to scriptural injunction" },
            { word: "यः", transliteration: "yaḥ", meaning: "which" },
            { word: "इज्यते", transliteration: "ijyate", meaning: "is performed" },
            { word: "यष्टव्यम्", transliteration: "yaṣṭavyam", meaning: "must be performed" },
            { word: "एव", transliteration: "eva", meaning: "only" },
            { word: "इति", transliteration: "iti", meaning: "thus" },
            { word: "मनः", transliteration: "manaḥ", meaning: "mind" },
            { word: "समाधाय", transliteration: "samādhāya", meaning: "fixing" },
            { word: "सः", transliteration: "saḥ", meaning: "that" },
            { word: "सात्त्विकः", transliteration: "sāttvikaḥ", meaning: "sattvic (in goodness)" }
          ],
          translation: "That sacrifice which is performed according to scriptural injunction, by those who expect no reward, with the firm conviction that it is a duty — that is sattvic.",
          modernInterpretation: "Now we move from food to SACRIFICE, and the sattvic version is beautifully simple. Three conditions: it follows proper guidelines (vidhi-dishta), the doer expects NO personal reward (aphala-akankshi), and it is done with the mindset 'this MUST be done — it is my duty' (yashtavyam eva iti).\n\nThe sattvic sacrifice is like paying your taxes HONESTLY. Not because you are afraid of a raid. Not because you want a refund. But because you genuinely believe — 'I live in this country, I use its roads, its hospitals, its army protects me. Contributing is my DUTY.' That mentality — doing what is right BECAUSE it is right, with zero expectation of a personal cookie — THAT is sattvic sacrifice.\n\nIn your daily life, this is the person who donates to a cause without wanting their name on a plaque. The employee who stays late to help a colleague without expecting credit. The parent who sacrifices their sleep, their comfort, their personal time for their child, not because they are keeping a scorecard, but because 'this is what I am SUPPOSED to do.' The key word is SAMADHAAYA — with a mind that is SETTLED, RESOLVED. No internal conflict, no 'what's in it for me,' just clear-minded duty. THAT is the highest form of sacrifice."
        },
        {
          chapter: 17,
          sloka: 12,
          devanagari: "अभिसंधाय तु फलं दम्भार्थमपि चैव यत् ।\nइज्यते भरतश्रेष्ठ तं यज्ञं विद्धि राजसम् ॥१२॥",
          transliteration: "abhisandhāya tu phalaṁ dambhārtham api caiva yat |\nijyate bharata-śreṣṭha taṁ yajñaṁ viddhi rājasam ||12||",
          words: [
            { word: "अभिसन्धाय", transliteration: "abhisandhāya", meaning: "having in view" },
            { word: "तु", transliteration: "tu", meaning: "but" },
            { word: "फलम्", transliteration: "phalam", meaning: "the fruit/result" },
            { word: "दम्भार्थम्", transliteration: "dambha-artham", meaning: "for the sake of show" },
            { word: "अपि", transliteration: "api", meaning: "also" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "एव", transliteration: "eva", meaning: "certainly" },
            { word: "यत्", transliteration: "yat", meaning: "which" },
            { word: "इज्यते", transliteration: "ijyate", meaning: "is performed" },
            { word: "भरतश्रेष्ठ", transliteration: "bharata-śreṣṭha", meaning: "O best of Bharatas" },
            { word: "तम्", transliteration: "tam", meaning: "that" },
            { word: "यज्ञम्", transliteration: "yajñam", meaning: "sacrifice" },
            { word: "विद्धि", transliteration: "viddhi", meaning: "know" },
            { word: "राजसम्", transliteration: "rājasam", meaning: "rajasic (in passion)" }
          ],
          translation: "But that sacrifice which is performed with an eye on the result, or merely for show, O best of Bharatas — know that to be rajasic.",
          modernInterpretation: "The rajasic sacrifice has two VERY recognizable traits: PHALA (you are doing it for the result) and DAMBHA (you are doing it for show). Either one or BOTH. And honestly, this describes about 90% of what passes for 'service' and 'sacrifice' in modern life.\n\nThe businessman who donates ten lakhs to a charity — and makes sure there is a HUGE banner with his photo at the event. The person who volunteers at an NGO — but only on days when the photographer is present. The family that does a massive puja not out of devotion but because the neighbors did one last month and they need to one-up them. DAMBHA — performance spirituality.\n\nOr the OTHER flavor: purely transactional sacrifice. 'God, I will do a special puja IF you give me this promotion.' 'I will fast for 11 Mondays IF I get married this year.' 'I will donate to this temple IF my business deal goes through.' This is not devotion — this is a BUSINESS NEGOTIATION with God. You are treating the divine like a vending machine: insert ritual, receive blessing. And look, it is not the WORST thing in the world. Rajasic sacrifice is still sacrifice. You are still DOING something positive externally. But internally, the meter is running. And Krishna says — that meter LIMITS the result you get."
        },
        {
          chapter: 17,
          sloka: 13,
          devanagari: "विधिहीनमसृष्टान्नं मन्त्रहीनमदक्षिणम् ।\nश्रद्धाविरहितं यज्ञं तामसं परिचक्षते ॥१३॥",
          transliteration: "vidhi-hīnam asṛṣṭānnaṁ mantra-hīnam adakṣiṇam |\nśraddhā-virahitaṁ yajñaṁ tāmasaṁ paricakṣate ||13||",
          words: [
            { word: "विधिहीनम्", transliteration: "vidhi-hīnam", meaning: "without proper procedure" },
            { word: "असृष्टान्नम्", transliteration: "asṛṣṭa-annam", meaning: "without distribution of food" },
            { word: "मन्त्रहीनम्", transliteration: "mantra-hīnam", meaning: "without proper chanting" },
            { word: "अदक्षिणम्", transliteration: "adakṣiṇam", meaning: "without proper remuneration" },
            { word: "श्रद्धाविरहितम्", transliteration: "śraddhā-virahitam", meaning: "devoid of faith" },
            { word: "यज्ञम्", transliteration: "yajñam", meaning: "sacrifice" },
            { word: "तामसम्", transliteration: "tāmasam", meaning: "tamasic (in ignorance)" },
            { word: "परिचक्षते", transliteration: "paricakṣate", meaning: "they call/declare" }
          ],
          translation: "That sacrifice which is performed without regard for scriptural injunctions, without distribution of food, without proper hymns, without remuneration to the priests, and devoid of faith — is declared to be tamasic.",
          modernInterpretation: "The tamasic sacrifice is the EMPTY RITUAL. Five devastating deficiencies: no proper procedure (vidhi-hina), no sharing of food (asrishta-anna), no sacred mantras (mantra-hina), no proper dakshina or compensation (adakshina), and — the KILLER — no faith (shraddha-virahita).\n\nYou have been to these events. Someone is performing a puja, but nobody knows WHY they are doing it. The pandit is rushing through mantras nobody understands. No food is offered or shared — the most BASIC act of community and generosity is missing. The whole thing feels hollow, going through motions like a machine. Nobody's HEART is in it.\n\nThe modern equivalent is the company CSR event where everyone shows up because HR mandated it, nobody actually cares about the cause, the 'volunteers' spend more time taking selfies than working, and the moment it is over everyone goes back to exactly who they were before. Or the person who goes to temple mechanically every Tuesday because their parents told them to, stands there for ten minutes with their mind on their phone, puts a coin in the box, and leaves feeling nothing.\n\nThe KEY absence is SHRADDHA — faith. You can get the procedure wrong and still have a powerful sacrifice if your HEART is in it. But you can get every procedure PERFECT and still have a tamasic sacrifice if your heart is EMPTY. Faith is not optional seasoning — it is the MAIN INGREDIENT."
        },
        {
          chapter: 17,
          sloka: 14,
          devanagari: "देवद्विजगुरुप्राज्ञपूजनं शौचमार्जवम् ।\nब्रह्मचर्यमहिंसा च शारीरं तप उच्यते ॥१४॥",
          transliteration: "deva-dvija-guru-prājña-pūjanaṁ śaucam ārjavam |\nbrahmacaryam ahiṁsā ca śārīraṁ tapa ucyate ||14||",
          words: [
            { word: "देव", transliteration: "deva", meaning: "gods" },
            { word: "द्विज", transliteration: "dvija", meaning: "the twice-born/brahmins" },
            { word: "गुरु", transliteration: "guru", meaning: "teachers" },
            { word: "प्राज्ञ", transliteration: "prājña", meaning: "the wise" },
            { word: "पूजनम्", transliteration: "pūjanam", meaning: "worship/reverence" },
            { word: "शौचम्", transliteration: "śaucam", meaning: "cleanliness/purity" },
            { word: "आर्जवम्", transliteration: "ārjavam", meaning: "straightforwardness/honesty" },
            { word: "ब्रह्मचर्यम्", transliteration: "brahmacaryam", meaning: "celibacy/continence" },
            { word: "अहिंसा", transliteration: "ahiṁsā", meaning: "non-violence" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "शारीरम्", transliteration: "śārīram", meaning: "of the body" },
            { word: "तपः", transliteration: "tapaḥ", meaning: "austerity" },
            { word: "उच्यते", transliteration: "ucyate", meaning: "is called" }
          ],
          translation: "Worship of the gods, the twice-born, teachers, and the wise; purity, straightforwardness, celibacy, and non-violence — this is called the austerity of the body.",
          modernInterpretation: "NOW Krishna begins the section on TAPAS — austerity — and he categorizes it beautifully into three domains: body, speech, and mind. This verse covers SHARIRA TAPAS — austerity of the body. And look at the five components.\n\nFirst: WORSHIP — reverence for the divine, for learned teachers, for the wise. This is not just going to temple. This is about how you physically CONDUCT yourself in the presence of something greater. Standing up when your teacher enters. Bowing your head in a sacred space. Using your BODY to express respect and humility.\n\nSecond: SHAUCHAM — cleanliness. Keep your body clean, your surroundings clean, your environment pure. This is why your grandmother insisted you shower before entering the puja room. Physical cleanliness is not just hygiene — it is a form of DISCIPLINE.\n\nThird: ARJAVAM — straightforwardness. Your body language matches your intentions. No crooked posture to hide crooked intentions. You stand STRAIGHT because you ARE straight.\n\nFourth: BRAHMACHARYA — often translated as celibacy, but more broadly it means MASTERY over your senses. Not being a slave to physical cravings. It is the ability to say NO to your body when your body says 'I WANT.'\n\nFifth: AHIMSA — non-violence. Your body causes no harm. Your hands do not strike. Your feet do not trample. Your physical presence in the world is GENTLE.\n\nNotice — these are not extraordinary feats. No lying on ice blocks, no walking on coals. REAL austerity of the body is simple: be clean, be honest, be respectful, be disciplined, and do no harm. ANYONE can start this today."
        }
        ]