[
        {
          chapter: 17,
          sloka: 15,
          devanagari: "अनुद्वेगकरं वाक्यं सत्यं प्रियहितं च यत् ।\nस्वाध्यायाभ्यसनं चैव वाङ्मयं तप उच्यते ॥१५॥",
          transliteration: "anudvega-karaṁ vākyaṁ satyaṁ priya-hitaṁ ca yat |\nsvādhyāyābhyasanaṁ caiva vāṅ-mayaṁ tapa ucyate ||15||",
          words: [
            { word: "अनुद्वेगकरम्", transliteration: "anudvega-karam", meaning: "not causing agitation" },
            { word: "वाक्यम्", transliteration: "vākyam", meaning: "words/speech" },
            { word: "सत्यम्", transliteration: "satyam", meaning: "truthful" },
            { word: "प्रिय", transliteration: "priya", meaning: "pleasant" },
            { word: "हितम्", transliteration: "hitam", meaning: "beneficial" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "यत्", transliteration: "yat", meaning: "which" },
            { word: "स्वाध्याय", transliteration: "svādhyāya", meaning: "self-study/study of scriptures" },
            { word: "अभ्यसनम्", transliteration: "abhyasanam", meaning: "practice" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "एव", transliteration: "eva", meaning: "also" },
            { word: "वाङ्मयम्", transliteration: "vāṅ-mayam", meaning: "of speech" },
            { word: "तपः", transliteration: "tapaḥ", meaning: "austerity" },
            { word: "उच्यते", transliteration: "ucyate", meaning: "is called" }
          ],
          translation: "Speech that causes no agitation, that is truthful, pleasant, and beneficial, as well as the practice of self-study — this is called the austerity of speech.",
          modernInterpretation: "After the body, Krishna moves to VAK TAPAS — austerity of SPEECH. And this might be the most NEEDED teaching for our time. Look at the four qualities of disciplined speech: ANUDVEGA-KARAM (does not cause disturbance), SATYAM (truthful), PRIYA (pleasant), and HITAM (beneficial). And then a fifth: SVADHYAYA (self-study, regular recitation of sacred texts).\n\nNotice that truth ALONE is not enough. Your speech must be truthful AND pleasant AND beneficial. This is the GOLDEN TRIANGLE of communication. Because you can say something true that is unnecessarily cruel. You can say something pleasant that is a total lie. You can say something beneficial that is delivered so harshly nobody listens. Krishna wants ALL THREE at once.\n\nImagine your friend asks, 'How do I look in this outfit?' The tamasic response: say nothing, grunt, scroll your phone. The rajasic response: 'You look TERRIBLE, change immediately' — true maybe, but delivered like a hammer. The sattvic response: 'That color does not suit you as well as the blue one — try that!' TRUE, PLEASANT, and BENEFICIAL. All at once.\n\nAnd then SVADHYAYA — the regular practice of studying wisdom literature. This means your speech is not just reactive conversation. You ACTIVELY feed your mind with elevated ideas so that elevated words naturally come OUT. You are what you read, and you speak what you are. If your daily input is Twitter fights and gossip, guess what your OUTPUT will be? Austerity of speech starts with austerity of INPUT."
        },
        {
          chapter: 17,
          sloka: 16,
          devanagari: "मनःप्रसादः सौम्यत्वं मौनमात्मविनिग्रहः ।\nभावसंशुद्धिरित्येतत्तपो मानसमुच्यते ॥१६॥",
          transliteration: "manaḥ-prasādaḥ saumyatvaṁ maunam ātma-vinigrahaḥ |\nbhāva-saṁśuddhir ity etat tapo mānasam ucyate ||16||",
          words: [
            { word: "मनःप्रसादः", transliteration: "manaḥ-prasādaḥ", meaning: "serenity of mind" },
            { word: "सौम्यत्वम्", transliteration: "saumyatvam", meaning: "gentleness/good temper" },
            { word: "मौनम्", transliteration: "maunam", meaning: "silence" },
            { word: "आत्मविनिग्रहः", transliteration: "ātma-vinigrahaḥ", meaning: "self-control" },
            { word: "भावसंशुद्धिः", transliteration: "bhāva-saṁśuddhiḥ", meaning: "purity of thought/feeling" },
            { word: "इति", transliteration: "iti", meaning: "thus" },
            { word: "एतत्", transliteration: "etat", meaning: "this" },
            { word: "तपः", transliteration: "tapaḥ", meaning: "austerity" },
            { word: "मानसम्", transliteration: "mānasam", meaning: "of the mind" },
            { word: "उच्यते", transliteration: "ucyate", meaning: "is called" }
          ],
          translation: "Serenity of mind, gentleness, silence, self-control, and purity of thought — this is called the austerity of the mind.",
          modernInterpretation: "And now the DEEPEST level — MANASA TAPAS — austerity of the MIND. Body discipline is visible. Speech discipline is audible. But mind discipline? That is between you and your OWN consciousness. Nobody else can see it. Nobody can verify it. This is the REAL test.\n\nFive components: MANAH-PRASADA (mental serenity — a calm, cheerful, clear mind), SAUMYATVA (gentleness — not just in behavior but in your THINKING about others), MAUNAM (silence — not just of the mouth but of the mental chatter), ATMA-VINIGRAHA (self-control — mastery over your own thought patterns), and BHAVA-SAMSHUDDHI (purity of feeling — your INTENTIONS are clean, not just your actions).\n\nThis is the HARDEST tapas by far. You might control your body from hitting someone. You might control your tongue from insulting them. But can you control your MIND from hating them? That is where the real battle is. The person who smiles at you while mentally plotting against you has ZERO manas tapas. The person who genuinely WISHES you well — even when you have wronged them — THAT is mind austerity.\n\nBHAVA-SAMSHUDDHI is especially powerful. Purity of INTENT. Not just doing the right thing, but doing it for the right REASON. Not just donating money, but donating with genuine love. Not just forgiving someone, but forgiving without keeping a mental scorecard. The mind is the LAST frontier of spirituality. You can fool everyone else, but you cannot fool your own mind. And Krishna says — discipline THAT, and you have conquered the highest form of austerity."
        },
        {
          chapter: 17,
          sloka: 17,
          devanagari: "श्रद्धया परया तप्तं तपस्तत्त्रिविधं नरैः ।\nअफलाकाङ्क्षिभिर्युक्तैः सात्त्विकं परिचक्षते ॥१७॥",
          transliteration: "śraddhayā parayā taptaṁ tapas tat tri-vidhaṁ naraiḥ |\naphalākāṅkṣibhir yuktaiḥ sāttvikaṁ paricakṣate ||17||",
          words: [
            { word: "श्रद्धया", transliteration: "śraddhayā", meaning: "with faith" },
            { word: "परया", transliteration: "parayā", meaning: "supreme/highest" },
            { word: "तप्तम्", transliteration: "taptam", meaning: "practised" },
            { word: "तपः", transliteration: "tapaḥ", meaning: "austerity" },
            { word: "तत्", transliteration: "tat", meaning: "that" },
            { word: "त्रिविधम्", transliteration: "tri-vidham", meaning: "threefold" },
            { word: "नरैः", transliteration: "naraiḥ", meaning: "by persons" },
            { word: "अफलाकाङ्क्षिभिः", transliteration: "aphala-ākāṅkṣibhiḥ", meaning: "not desiring fruit" },
            { word: "युक्तैः", transliteration: "yuktaiḥ", meaning: "balanced/steadfast" },
            { word: "सात्त्विकम्", transliteration: "sāttvikam", meaning: "sattvic" },
            { word: "परिचक्षते", transliteration: "paricakṣate", meaning: "is declared" }
          ],
          translation: "This threefold austerity (of body, speech, and mind) practised with supreme faith by steadfast persons who desire no fruit — that is declared to be sattvic.",
          modernInterpretation: "Now Krishna CLASSIFIES the austerities themselves. Sattvic tapas has three characteristics: SHRADDHA PARAYA (supreme, unwavering faith), APHALA-AKANKSHI (zero desire for personal gain), and YUKTA (balanced, steady, equanimous approach).\n\nThis is the person who maintains their discipline not because they are chasing a reward, but because it is who they ARE. The person who eats healthy not because they want to look good on Instagram, but because they genuinely RESPECT their body. The person who speaks kindly not to win popularity, but because they cannot IMAGINE being harsh. The person who keeps their mind pure not to earn spiritual brownie points, but because a cluttered mind simply feels WRONG to them.\n\nThe word YUKTA here is crucial. It means balanced, steady, harmonized. Sattvic austerity is not EXTREME. It is not dramatic. It does not make you miserable. It is SUSTAINABLE because it comes from an inner alignment, not an external pressure. Think of the difference between someone who exercises because they love their body versus someone who exercises because they hate their body. SAME action, completely different energy. The first is sattvic — joyful, sustainable, life-affirming. The second burns out eventually because the motivation is NEGATIVE.\n\nSattvic austerity FEEDS you. It does not drain you. If your spiritual practice leaves you feeling depleted, resentful, or superior to others — check your motivation. True sattvic tapas makes you more peaceful, more humble, and more connected."
        },
        {
          chapter: 17,
          sloka: 18,
          devanagari: "सत्कारमानपूजार्थं तपो दम्भेन चैव यत् ।\nक्रियते तदिह प्रोक्तं राजसं चलमध्रुवम् ॥१८॥",
          transliteration: "satkāra-māna-pūjārthaṁ tapo dambhena caiva yat |\nkriyate tad iha proktaṁ rājasaṁ calam adhruvam ||18||",
          words: [
            { word: "सत्कार", transliteration: "satkāra", meaning: "hospitality/respect" },
            { word: "मान", transliteration: "māna", meaning: "honor" },
            { word: "पूजा", transliteration: "pūjā", meaning: "worship/adoration" },
            { word: "अर्थम्", transliteration: "artham", meaning: "for the sake of" },
            { word: "तपः", transliteration: "tapaḥ", meaning: "austerity" },
            { word: "दम्भेन", transliteration: "dambhena", meaning: "with hypocrisy/ostentation" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "एव", transliteration: "eva", meaning: "certainly" },
            { word: "यत्", transliteration: "yat", meaning: "which" },
            { word: "क्रियते", transliteration: "kriyate", meaning: "is done" },
            { word: "तत्", transliteration: "tat", meaning: "that" },
            { word: "इह", transliteration: "iha", meaning: "here" },
            { word: "प्रोक्तम्", transliteration: "proktam", meaning: "is said" },
            { word: "राजसम्", transliteration: "rājasam", meaning: "rajasic" },
            { word: "चलम्", transliteration: "calam", meaning: "unsteady" },
            { word: "अध्रुवम्", transliteration: "adhruvam", meaning: "temporary" }
          ],
          translation: "Austerity that is practised with hypocrisy, for the sake of gaining respect, honor, and adoration — that is said to be rajasic, unstable, and impermanent.",
          modernInterpretation: "Rajasic tapas is PERFORMANCE SPIRITUALITY in its purest form. The motivation? SATKARA (wanting respect), MANA (wanting honor), PUJA (wanting worship/adoration), and DAMBHA (hypocrisy and showmanship). And the result? CHALAM (unstable) and ADHRUVAM (temporary).\n\nThis is the person who does a 30-day meditation challenge — but ONLY because they want to post the completion certificate. The person who does yoga in expensive branded clothes at the trendiest studio, not for inner peace but for the AESTHETIC. The influencer who goes on a 'spiritual retreat' in Bali and comes back with 500 photos and zero transformation.\n\nKrishna nails the RESULT of rajasic tapas: it is UNSTABLE and TEMPORARY. Why? Because the motivation is external. When the likes stop coming, the practice stops. When nobody is watching, the discipline evaporates. When the admiration fades, the austerity crumbles. It has no ROOT — it is held up entirely by the scaffolding of social approval.\n\nCompare this to the sattvic practitioner who meditates at 5 AM regardless of whether anyone knows. Whose practice does not change whether they have 10 followers or 10 million. THAT practice is stable because it is ROOTED in something deeper than other people's opinions. Rajasic tapas is like a plant in a pot on a moving truck — it looks alive but it has no ground. One bump and it falls over."
        },
        {
          chapter: 17,
          sloka: 19,
          devanagari: "मूढग्राहेणात्मनो यत्पीडया क्रियते तपः ।\nपरस्योत्सादनार्थं वा तत्तामसमुदाहृतम् ॥१९॥",
          transliteration: "mūḍha-grāheṇātmano yat pīḍayā kriyate tapaḥ |\nparasyotsādanārthaṁ vā tat tāmasam udāhṛtam ||19||",
          words: [
            { word: "मूढग्राहेण", transliteration: "mūḍha-grāheṇa", meaning: "with foolish stubbornness" },
            { word: "आत्मनः", transliteration: "ātmanaḥ", meaning: "of oneself" },
            { word: "यत्", transliteration: "yat", meaning: "which" },
            { word: "पीडया", transliteration: "pīḍayā", meaning: "by torture/pain" },
            { word: "क्रियते", transliteration: "kriyate", meaning: "is done" },
            { word: "तपः", transliteration: "tapaḥ", meaning: "austerity" },
            { word: "परस्य", transliteration: "parasya", meaning: "of others" },
            { word: "उत्सादनार्थम्", transliteration: "utsādana-artham", meaning: "for the purpose of destroying" },
            { word: "वा", transliteration: "vā", meaning: "or" },
            { word: "तत्", transliteration: "tat", meaning: "that" },
            { word: "तामसम्", transliteration: "tāmasam", meaning: "tamasic" },
            { word: "उदाहृतम्", transliteration: "udāhṛtam", meaning: "is declared" }
          ],
          translation: "Austerity that is practised with foolish stubbornness, through self-torture, or for the purpose of destroying others — that is declared to be tamasic.",
          modernInterpretation: "Tamasic tapas is the DARKEST form of austerity. Two motivations: MUDHA-GRAHENA ATMANAH PIDAYA — foolishly and stubbornly tormenting YOURSELF. Or PARASYA UTSADANA-ARTHAM — destroying OTHERS. Either self-harm or other-harm, both dressed up as 'spiritual practice.'\n\nThe first category: foolish self-torture. The person who fasts until they collapse, not for any genuine spiritual reason, but because they have a DISTORTED relationship with their own body. The person who sleeps on the floor and denies themselves every comfort, not out of detachment, but out of SELF-PUNISHMENT. This is spirituality hijacked by self-hatred. It looks like devotion, but it is actually violence turned INWARD.\n\nThe second category is even more disturbing: austerity performed to HARM others. This is the person who performs intense rituals and practices specifically to curse someone, to bring someone down, to gain power OVER another person. In ancient times, this was literal black magic. In modern times? It is the person who weaponizes their spirituality — 'I am more disciplined than you, I am more pure than you, I am BETTER than you' — using their practice as a sword to cut others down.\n\nKrishna is giving a CRITICAL warning: austerity without wisdom is DANGEROUS. Pain is not automatically holy. Suffering is not automatically spiritual. If your practice hurts you foolishly or hurts others intentionally — no matter how 'religious' it looks on the outside — it is TAMASIC. Full stop."
        },
        {
          chapter: 17,
          sloka: 20,
          devanagari: "दातव्यमिति यद्दानं दीयतेऽनुपकारिणे ।\nदेशे काले च पात्रे च तद्दानं सात्त्विकं स्मृतम् ॥२०॥",
          transliteration: "dātavyam iti yad dānaṁ dīyate'nupakāriṇe |\ndeśe kāle ca pātre ca tad dānaṁ sāttvikaṁ smṛtam ||20||",
          words: [
            { word: "दातव्यम्", transliteration: "dātavyam", meaning: "to be given" },
            { word: "इति", transliteration: "iti", meaning: "thus" },
            { word: "यत्", transliteration: "yat", meaning: "which" },
            { word: "दानम्", transliteration: "dānam", meaning: "charity" },
            { word: "दीयते", transliteration: "dīyate", meaning: "is given" },
            { word: "अनुपकारिणे", transliteration: "anupakāriṇe", meaning: "to one who cannot reciprocate" },
            { word: "देशे", transliteration: "deśe", meaning: "in the right place" },
            { word: "काले", transliteration: "kāle", meaning: "at the right time" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "पात्रे", transliteration: "pātre", meaning: "to a worthy person" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "तत्", transliteration: "tat", meaning: "that" },
            { word: "दानम्", transliteration: "dānam", meaning: "charity" },
            { word: "सात्त्विकम्", transliteration: "sāttvikam", meaning: "sattvic" },
            { word: "स्मृतम्", transliteration: "smṛtam", meaning: "is considered" }
          ],
          translation: "That charity which is given as a matter of duty, to one who cannot reciprocate, at the proper place and time, and to a worthy person — that is considered sattvic.",
          modernInterpretation: "Now Krishna moves to DANA — charity — and the sattvic version is a MASTERCLASS in generosity. Four conditions: DATAVYAM ITI (given as duty — 'this MUST be given'), ANUPAKARINE (to someone who CANNOT repay you), DESHE KALE (at the right place and right time), and PATRE (to a worthy recipient).\n\nThe most powerful word here is ANUPAKARINE — to someone who CANNOT reciprocate. This is the PUREST test of charity. When you give to someone who can never return the favor, there is ZERO possibility of selfish gain. You are not networking. You are not investing. You are not building a relationship for future benefit. You are simply GIVING because it needs to be given.\n\nThe modern sattvic donor does not give to the alumnus who will name a building after them. They give to the anonymous student who needs tuition fees and will never know the donor's name. They do not donate to the hospital that will put their photo in the lobby. They donate to the village clinic that has no lobby.\n\nDESHA and KALA — right place and right time — are also critical. Giving a winter coat in July is wasteful. Donating books to a village that needs food first is misplaced. Sattvic charity requires INTELLIGENCE and AWARENESS. It is not just about feeling good while giving. It is about ensuring the giving actually HELPS. And PATRA — the right recipient — means your charity should go where it will be USED well, not wasted or misused.\n\nSattvic charity is the convergence of generosity and WISDOM. Heart AND brain, working together."
        },
        {
          chapter: 17,
          sloka: 21,
          devanagari: "यत्तु प्रत्युपकारार्थं फलमुद्दिश्य वा पुनः ।\nदीयते च परिक्लिष्टं तद्दानं राजसं स्मृतम् ॥२१॥",
          transliteration: "yat tu pratyupakārārthaṁ phalam uddiśya vā punaḥ |\ndīyate ca parikliṣṭaṁ tad dānaṁ rājasaṁ smṛtam ||21||",
          words: [
            { word: "यत्", transliteration: "yat", meaning: "which" },
            { word: "तु", transliteration: "tu", meaning: "but" },
            { word: "प्रत्युपकारार्थम्", transliteration: "pratyupakāra-artham", meaning: "for the sake of getting something in return" },
            { word: "फलम्", transliteration: "phalam", meaning: "fruit/result" },
            { word: "उद्दिश्य", transliteration: "uddiśya", meaning: "with the aim of" },
            { word: "वा", transliteration: "vā", meaning: "or" },
            { word: "पुनः", transliteration: "punaḥ", meaning: "again" },
            { word: "दीयते", transliteration: "dīyate", meaning: "is given" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "परिक्लिष्टम्", transliteration: "parikliṣṭam", meaning: "reluctantly/grudgingly" },
            { word: "तत्", transliteration: "tat", meaning: "that" },
            { word: "दानम्", transliteration: "dānam", meaning: "charity" },
            { word: "राजसम्", transliteration: "rājasam", meaning: "rajasic" },
            { word: "स्मृतम्", transliteration: "smṛtam", meaning: "is considered" }
          ],
          translation: "But that charity which is given with the aim of getting something in return, or with expectation of fruit, or given reluctantly — that is considered rajasic.",
          modernInterpretation: "Rajasic charity has THREE telltale signs: PRATYUPAKARA-ARTHAM (you expect something back), PHALAM UDDISHYA (you are eyeing a specific result), or PARIKLISHTAM (you give GRUDGINGLY, with reluctance and inner resistance).\n\nThis is the most COMMON form of giving in the world. The corporate donation that is really a TAX STRATEGY. The wedding gift where you are mentally calculating — 'They gave us 11,000 at our wedding, so we will give them 11,000 back.' The charity that comes with strings: 'I helped you, so now you OWE me.' This is not giving — this is INVESTING with a spiritual label.\n\nAnd then there is PARIKLISHTAM — the grudging gift. You give because social pressure FORCES you to, but your heart is screaming, 'I do not WANT to give this.' The donation box comes around at the office event and you put money in because everyone is watching, but inside you are resenting every rupee. The WhatsApp message from a friend raising funds — you contribute not out of generosity but because you will look BAD if you do not.\n\nHere is the thing — rajasic charity still HELPS the recipient. The student who gets the scholarship does not care about the donor's motivation. The hospital gets built regardless of why the money was given. So rajasic giving is not EVIL. It is just LIMITED. The external benefit happens, but the INTERNAL transformation that true giving is supposed to bring? That does not happen. You gave money, but you did not give your HEART. And it is the heart-giving that changes the giver."
        },
        {
          chapter: 17,
          sloka: 22,
          devanagari: "अदेशकाले यद्दानमपात्रेभ्यश्च दीयते ।\nअसत्कृतमवज्ञातं तत्तामसमुदाहृतम् ॥२२॥",
          transliteration: "adeśa-kāle yad dānam apātrebhyaś ca dīyate |\nasat-kṛtam avajñātaṁ tat tāmasam udāhṛtam ||22||",
          words: [
            { word: "अदेशकाले", transliteration: "adeśa-kāle", meaning: "at the wrong place and time" },
            { word: "यत्", transliteration: "yat", meaning: "which" },
            { word: "दानम्", transliteration: "dānam", meaning: "charity" },
            { word: "अपात्रेभ्यः", transliteration: "apātrebhyaḥ", meaning: "to unworthy recipients" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "दीयते", transliteration: "dīyate", meaning: "is given" },
            { word: "असत्कृतम्", transliteration: "asat-kṛtam", meaning: "without respect" },
            { word: "अवज्ञातम्", transliteration: "avajñātam", meaning: "with contempt" },
            { word: "तत्", transliteration: "tat", meaning: "that" },
            { word: "तामसम्", transliteration: "tāmasam", meaning: "tamasic" },
            { word: "उदाहृतम्", transliteration: "udāhṛtam", meaning: "is declared" }
          ],
          translation: "That charity which is given at the wrong place and time, to unworthy recipients, without respect or with contempt — that is declared to be tamasic.",
          modernInterpretation: "Tamasic charity is giving that actively DEGRADES the act of giving. Four markers: ADESHA-KALE (wrong place and time), APATREBHYAH (to unworthy recipients — those who will misuse it), ASAT-KRITA (without respect — you throw the money rather than offer it), and AVAJNATA (with contempt — you look DOWN on the person you are giving to).\n\nThe person who throws coins at a beggar with DISGUST on their face. The person who donates old, torn clothes and feels SUPERIOR for doing so. The person who gives money to someone they KNOW will use it for destructive purposes — funding someone's addiction, enabling someone's harmful behavior, supporting a cause that actually HURTS people.\n\nAVAJNATAM — with contempt — is the most damaging aspect. When you give while making the recipient feel SMALL, you have not really given at all. You have TAKEN — you have taken their dignity. The person who says, 'Here, take this, you NEED it more than me' with a condescending tone — that is not charity. That is a power move disguised as generosity.\n\nTrue charity ELEVATES both the giver AND the receiver. Tamasic charity degrades BOTH. The giver becomes more arrogant, and the receiver feels humiliated. It would have been better not to give at all. This is why HOW you give matters as much as WHAT you give. A single rupee given with love is worth more than a crore given with contempt. The Gita is clear — the ENERGY behind the act determines the act's true nature."
        },
        {
          chapter: 17,
          sloka: 23,
          devanagari: "ॐ तत्सदिति निर्देशो ब्रह्मणस्त्रिविधः स्मृतः ।\nब्राह्मणास्तेन वेदाश्च यज्ञाश्च विहिताः पुरा ॥२३॥",
          transliteration: "oṁ tat sad iti nirdeśo brahmaṇas tri-vidhaḥ smṛtaḥ |\nbrāhmaṇās tena vedāś ca yajñāś ca vihitāḥ purā ||23||",
          words: [
            { word: "ॐ", transliteration: "oṁ", meaning: "Om" },
            { word: "तत्", transliteration: "tat", meaning: "That" },
            { word: "सत्", transliteration: "sat", meaning: "Truth/Reality" },
            { word: "इति", transliteration: "iti", meaning: "thus" },
            { word: "निर्देशः", transliteration: "nirdeśaḥ", meaning: "designation/indication" },
            { word: "ब्रह्मणः", transliteration: "brahmaṇaḥ", meaning: "of Brahman" },
            { word: "त्रिविधः", transliteration: "tri-vidhaḥ", meaning: "threefold" },
            { word: "स्मृतः", transliteration: "smṛtaḥ", meaning: "is remembered/known" },
            { word: "ब्राह्मणाः", transliteration: "brāhmaṇāḥ", meaning: "the brahmins" },
            { word: "तेन", transliteration: "tena", meaning: "by that" },
            { word: "वेदाः", transliteration: "vedāḥ", meaning: "the Vedas" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "यज्ञाः", transliteration: "yajñāḥ", meaning: "sacrifices" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "विहिताः", transliteration: "vihitāḥ", meaning: "ordained/created" },
            { word: "पुरा", transliteration: "purā", meaning: "in the beginning" }
          ],
          translation: "Om Tat Sat — this has been declared as the threefold designation of Brahman. By that were the brahmins, the Vedas, and the sacrifices ordained in the beginning.",
          modernInterpretation: "We have now arrived at the CROWN of Chapter 17. OM TAT SAT — three words that contain the ENTIRE reality of Brahman. This is not just a mantra. This is the COSMIC SIGNATURE of the Absolute.\n\nOM — the primordial sound, the vibration from which all existence emerged. Every religion, every culture, every tradition has some version of this sacred sound. It is the HUMMING of the universe itself.\n\nTAT — 'That.' The Supreme Reality that cannot be named, cannot be contained, cannot be defined. It is so VAST that the best word for it is simply 'THAT.' Like pointing at the sky and saying 'that' — because no specific word can capture it.\n\nSAT — Truth, Reality, Existence itself. That which IS. Not that which appears, not that which changes, but that which ETERNALLY exists.\n\nKrishna says these three words CREATED the framework of spiritual life — the brahmins (seekers of truth), the Vedas (repositories of knowledge), and the yajnas (sacred practices). Everything in the spiritual tradition traces back to Om Tat Sat.\n\nThink of it as the spiritual equivalent of the ROOT DIRECTORY. In a computer, everything branches from the root folder. All files, all programs, all data trace back to ONE origin. Om Tat Sat is the root directory of all existence. Every mantra is a subset of Om. Every truth is an echo of Tat. Every reality is a fragment of Sat. And Krishna is handing Arjuna — and us — the ACCESS CODE to the entire system."
        },
        {
          chapter: 17,
          sloka: 24,
          devanagari: "तस्मादोमित्युदाहृत्य यज्ञदानतपःक्रियाः ।\nप्रवर्तन्ते विधानोक्ताः सततं ब्रह्मवादिनाम् ॥२४॥",
          transliteration: "tasmād om ity udāhṛtya yajña-dāna-tapaḥ-kriyāḥ |\npravartante vidhānoktāḥ satataṁ brahma-vādinām ||24||",
          words: [
            { word: "तस्मात्", transliteration: "tasmāt", meaning: "therefore" },
            { word: "ॐ", transliteration: "om", meaning: "Om" },
            { word: "इति", transliteration: "iti", meaning: "thus" },
            { word: "उदाहृत्य", transliteration: "udāhṛtya", meaning: "uttering" },
            { word: "यज्ञ", transliteration: "yajña", meaning: "sacrifice" },
            { word: "दान", transliteration: "dāna", meaning: "charity" },
            { word: "तपः", transliteration: "tapaḥ", meaning: "austerity" },
            { word: "क्रियाः", transliteration: "kriyāḥ", meaning: "acts" },
            { word: "प्रवर्तन्ते", transliteration: "pravartante", meaning: "begin/commence" },
            { word: "विधानोक्ताः", transliteration: "vidhāna-uktāḥ", meaning: "as prescribed by scriptural regulations" },
            { word: "सततम्", transliteration: "satatam", meaning: "always" },
            { word: "ब्रह्मवादिनाम्", transliteration: "brahma-vādinām", meaning: "of the knowers of Brahman" }
          ],
          translation: "Therefore, acts of sacrifice, charity, and austerity as prescribed by the scriptures are always commenced by the knowers of Brahman with the utterance of Om.",
          modernInterpretation: "Krishna now explains the PRACTICAL application of Om. Every sacred act — every yajna, every act of charity, every austerity — begins with OM. It is the spiritual ON switch. Before you donate, say Om. Before you perform a ritual, say Om. Before you begin your discipline, say Om.\n\nWhy? Because Om CONNECTS your individual act to the COSMIC purpose. Without Om, your sacrifice is just you performing a ritual. WITH Om, your sacrifice is plugged into the universal power grid. It is like the difference between a solar panel lying on the ground and a solar panel CONNECTED to the grid. The connection is what makes the energy FLOW.\n\nFor the Brahma-vadins — the knowers and seekers of Brahman — Om is not just a formality. It is a REMINDER. Every time they say Om before an action, they are telling themselves: 'This action is not about ME. This action is about the SUPREME.' It resets the intention. It cleanses the ego. It transforms a mundane act into a sacred one.\n\nIn modern life, think of Om as a MINDFULNESS BELL. Before you eat, pause and say Om — suddenly you are not just shoving food in your mouth. You are offering food to the divine fire within. Before you start work, pause and say Om — suddenly you are not just grinding for a paycheck. You are offering your skills to something greater. One syllable. Total transformation of intent. That is the POWER of Om."
        },
        {
          chapter: 17,
          sloka: 25,
          devanagari: "तदित्यनभिसन्धाय फलं यज्ञतपःक्रियाः ।\nदानक्रियाश्च विविधाः क्रियन्ते मोक्षकाङ्क्षिभिः ॥२५॥",
          transliteration: "tad ity anabhisandhāya phalaṁ yajña-tapaḥ-kriyāḥ |\ndāna-kriyāś ca vividhāḥ kriyante mokṣa-kāṅkṣibhiḥ ||25||",
          words: [
            { word: "तत्", transliteration: "tat", meaning: "That" },
            { word: "इति", transliteration: "iti", meaning: "thus" },
            { word: "अनभिसन्धाय", transliteration: "anabhisandhāya", meaning: "without aiming at" },
            { word: "फलम्", transliteration: "phalam", meaning: "fruit/result" },
            { word: "यज्ञ", transliteration: "yajña", meaning: "sacrifice" },
            { word: "तपः", transliteration: "tapaḥ", meaning: "austerity" },
            { word: "क्रियाः", transliteration: "kriyāḥ", meaning: "acts" },
            { word: "दानक्रियाः", transliteration: "dāna-kriyāḥ", meaning: "acts of charity" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "विविधाः", transliteration: "vividhāḥ", meaning: "various" },
            { word: "क्रियन्ते", transliteration: "kriyante", meaning: "are performed" },
            { word: "मोक्षकाङ्क्षिभिः", transliteration: "mokṣa-kāṅkṣibhiḥ", meaning: "by those who desire liberation" }
          ],
          translation: "With the utterance of 'Tat' and without aiming at any fruit, various acts of sacrifice, austerity, and charity are performed by those who desire liberation.",
          modernInterpretation: "Now comes TAT — 'That.' While Om is the SOUND of the Absolute, Tat is the POINTER toward it. When you say 'Tat' before an action, you are declaring: 'This is not MINE. This belongs to THAT — to the Supreme, to the Infinite, to something far beyond my little personal agenda.'\n\nANABHISANDHAYA PHALAM — without aiming at any fruit. This is the MOKSHA-SEEKERS' approach. People who want liberation do not perform sacrifices for heaven. They do not do austerity for superpowers. They do not give charity for tax benefits. They do EVERYTHING as an offering to TAT — to that nameless, formless, infinite Reality.\n\nIt is like the difference between a river that flows into a DAM (where the water is captured and used for a purpose) versus a river that flows into the OCEAN (where it merges and loses its separate identity). Rajasic action flows into the dam of personal benefit. Sattvic action, marked by 'Tat,' flows into the ocean of the Absolute.\n\nThe word TAT is also beautifully humble. You are not even NAMING God. You are not claiming to know what the Ultimate Reality is. You are just saying 'THAT' — pointing in the direction of something you know exists but cannot fully grasp. It is the spirituality of AWE rather than the spirituality of certainty. And there is something deeply HONEST about that. The greatest seekers are not those who claim to have all the answers. They are the ones who point toward the mystery and say, simply, 'THAT.'"
        },
        {
          chapter: 17,
          sloka: 26,
          devanagari: "सद्भावे साधुभावे च सदित्येतत्प्रयुज्यते ।\nप्रशस्ते कर्मणि तथा सच्छब्दः पार्थ युज्यते ॥२६॥",
          transliteration: "sad-bhāve sādhu-bhāve ca sad ity etat prayujyate |\npraśaste karmaṇi tathā sac-chabdaḥ pārtha yujyate ||26||",
          words: [
            { word: "सद्भावे", transliteration: "sat-bhāve", meaning: "in the sense of reality/existence" },
            { word: "साधुभावे", transliteration: "sādhu-bhāve", meaning: "in the sense of goodness" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "सत्", transliteration: "sat", meaning: "Sat (truth/reality)" },
            { word: "इति", transliteration: "iti", meaning: "thus" },
            { word: "एतत्", transliteration: "etat", meaning: "this" },
            { word: "प्रयुज्यते", transliteration: "prayujyate", meaning: "is used" },
            { word: "प्रशस्ते", transliteration: "praśaste", meaning: "auspicious/praiseworthy" },
            { word: "कर्मणि", transliteration: "karmaṇi", meaning: "in action" },
            { word: "तथा", transliteration: "tathā", meaning: "also" },
            { word: "सच्छब्दः", transliteration: "sat-śabdaḥ", meaning: "the word Sat" },
            { word: "पार्थ", transliteration: "pārtha", meaning: "O son of Pritha (Arjuna)" },
            { word: "युज्यते", transliteration: "yujyate", meaning: "is used" }
          ],
          translation: "The word 'Sat' is used in the sense of reality and goodness. Likewise, O Partha, the word 'Sat' is used for auspicious action.",
          modernInterpretation: "Now Krishna unpacks SAT — the third and final component of the cosmic triad. SAT means TRUTH, REALITY, EXISTENCE, GOODNESS. It is used in two senses: SAD-BHAVE (the nature of reality — that which truly EXISTS) and SADHU-BHAVE (the nature of goodness — that which is genuinely VIRTUOUS). And it is applied to PRASHASTE KARMANI — praiseworthy, auspicious actions.\n\nSAT is the QUALITY CHECK of the spiritual life. When you say something is 'Sat,' you are declaring it to be REAL — not fake, not hollow, not pretend. It is the opposite of ASAT (unreal, false). In a world full of illusions, performances, and pretenses, SAT cuts through everything and asks: 'But is it TRUE? Is it REAL? Is it GOOD?'\n\nIn everyday Hindi, we still use SAT constantly. SATYA (truth), SATSANG (company of truth), SATVIK (pure), SANT (saint — one who embodies Sat). The word has permeated Indian culture so deeply that even people who have never read the Gita live by its echo.\n\nWhen Krishna says SAT is used for praiseworthy action, he is giving us a FILTER for all our deeds. Before any important action, ask: Is this SAT? Is it real, true, and good? If yes, proceed. If not, reconsider. It is the simplest ethical framework ever created — one syllable, three letters, infinite wisdom."
        },
        {
          chapter: 17,
          sloka: 27,
          devanagari: "यज्ञे तपसि दाने च स्थितिः सदिति चोच्यते ।\nकर्म चैव तदर्थीयं सदित्येवाभिधीयते ॥२७॥",
          transliteration: "yajñe tapasi dāne ca sthitiḥ sad iti cocyate |\nkarma caiva tad-arthīyaṁ sad ity evābhidhīyate ||27||",
          words: [
            { word: "यज्ञे", transliteration: "yajñe", meaning: "in sacrifice" },
            { word: "तपसि", transliteration: "tapasi", meaning: "in austerity" },
            { word: "दाने", transliteration: "dāne", meaning: "in charity" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "स्थितिः", transliteration: "sthitiḥ", meaning: "steadfastness" },
            { word: "सत्", transliteration: "sat", meaning: "Sat (truth)" },
            { word: "इति", transliteration: "iti", meaning: "thus" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "उच्यते", transliteration: "ucyate", meaning: "is called" },
            { word: "कर्म", transliteration: "karma", meaning: "action" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "एव", transliteration: "eva", meaning: "certainly" },
            { word: "तदर्थीयम्", transliteration: "tad-arthīyam", meaning: "for the sake of That (Brahman)" },
            { word: "सत्", transliteration: "sat", meaning: "Sat (truth)" },
            { word: "इति", transliteration: "iti", meaning: "thus" },
            { word: "एव", transliteration: "eva", meaning: "certainly" },
            { word: "अभिधीयते", transliteration: "abhidhīyate", meaning: "is designated" }
          ],
          translation: "Steadfastness in sacrifice, austerity, and charity is also called 'Sat.' And action performed for the sake of That (Brahman) is also designated as 'Sat.'",
          modernInterpretation: "Krishna deepens the meaning of SAT even further. Not only is SAT used for praiseworthy actions, but STHITI — STEADFASTNESS — in sacrifice, austerity, and charity is ALSO called Sat. And any action performed TAD-ARTHIYAM — for the sake of THAT (Brahman, the Supreme) — is ALSO Sat.\n\nThis is profound. CONSISTENCY in spiritual practice is itself a form of truth. The person who meditates every day for twenty years — that STEADFASTNESS is Sat. Not just the meditation, but the COMMITMENT to it. Not just the charity, but the PERSISTENCE of charitable living. It is one thing to do a good deed. It is another thing entirely to LIVE as a good deed, day after day, year after year.\n\nAnd then the ultimate qualifier: TAD-ARTHIYAM — done for the sake of THAT. When all your actions — your work, your worship, your giving, your discipline — are oriented not toward your ego but toward the SUPREME REALITY, then everything you do becomes Sat. Your morning jog becomes Sat. Your office work becomes Sat. Your cooking becomes Sat. Not because the action itself is special, but because the INTENTION behind it points toward the Infinite.\n\nThis is Krishna collapsing the entire spiritual life into one word. Om is the SOUND of Brahman. Tat is the POINTER to Brahman. Sat is the NATURE of Brahman expressed through your steady, devoted, truthful actions. Three syllables. The entire path of liberation."
        },
        {
          chapter: 17,
          sloka: 28,
          devanagari: "अश्रद्धया हुतं दत्तं तपस्तप्तं कृतं च यत् ।\nअसदित्युच्यते पार्थ न च तत्प्रेत्य नो इह ॥२८॥",
          transliteration: "aśraddhayā hutaṁ dattaṁ tapas taptaṁ kṛtaṁ ca yat |\nasad ity ucyate pārtha na ca tat pretya no iha ||28||",
          words: [
            { word: "अश्रद्धया", transliteration: "aśraddhayā", meaning: "without faith" },
            { word: "हुतम्", transliteration: "hutam", meaning: "offered in sacrifice" },
            { word: "दत्तम्", transliteration: "dattam", meaning: "given in charity" },
            { word: "तपः", transliteration: "tapaḥ", meaning: "austerity" },
            { word: "तप्तम्", transliteration: "taptam", meaning: "performed" },
            { word: "कृतम्", transliteration: "kṛtam", meaning: "done" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "यत्", transliteration: "yat", meaning: "whatever" },
            { word: "असत्", transliteration: "asat", meaning: "Asat (unreal/false)" },
            { word: "इति", transliteration: "iti", meaning: "thus" },
            { word: "उच्यते", transliteration: "ucyate", meaning: "is called" },
            { word: "पार्थ", transliteration: "pārtha", meaning: "O son of Pritha" },
            { word: "न", transliteration: "na", meaning: "not" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "तत्", transliteration: "tat", meaning: "that" },
            { word: "प्रेत्य", transliteration: "pretya", meaning: "after death" },
            { word: "नो", transliteration: "no", meaning: "nor" },
            { word: "इह", transliteration: "iha", meaning: "here (in this world)" }
          ],
          translation: "Whatever is sacrificed, given, or performed, and whatever austerity is practised without faith — it is called 'Asat,' O Partha. It is of no avail either here or hereafter.",
          modernInterpretation: "And THIS is the closing verse of Chapter 17 — and it lands like a THUNDERBOLT. Everything — sacrifice, charity, austerity, any action whatsoever — done WITHOUT SHRADDHA (faith) is ASAT. Unreal. False. Void. And it bears NO fruit — 'na ca tat pretya no iha' — neither in this world NOR in the next.\n\nThis is Krishna's FINAL VERDICT on the matter. You can perform the grandest sacrifice. You can donate millions. You can fast for months and meditate for years. But if there is NO FAITH behind it — if the heart is empty, if the conviction is absent, if you are just going through dead motions — then ALL of it is ASAT. Unreal. Worthless. Zero.\n\nThink about it — a love letter written without love is just ink on paper. A marriage vow spoken without commitment is just words in the air. A prayer recited without belief is just sound waves hitting a wall. The FORM means nothing without the ESSENCE. And the essence is SHRADDHA — faith.\n\nThis is why Chapter 17 is called SHRADDHATRAYA VIBHAGA YOGA. Everything — food, sacrifice, austerity, charity — gets classified by THREE types of faith. But the ULTIMATE message is even simpler: WITHOUT faith, NOTHING counts. With sattvic faith, EVERYTHING counts. Your faith is not an accessory to your spiritual life. Your faith IS your spiritual life.\n\nSo as you leave this chapter, ask yourself the REAL question: What do I have genuine, deep, unshakeable faith IN? Not what do I say I believe. Not what I post about. Not what I perform for others. What do I ACTUALLY trust with my entire being? THAT answer — whatever it is — that is who you are. Yo yac-chraddhaḥ sa eva saḥ. You ARE your faith. Choose it wisely."
        }
        ]