        {
          chapter: 4,
          sloka: 1,
          devanagari: "श्रीभगवानुवाच ।\nइमं विवस्वते योगं प्रोक्तवानहमव्ययम् ।\nविवस्वान्मनवे प्राह मनुरिक्ष्वाकवेऽब्रवीत् ॥१॥",
          transliteration: "śrī-bhagavān uvāca |\nimaṁ vivasvate yogaṁ proktavān aham avyayam |\nvivasvān manave prāha manur ikṣvākave 'bravīt ||1||",
          words: [
            { word: "श्रीभगवान्", transliteration: "śrī-bhagavān", meaning: "the Blessed Lord" },
            { word: "उवाच", transliteration: "uvāca", meaning: "said" },
            { word: "इमम्", transliteration: "imam", meaning: "this" },
            { word: "विवस्वते", transliteration: "vivasvate", meaning: "to Vivasvan (the sun-god)" },
            { word: "योगम्", transliteration: "yogam", meaning: "yoga, science of union" },
            { word: "प्रोक्तवान्", transliteration: "proktavān", meaning: "instructed, taught" },
            { word: "अहम्", transliteration: "aham", meaning: "I" },
            { word: "अव्ययम्", transliteration: "avyayam", meaning: "imperishable, eternal" },
            { word: "विवस्वान्", transliteration: "vivasvān", meaning: "Vivasvan (the sun-god)" },
            { word: "मनवे", transliteration: "manave", meaning: "to Manu (the father of mankind)" },
            { word: "प्राह", transliteration: "prāha", meaning: "told" },
            { word: "मनुः", transliteration: "manuḥ", meaning: "Manu" },
            { word: "इक्ष्वाकवे", transliteration: "ikṣvākave", meaning: "to Ikshvaku" },
            { word: "अब्रवीत्", transliteration: "abravīt", meaning: "told, instructed" },
          ],
          translation: "The Blessed Lord said: I taught this imperishable yoga to Vivasvan (the sun-god); Vivasvan taught it to Manu (the father of mankind); and Manu taught it to Ikshvaku.",
          modernInterpretation: "Krishna casually drops that He taught yoga to the Sun. Not a yoga instructor in Bali — the actual Sun. This is the original 'I was doing this before it was cool.' While we struggle to get three people to attend our webinar, Krishna's ancient knowledge chain went: God → Sun → Father of Humanity → First King. That is the most elite referral chain in history. LinkedIn influencers could never."
        },
        {
          chapter: 4,
          sloka: 2,
          devanagari: "एवं परम्पराप्राप्तमिमं राजर्षयो विदुः ।\nस कालेनेह महता योगो नष्टः परन्तप ॥२॥",
          transliteration: "evaṁ paramparā-prāptam imaṁ rājarṣayo viduḥ |\nsa kāleneha mahatā yogo naṣṭaḥ parantapa ||2||",
          words: [
            { word: "एवम्", transliteration: "evam", meaning: "thus" },
            { word: "परम्पराप्राप्तम्", transliteration: "paramparā-prāptam", meaning: "received through succession, handed down in disciplic chain" },
            { word: "इमम्", transliteration: "imam", meaning: "this" },
            { word: "राजर्षयः", transliteration: "rājarṣayaḥ", meaning: "the saintly kings, royal sages" },
            { word: "विदुः", transliteration: "viduḥ", meaning: "understood, knew" },
            { word: "सः", transliteration: "saḥ", meaning: "that" },
            { word: "कालेन", transliteration: "kālena", meaning: "by time" },
            { word: "इह", transliteration: "iha", meaning: "in this world" },
            { word: "महता", transliteration: "mahatā", meaning: "great (lapse of)" },
            { word: "योगः", transliteration: "yogaḥ", meaning: "yoga, the science" },
            { word: "नष्टः", transliteration: "naṣṭaḥ", meaning: "lost, destroyed" },
            { word: "परन्तप", transliteration: "parantapa", meaning: "O scorcher of foes (Arjuna)" },
          ],
          translation: "Thus received through the chain of disciplic succession, the saintly kings understood this yoga. But over a great passage of time, this yoga was lost in this world, O scorcher of foes.",
          modernInterpretation: "Knowledge was passed down through a perfect chain — guru to student, king to prince — and it still got lost over time. If divine wisdom with a direct-from-God lineage cannot survive the passage of time, what chance does your company's onboarding documentation have? This is basically what happens to every Notion workspace after the original team leaves. Humanity had the source code to liberation and we lost it like a forgotten Google Drive link."
        },
        {
          chapter: 4,
          sloka: 3,
          devanagari: "स एवायं मया तेऽद्य योगः प्रोक्तः पुरातनः ।\nभक्तोऽसि मे सखा चेति रहस्यं ह्येतदुत्तमम् ॥३॥",
          transliteration: "sa evāyaṁ mayā te 'dya yogaḥ proktaḥ purātanaḥ |\nbhakto 'si me sakhā ceti rahasyaṁ hy etad uttamam ||3||",
          words: [
            { word: "सः", transliteration: "saḥ", meaning: "that" },
            { word: "एव", transliteration: "eva", meaning: "certainly, indeed" },
            { word: "अयम्", transliteration: "ayam", meaning: "this" },
            { word: "मया", transliteration: "mayā", meaning: "by Me" },
            { word: "ते", transliteration: "te", meaning: "to you" },
            { word: "अद्य", transliteration: "adya", meaning: "today" },
            { word: "योगः", transliteration: "yogaḥ", meaning: "yoga" },
            { word: "प्रोक्तः", transliteration: "proktaḥ", meaning: "spoken, declared" },
            { word: "पुरातनः", transliteration: "purātanaḥ", meaning: "ancient" },
            { word: "भक्तः", transliteration: "bhaktaḥ", meaning: "devotee" },
            { word: "असि", transliteration: "asi", meaning: "you are" },
            { word: "मे", transliteration: "me", meaning: "My" },
            { word: "सखा", transliteration: "sakhā", meaning: "friend" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "इति", transliteration: "iti", meaning: "therefore" },
            { word: "रहस्यम्", transliteration: "rahasyam", meaning: "secret, mystery" },
            { word: "हि", transliteration: "hi", meaning: "certainly, indeed" },
            { word: "एतत्", transliteration: "etat", meaning: "this" },
            { word: "उत्तमम्", transliteration: "uttamam", meaning: "supreme, highest" },
          ],
          translation: "That very same ancient yoga has been today spoken by Me to you, because you are My devotee and My friend — for this is a supreme secret.",
          modernInterpretation: "Krishna is saying: 'I am telling you this because you are my friend AND my devotee.' Not just a follower — a friend. This is the ultimate inner-circle access. Forget VIP passes and backstage entries — Krishna just gave Arjuna the 'close friends' story on Instagram, except the content is the meaning of existence. The criteria for receiving the highest knowledge is not IQ, not caste, not money — it is love and trust. That is it. The universe's biggest secret runs on friendship, not subscriptions."
        },
        {
          chapter: 4,
          sloka: 4,
          devanagari: "अर्जुन उवाच ।\nअपरं भवतो जन्म परं जन्म विवस्वतः ।\nकथमेतद्विजानीयां त्वमादौ प्रोक्तवानिति ॥४॥",
          transliteration: "arjuna uvāca |\naparaṁ bhavato janma paraṁ janma vivasvataḥ |\nkatham etad vijānīyāṁ tvam ādau proktavān iti ||4||",
          words: [
            { word: "अर्जुन", transliteration: "arjuna", meaning: "Arjuna" },
            { word: "उवाच", transliteration: "uvāca", meaning: "said" },
            { word: "अपरम्", transliteration: "aparam", meaning: "later, recent" },
            { word: "भवतः", transliteration: "bhavataḥ", meaning: "Your" },
            { word: "जन्म", transliteration: "janma", meaning: "birth" },
            { word: "परम्", transliteration: "param", meaning: "earlier, prior" },
            { word: "जन्म", transliteration: "janma", meaning: "birth" },
            { word: "विवस्वतः", transliteration: "vivasvataḥ", meaning: "of Vivasvan (the sun-god)" },
            { word: "कथम्", transliteration: "katham", meaning: "how" },
            { word: "एतत्", transliteration: "etat", meaning: "this" },
            { word: "विजानीयाम्", transliteration: "vijānīyām", meaning: "shall I understand" },
            { word: "त्वम्", transliteration: "tvam", meaning: "You" },
            { word: "आदौ", transliteration: "ādau", meaning: "in the beginning" },
            { word: "प्रोक्तवान्", transliteration: "proktavān", meaning: "instructed, taught" },
            { word: "इति", transliteration: "iti", meaning: "thus" },
          ],
          translation: "Arjuna said: Your birth is recent, and the birth of Vivasvan was in ancient times. How am I to understand that You taught this yoga in the beginning?",
          modernInterpretation: "Arjuna basically fact-checks Krishna in real time. 'Bro, you are my age. The Sun God existed millions of years ago. How exactly did YOU teach HIM?' This is the friend who reads your resume and says 'Wait, you said you have 20 years of experience but you are 25?' Arjuna is not being disrespectful — he genuinely wants to understand. And honestly, this is the most reasonable question anyone has asked in the entire Gita so far. Even best friends deserve a LinkedIn verification."
        },
        {
          chapter: 4,
          sloka: 5,
          devanagari: "श्रीभगवानुवाच ।\nबहूनि मे व्यतीतानि जन्मानि तव चार्जुन ।\nतान्यहं वेद सर्वाणि न त्वं वेत्थ परन्तप ॥५॥",
          transliteration: "śrī-bhagavān uvāca |\nbahūni me vyatītāni janmāni tava cārjuna |\ntāny ahaṁ veda sarvāṇi na tvaṁ vettha parantapa ||5||",
          words: [
            { word: "श्रीभगवान्", transliteration: "śrī-bhagavān", meaning: "the Blessed Lord" },
            { word: "उवाच", transliteration: "uvāca", meaning: "said" },
            { word: "बहूनि", transliteration: "bahūni", meaning: "many" },
            { word: "मे", transliteration: "me", meaning: "My" },
            { word: "व्यतीतानि", transliteration: "vyatītāni", meaning: "have passed" },
            { word: "जन्मानि", transliteration: "janmāni", meaning: "births" },
            { word: "तव", transliteration: "tava", meaning: "your" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "अर्जुन", transliteration: "arjuna", meaning: "O Arjuna" },
            { word: "तानि", transliteration: "tāni", meaning: "those" },
            { word: "अहम्", transliteration: "aham", meaning: "I" },
            { word: "वेद", transliteration: "veda", meaning: "know" },
            { word: "सर्वाणि", transliteration: "sarvāṇi", meaning: "all" },
            { word: "न", transliteration: "na", meaning: "not" },
            { word: "त्वम्", transliteration: "tvam", meaning: "you" },
            { word: "वेत्थ", transliteration: "vettha", meaning: "know" },
            { word: "परन्तप", transliteration: "parantapa", meaning: "O scorcher of foes" },
          ],
          translation: "The Blessed Lord said: Many births of Mine have passed, and many of yours too, O Arjuna. I know them all, but you do not know them, O scorcher of foes.",
          modernInterpretation: "Krishna just casually says: 'We have both been born many times. I remember all of them. You do not.' This is the most savage flex in spiritual history. Imagine someone saying 'We have met in every lifetime, I remember everything — you just forgot.' It is like having 10,000 photos in your Google Photos but no memory of taking any of them. Krishna has unlimited cloud storage for past lives. Arjuna is running on 'free tier — 15 GB only.' The difference between God and man: God never clears His browser history."
        },
        {
          chapter: 4,
          sloka: 6,
          devanagari: "अजोऽपि सन्नव्ययात्मा भूतानामीश्वरोऽपि सन् ।\nप्रकृतिं स्वामधिष्ठाय सम्भवाम्यात्ममायया ॥६॥",
          transliteration: "ajo 'pi sann avyayātmā bhūtānām īśvaro 'pi san |\nprakṛtiṁ svām adhiṣṭhāya sambhavāmy ātma-māyayā ||6||",
          words: [
            { word: "अजः", transliteration: "ajaḥ", meaning: "unborn" },
            { word: "अपि", transliteration: "api", meaning: "although" },
            { word: "सन्", transliteration: "san", meaning: "being" },
            { word: "अव्ययात्मा", transliteration: "avyayātmā", meaning: "imperishable self, undying nature" },
            { word: "भूतानाम्", transliteration: "bhūtānām", meaning: "of all beings" },
            { word: "ईश्वरः", transliteration: "īśvaraḥ", meaning: "the Lord, the Supreme" },
            { word: "अपि", transliteration: "api", meaning: "although" },
            { word: "सन्", transliteration: "san", meaning: "being" },
            { word: "प्रकृतिम्", transliteration: "prakṛtim", meaning: "nature, material energy" },
            { word: "स्वाम्", transliteration: "svām", meaning: "own" },
            { word: "अधिष्ठाय", transliteration: "adhiṣṭhāya", meaning: "presiding over, taking control of" },
            { word: "सम्भवामि", transliteration: "sambhavāmi", meaning: "I manifest, I appear" },
            { word: "आत्ममायया", transliteration: "ātma-māyayā", meaning: "by My own divine power (maya)" },
          ],
          translation: "Though I am unborn, imperishable, and the Lord of all beings, I manifest Myself by controlling My own material nature through My divine power (maya).",
          modernInterpretation: "Krishna says: 'I am unborn, eternal, and the boss of everything — but I still choose to show up.' This is the CEO who owns the company, does not need to come to work, has nothing to prove — but still logs in to the 9 AM standup because the team needs Him. He is not forced to take birth. He is not bound by karma. He literally creates a body out of His own divine power like a developer spinning up a container. God does not get deployed — God self-deploys. Kubernetes could never."
        },
        {
          chapter: 4,
          sloka: 7,
          devanagari: "यदा यदा हि धर्मस्य ग्लानिर्भवति भारत ।\nअभ्युत्थानमधर्मस्य तदात्मानं सृजाम्यहम् ॥७॥",
          transliteration: "yadā yadā hi dharmasya glānir bhavati bhārata |\nabhyutthānam adharmasya tadātmānaṁ sṛjāmy aham ||7||",
          words: [
            { word: "यदा", transliteration: "yadā", meaning: "whenever" },
            { word: "यदा", transliteration: "yadā", meaning: "whenever" },
            { word: "हि", transliteration: "hi", meaning: "certainly, indeed" },
            { word: "धर्मस्य", transliteration: "dharmasya", meaning: "of dharma, of righteousness" },
            { word: "ग्लानिः", transliteration: "glāniḥ", meaning: "decline, decay" },
            { word: "भवति", transliteration: "bhavati", meaning: "occurs, happens" },
            { word: "भारत", transliteration: "bhārata", meaning: "O descendant of Bharata (Arjuna)" },
            { word: "अभ्युत्थानम्", transliteration: "abhyutthānam", meaning: "rise, predominance" },
            { word: "अधर्मस्य", transliteration: "adharmasya", meaning: "of unrighteousness" },
            { word: "तदा", transliteration: "tadā", meaning: "then, at that time" },
            { word: "आत्मानम्", transliteration: "ātmānam", meaning: "Myself" },
            { word: "सृजामि", transliteration: "sṛjāmi", meaning: "I create, I manifest" },
            { word: "अहम्", transliteration: "aham", meaning: "I" },
          ],
          translation: "Whenever there is a decline of dharma (righteousness) and a rise of adharma (unrighteousness), O Bharata, at that time I manifest Myself.",
          modernInterpretation: "This is the most iconic verse in the Gita — the original 'I will be back.' Whenever the world goes off the rails, whenever injustice is trending and dharma is getting ratio'd, Krishna says He personally logs in to fix things. This is not a scheduled maintenance window — it is an on-call SRE who shows up exactly when the production server is on fire. No ticket needed. No approval chain. The universe has a self-healing mechanism, and it is God Himself. Every superhero origin story is a remix of this one verse."
        },
        {
          chapter: 4,
          sloka: 8,
          devanagari: "परित्राणाय साधूनां विनाशाय च दुष्कृताम् ।\nधर्मसंस्थापनार्थाय सम्भवामि युगे युगे ॥८॥",
          transliteration: "paritrāṇāya sādhūnāṁ vināśāya ca duṣkṛtām |\ndharma-saṁsthāpanārthāya sambhavāmi yuge yuge ||8||",
          words: [
            { word: "परित्राणाय", transliteration: "paritrāṇāya", meaning: "for the protection, for the deliverance" },
            { word: "साधूनाम्", transliteration: "sādhūnām", meaning: "of the good, of the righteous" },
            { word: "विनाशाय", transliteration: "vināśāya", meaning: "for the destruction" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "दुष्कृताम्", transliteration: "duṣkṛtām", meaning: "of the evil-doers, the wicked" },
            { word: "धर्मसंस्थापनार्थाय", transliteration: "dharma-saṁsthāpanārthāya", meaning: "for the establishment of dharma" },
            { word: "सम्भवामि", transliteration: "sambhavāmi", meaning: "I manifest, I appear" },
            { word: "युगे", transliteration: "yuge", meaning: "in age, in era" },
            { word: "युगे", transliteration: "yuge", meaning: "after age" },
          ],
          translation: "For the protection of the righteous, for the destruction of the wicked, and for the establishment of dharma, I manifest Myself in every age.",
          modernInterpretation: "Verse 7 was the trailer. This is the full mission statement. Three objectives: protect the good people, destroy the bad actors, and restore dharma. That is it. No committee meetings, no 47-slide strategy deck, no 'let us circle back.' God's OKRs are three lines long and they have not changed across multiple yugas. Protect. Destroy evil. Restore order. If your company's mission statement is longer than God's, you might want to edit it. Also, 'yuge yuge' — age after age — means this is not a one-time hotfix. It is a recurring deployment. The universe runs on CI/CD, and Krishna is the pipeline."
        },
        {
          chapter: 4,
          sloka: 9,
          devanagari: "जन्म कर्म च मे दिव्यमेवं यो वेत्ति तत्त्वतः ।\nत्यक्त्वा देहं पुनर्जन्म नैति मामेति सोऽर्जुन ॥९॥",
          transliteration: "janma karma ca me divyam evaṁ yo vetti tattvataḥ |\ntyaktvā dehaṁ punar janma naiti mām eti so 'rjuna ||9||",
          words: [
            { word: "जन्म", transliteration: "janma", meaning: "birth" },
            { word: "कर्म", transliteration: "karma", meaning: "action, work" },
            { word: "च", transliteration: "ca", meaning: "and" },
            { word: "मे", transliteration: "me", meaning: "My" },
            { word: "दिव्यम्", transliteration: "divyam", meaning: "divine, transcendental" },
            { word: "एवम्", transliteration: "evam", meaning: "thus" },
            { word: "यः", transliteration: "yaḥ", meaning: "one who" },
            { word: "वेत्ति", transliteration: "vetti", meaning: "knows" },
            { word: "तत्त्वतः", transliteration: "tattvataḥ", meaning: "in truth, in reality" },
            { word: "त्यक्त्वा", transliteration: "tyaktvā", meaning: "having left, having abandoned" },
            { word: "देहम्", transliteration: "deham", meaning: "the body" },
            { word: "पुनर्जन्म", transliteration: "punar janma", meaning: "rebirth" },
            { word: "न", transliteration: "na", meaning: "not" },
            { word: "एति", transliteration: "eti", meaning: "attains, comes to" },
            { word: "माम्", transliteration: "mām", meaning: "Me" },
            { word: "एति", transliteration: "eti", meaning: "comes to, reaches" },
            { word: "सः", transliteration: "saḥ", meaning: "he" },
            { word: "अर्जुन", transliteration: "arjuna", meaning: "O Arjuna" },
          ],
          translation: "One who truly knows the divine nature of My birth and actions, upon leaving the body, is not born again — but comes to Me, O Arjuna.",
          modernInterpretation: "Here is the ultimate exit from the rebirth cycle: just truly understand that Krishna's birth and actions are divine, not ordinary. That is the cheat code. No 10,000-hour rule, no premium subscription, no 30-day free trial. Just genuine, deep understanding. But here is the catch — 'tattvataḥ' means 'in truth,' not superficially. You cannot just read the Wikipedia summary and call it done. This is not 'I watched the YouTube explainer so I get it.' It is knowing so deeply that it transforms you. Think of it as the difference between reading about swimming and actually being in the ocean."
        },
        {
          chapter: 4,
          sloka: 10,
          devanagari: "वीतरागभयक्रोधा मन्मया मामुपाश्रिताः ।\nबहवो ज्ञानतपसा पूता मद्भावमागताः ॥१०॥",
          transliteration: "vīta-rāga-bhaya-krodhā man-mayā mām upāśritāḥ |\nbahavo jñāna-tapasā pūtā mad-bhāvam āgatāḥ ||10||",
          words: [
            { word: "वीत", transliteration: "vīta", meaning: "freed from, devoid of" },
            { word: "राग", transliteration: "rāga", meaning: "attachment" },
            { word: "भय", transliteration: "bhaya", meaning: "fear" },
            { word: "क्रोधाः", transliteration: "krodhāḥ", meaning: "anger" },
            { word: "मन्मयाः", transliteration: "man-mayāḥ", meaning: "absorbed in Me, fully in Me" },
            { word: "माम्", transliteration: "mām", meaning: "Me" },
            { word: "उपाश्रिताः", transliteration: "upāśritāḥ", meaning: "taking refuge in" },
            { word: "बहवः", transliteration: "bahavaḥ", meaning: "many" },
            { word: "ज्ञानतपसा", transliteration: "jñāna-tapasā", meaning: "by the fire of knowledge, by the austerity of knowledge" },
            { word: "पूताः", transliteration: "pūtāḥ", meaning: "purified" },
            { word: "मद्भावम्", transliteration: "mad-bhāvam", meaning: "My nature, My state of being" },
            { word: "आगताः", transliteration: "āgatāḥ", meaning: "attained, arrived at" },
          ],
          translation: "Freed from attachment, fear, and anger, absorbed in Me, taking refuge in Me, purified by the fire of knowledge — many have attained My state of being.",
          modernInterpretation: "Krishna gives the alumni list: many people have already graduated from this program. The prerequisites? Drop attachment, fear, and anger — the three apps that drain your battery the fastest. Attachment is that ex's Instagram you keep checking. Fear is the anxiety of 'what will people think.' Anger is every road rage incident and Twitter argument combined. Delete these three apps, fill yourself with divine knowledge, and you reach Krishna's level. Many have done it before you. This is not a beta program — it is a proven path with verified reviews. The only question is: will you uninstall the junk, or keep running on 3% battery forever?"
        },
