        {
          chapter: 4,
          sloka: 11,
          devanagari: "ये यथा मां प्रपद्यन्ते तांस्तथैव भजाम्यहम् ।\nमम वर्त्मानुवर्तन्ते मनुष्याः पार्थ सर्वशः ॥११॥",
          transliteration: "ye yathā māṁ prapadyante tāṁs tathaiva bhajāmy aham |\nmama vartmānuvartante manuṣyāḥ pārtha sarvaśaḥ ||11||",
          words: [
            { word: "ये", transliteration: "ye", meaning: "who" },
            { word: "यथा", transliteration: "yathā", meaning: "as" },
            { word: "माम्", transliteration: "mām", meaning: "Me" },
            { word: "प्रपद्यन्ते", transliteration: "prapadyante", meaning: "surrender" },
            { word: "तान्", transliteration: "tān", meaning: "them" },
            { word: "तथा", transliteration: "tathā", meaning: "so" },
            { word: "एव", transliteration: "eva", meaning: "certainly" },
            { word: "भजामि", transliteration: "bhajāmi", meaning: "I reward / reciprocate" },
            { word: "अहम्", transliteration: "aham", meaning: "I" },
            { word: "मम", transliteration: "mama", meaning: "My" },
            { word: "वर्त्म", transliteration: "vartma", meaning: "path" },
            { word: "अनुवर्तन्ते", transliteration: "anuvartante", meaning: "follow" },
            { word: "मनुष्याः", transliteration: "manuṣyāḥ", meaning: "human beings" },
            { word: "पार्थ", transliteration: "pārtha", meaning: "O Partha (Arjuna)" },
            { word: "सर्वशः", transliteration: "sarvaśaḥ", meaning: "in all respects" }
          ],
          translation: "As they surrender unto Me, I reward them accordingly. Everyone follows My path in all respects, O son of Pritha.",
          modernInterpretation: "Krishna just dropped the ultimate customer service policy: 'You get back exactly what you put in.' This is the cosmic version of 'you reap what you sow' — except the CEO of the universe is personally handling every ticket. Pray for wealth? Here is your wealth track. Seek knowledge? Welcome to the wisdom department. Want nothing but love? VIP lounge, right this way. Krishna is basically saying every spiritual path is a valid URL — they all resolve to the same server. Hindu, Buddhist, atheist doing good karma — all valid endpoints. The divine API accepts all request formats."
        },
        {
          chapter: 4,
          sloka: 12,
          devanagari: "काङ्क्षन्तः कर्मणां सिद्धिं यजन्त इह देवताः ।\nक्षिप्रं हि मानुषे लोके सिद्धिर्भवति कर्मजा ॥१२॥",
          transliteration: "kāṅkṣantaḥ karmaṇāṁ siddhiṁ yajanta iha devatāḥ |\nkṣipraṁ hi mānuṣe loke siddhir bhavati karmajā ||12||",
          words: [
            { word: "काङ्क्षन्तः", transliteration: "kāṅkṣantaḥ", meaning: "desiring" },
            { word: "कर्मणाम्", transliteration: "karmaṇām", meaning: "of actions" },
            { word: "सिद्धिम्", transliteration: "siddhim", meaning: "success / perfection" },
            { word: "यजन्ते", transliteration: "yajante", meaning: "they worship" },
            { word: "इह", transliteration: "iha", meaning: "in this world" },
            { word: "देवताः", transliteration: "devatāḥ", meaning: "the gods / demigods" },
            { word: "क्षिप्रम्", transliteration: "kṣipram", meaning: "quickly" },
            { word: "हि", transliteration: "hi", meaning: "certainly" },
            { word: "मानुषे", transliteration: "mānuṣe", meaning: "in human" },
            { word: "लोके", transliteration: "loke", meaning: "world" },
            { word: "सिद्धिः", transliteration: "siddhiḥ", meaning: "success" },
            { word: "भवति", transliteration: "bhavati", meaning: "comes" },
            { word: "कर्मजा", transliteration: "karmajā", meaning: "born of action" }
          ],
          translation: "Desiring success in their actions, people in this world worship the demigods. For in the human world, success born of action comes quickly.",
          modernInterpretation: "This is the ancient explanation for why people chase quick wins. Want money fast? Worship Lakshmi. Want exams cleared? Saraswati puja. It is the original version of 'Which influencer course should I buy for guaranteed results in 30 days?' People want shortcuts — express delivery spirituality, same-day enlightenment. Amazon Prime for blessings. Krishna is not judging — He is just observing that humans have always preferred the microwave over the slow cooker. The results come fast, sure — but they also expire fast."
        },
        {
          chapter: 4,
          sloka: 13,
          devanagari: "चातुर्वर्ण्यं मया सृष्टं गुणकर्मविभागशः ।\nतस्य कर्तारमपि मां विद्ध्यकर्तारमव्ययम् ॥१३॥",
          transliteration: "cātur-varṇyaṁ mayā sṛṣṭaṁ guṇa-karma-vibhāgaśaḥ |\ntasya kartāram api māṁ viddhy akartāram avyayam ||13||",
          words: [
            { word: "चातुर्वर्ण्यम्", transliteration: "cātur-varṇyam", meaning: "the four divisions of society" },
            { word: "मया", transliteration: "mayā", meaning: "by Me" },
            { word: "सृष्टम्", transliteration: "sṛṣṭam", meaning: "created" },
            { word: "गुण", transliteration: "guṇa", meaning: "qualities / modes of nature" },
            { word: "कर्म", transliteration: "karma", meaning: "action / work" },
            { word: "विभागशः", transliteration: "vibhāgaśaḥ", meaning: "in terms of division" },
            { word: "तस्य", transliteration: "tasya", meaning: "of that" },
            { word: "कर्तारम्", transliteration: "kartāram", meaning: "the creator" },
            { word: "अपि", transliteration: "api", meaning: "although" },
            { word: "माम्", transliteration: "mām", meaning: "Me" },
            { word: "विद्धि", transliteration: "viddhi", meaning: "know" },
            { word: "अकर्तारम्", transliteration: "akartāram", meaning: "the non-doer" },
            { word: "अव्ययम्", transliteration: "avyayam", meaning: "imperishable / unchangeable" }
          ],
          translation: "The four divisions of human society were created by Me according to differences in quality (guna) and action (karma). Though I am the creator of this system, know Me to be the imperishable non-doer.",
          modernInterpretation: "This is THE most misquoted verse in Indian history. Krishna literally says the system is based on guna (your qualities) and karma (your work) — NOT on birth. A coder's son is not automatically a coder. A doctor's daughter does not come out of the womb holding a stethoscope. Krishna designed a skill-based matchmaking system, and humans turned it into a hereditary monarchy. It is like designing LinkedIn for merit-based hiring and watching people turn it into 'My father is MD of the company, please hire me.' Also notice the flex — 'I created the whole system, but I am not bound by it.' Ultimate founder energy: built the product, stepped back, not affected by bugs in production."
        },
        {
          chapter: 4,
          sloka: 14,
          devanagari: "न मां कर्माणि लिम्पन्ति न मे कर्मफले स्पृहा ।\nइति मां योऽभिजानाति कर्मभिर्न स बध्यते ॥१४॥",
          transliteration: "na māṁ karmāṇi limpanti na me karma-phale spṛhā |\niti māṁ yo 'bhijānāti karmabhir na sa badhyate ||14||",
          words: [
            { word: "न", transliteration: "na", meaning: "not" },
            { word: "माम्", transliteration: "mām", meaning: "Me" },
            { word: "कर्माणि", transliteration: "karmāṇi", meaning: "actions" },
            { word: "लिम्पन्ति", transliteration: "limpanti", meaning: "taint / affect" },
            { word: "मे", transliteration: "me", meaning: "My" },
            { word: "कर्मफले", transliteration: "karma-phale", meaning: "in the fruits of action" },
            { word: "स्पृहा", transliteration: "spṛhā", meaning: "desire / aspiration" },
            { word: "इति", transliteration: "iti", meaning: "thus" },
            { word: "यः", transliteration: "yaḥ", meaning: "who" },
            { word: "अभिजानाति", transliteration: "abhijānāti", meaning: "truly knows" },
            { word: "कर्मभिः", transliteration: "karmabhiḥ", meaning: "by actions" },
            { word: "स", transliteration: "sa", meaning: "he" },
            { word: "बध्यते", transliteration: "badhyate", meaning: "is bound" }
          ],
          translation: "Actions do not taint Me, nor do I desire the fruits of action. One who understands this truth about Me is never bound by actions.",
          modernInterpretation: "Krishna is the original open-source contributor — builds the entire universe, asks for zero credit, has no stock options, and does not even check the GitHub stars. He is saying: 'I do everything, but nothing sticks to me because I have no attachment to outcomes.' Imagine working at a startup, shipping features daily, and genuinely not caring about your performance review. Impossible for us, but that is the divine cheat code. And here is the kicker — if YOU understand this principle, you are free too. Work hard, detach from results, and karma cannot touch you. It is like playing a video game in God mode."
        },
        {
          chapter: 4,
          sloka: 15,
          devanagari: "एवं ज्ञात्वा कृतं कर्म पूर्वैरपि मुमुक्षुभिः ।\nकुरु कर्मैव तस्मात्त्वं पूर्वैः पूर्वतरं कृतम् ॥१५॥",
          transliteration: "evaṁ jñātvā kṛtaṁ karma pūrvair api mumukṣubhiḥ |\nkuru karmaiva tasmāt tvaṁ pūrvaiḥ pūrvataraṁ kṛtam ||15||",
          words: [
            { word: "एवम्", transliteration: "evam", meaning: "thus" },
            { word: "ज्ञात्वा", transliteration: "jñātvā", meaning: "having known" },
            { word: "कृतम्", transliteration: "kṛtam", meaning: "performed" },
            { word: "कर्म", transliteration: "karma", meaning: "action" },
            { word: "पूर्वैः", transliteration: "pūrvaiḥ", meaning: "by the ancients" },
            { word: "अपि", transliteration: "api", meaning: "also" },
            { word: "मुमुक्षुभिः", transliteration: "mumukṣubhiḥ", meaning: "by those seeking liberation" },
            { word: "कुरु", transliteration: "kuru", meaning: "perform" },
            { word: "कर्म", transliteration: "karma", meaning: "action" },
            { word: "एव", transliteration: "eva", meaning: "certainly" },
            { word: "तस्मात्", transliteration: "tasmāt", meaning: "therefore" },
            { word: "त्वम्", transliteration: "tvam", meaning: "you" },
            { word: "पूर्वतरम्", transliteration: "pūrvataram", meaning: "in ancient times" }
          ],
          translation: "Knowing this, the ancient seekers of liberation also performed action. Therefore, you too should perform action, as the ancients did in bygone times.",
          modernInterpretation: "Krishna pulls the ultimate 'even your seniors did it' card. 'The OG seekers — Janaka, Manu, all the legends — they knew the truth AND still showed up to work every day. So do not sit here acting like enlightenment means becoming a full-time couch philosopher.' This is Krishna shutting down every excuse. You cannot say 'I am too spiritual to work.' The greatest sages in history had 9-to-5s. Imagine Janaka updating his LinkedIn: 'King by day, Self-realized soul by night. Open to opportunities in both governance and moksha.' If they could balance karma and jnana, you can at least answer your emails."
        },
        {
          chapter: 4,
          sloka: 16,
          devanagari: "किं कर्म किमकर्मेति कवयोऽप्यत्र मोहिताः ।\nतत्ते कर्म प्रवक्ष्यामि यज्ज्ञात्वा मोक्ष्यसेऽशुभात् ॥१६॥",
          transliteration: "kiṁ karma kim akarmeti kavayo 'py atra mohitāḥ |\ntat te karma pravakṣyāmi yaj jñātvā mokṣyase 'śubhāt ||16||",
          words: [
            { word: "किम्", transliteration: "kim", meaning: "what" },
            { word: "कर्म", transliteration: "karma", meaning: "action" },
            { word: "किम्", transliteration: "kim", meaning: "what" },
            { word: "अकर्म", transliteration: "akarma", meaning: "inaction" },
            { word: "इति", transliteration: "iti", meaning: "thus" },
            { word: "कवयः", transliteration: "kavayaḥ", meaning: "the wise / poets" },
            { word: "अपि", transliteration: "api", meaning: "even" },
            { word: "अत्र", transliteration: "atra", meaning: "here / in this matter" },
            { word: "मोहिताः", transliteration: "mohitāḥ", meaning: "confused / bewildered" },
            { word: "तत्", transliteration: "tat", meaning: "that" },
            { word: "ते", transliteration: "te", meaning: "to you" },
            { word: "प्रवक्ष्यामि", transliteration: "pravakṣyāmi", meaning: "I shall explain" },
            { word: "यत्", transliteration: "yat", meaning: "which" },
            { word: "ज्ञात्वा", transliteration: "jñātvā", meaning: "having known" },
            { word: "मोक्ष्यसे", transliteration: "mokṣyase", meaning: "you shall be liberated" },
            { word: "अशुभात्", transliteration: "aśubhāt", meaning: "from inauspiciousness / evil" }
          ],
          translation: "What is action? What is inaction? Even the wise are confused about this. I shall explain to you what action is, knowing which you shall be liberated from evil.",
          modernInterpretation: "Even the intellectuals are confused — and Krishna acknowledges it. This is like a professor saying 'Even PhDs get this wrong, so pay attention.' The question of what counts as real action versus inaction has confused philosophers for millennia. Is sitting in meditation action or inaction? Is a busy person who accomplishes nothing actually doing anything? Krishna is about to drop the most counterintuitive framework in philosophy. Buckle up — this is the part where your brain does a system restart. If even the ancient sages needed clarification, maybe do not feel bad about being confused at your Monday morning standup."
        },
        {
          chapter: 4,
          sloka: 17,
          devanagari: "कर्मणो ह्यपि बोद्धव्यं बोद्धव्यं च विकर्मणः ।\nअकर्मणश्च बोद्धव्यं गहना कर्मणो गतिः ॥१७॥",
          transliteration: "karmaṇo hy api boddhavyaṁ boddhavyaṁ ca vikarmaṇaḥ |\nakarmaṇaś ca boddhavyaṁ gahanā karmaṇo gatiḥ ||17||",
          words: [
            { word: "कर्मणः", transliteration: "karmaṇaḥ", meaning: "of action" },
            { word: "हि", transliteration: "hi", meaning: "certainly" },
            { word: "अपि", transliteration: "api", meaning: "also" },
            { word: "बोद्धव्यम्", transliteration: "boddhavyam", meaning: "should be understood" },
            { word: "विकर्मणः", transliteration: "vikarmaṇaḥ", meaning: "of forbidden action" },
            { word: "अकर्मणः", transliteration: "akarmaṇaḥ", meaning: "of inaction" },
            { word: "गहना", transliteration: "gahanā", meaning: "very difficult / deep" },
            { word: "कर्मणः", transliteration: "karmaṇaḥ", meaning: "of action" },
            { word: "गतिः", transliteration: "gatiḥ", meaning: "the path / course" }
          ],
          translation: "One must understand the nature of action, the nature of forbidden action, and the nature of inaction. The path of action is deep and difficult to understand.",
          modernInterpretation: "Krishna introduces three categories: karma (right action), vikarma (wrong action), and akarma (inaction / transcendental non-action). Think of it as a spiritual traffic light — green, red, and a mysterious fourth signal nobody taught you about in driving school. Most people only understand green and red. But Krishna is saying there is a whole dimension you are missing. Doing the right thing (karma) — straightforward. Doing the wrong thing (vikarma) — obviously bad. But understanding the nature of true inaction (akarma) — that is where it gets deep. This is the advanced course, and Krishna just warned you: 'The syllabus is thick.' Even Google Maps cannot navigate this — you need a guru."
        },
        {
          chapter: 4,
          sloka: 18,
          devanagari: "कर्मण्यकर्म यः पश्येदकर्मणि च कर्म यः ।\nस बुद्धिमान्मनुष्येषु स युक्तः कृत्स्नकर्मकृत् ॥१८॥",
          transliteration: "karmaṇy akarma yaḥ paśyed akarmaṇi ca karma yaḥ |\nsa buddhimān manuṣyeṣu sa yuktaḥ kṛtsna-karma-kṛt ||18||",
          words: [
            { word: "कर्मणि", transliteration: "karmaṇi", meaning: "in action" },
            { word: "अकर्म", transliteration: "akarma", meaning: "inaction" },
            { word: "यः", transliteration: "yaḥ", meaning: "who" },
            { word: "पश्येत्", transliteration: "paśyet", meaning: "sees" },
            { word: "अकर्मणि", transliteration: "akarmaṇi", meaning: "in inaction" },
            { word: "कर्म", transliteration: "karma", meaning: "action" },
            { word: "सः", transliteration: "saḥ", meaning: "he" },
            { word: "बुद्धिमान्", transliteration: "buddhimān", meaning: "intelligent / wise" },
            { word: "मनुष्येषु", transliteration: "manuṣyeṣu", meaning: "among human beings" },
            { word: "युक्तः", transliteration: "yuktaḥ", meaning: "engaged in yoga / spiritually connected" },
            { word: "कृत्स्नकर्मकृत्", transliteration: "kṛtsna-karma-kṛt", meaning: "doer of all actions" }
          ],
          translation: "One who sees inaction in action, and action in inaction, is wise among human beings. Such a person is a yogi and has accomplished all actions.",
          modernInterpretation: "This is the verse that breaks brains. Read it twice. Three times. Still confused? Good — that means you are paying attention. Krishna says the truly wise person can be incredibly busy yet internally still (inaction in action), and can appear to be doing nothing yet be profoundly active (action in inaction). Think of it this way: your colleague who is 'always busy' on Slack but produces nothing? That is action with no real action. Your quiet coworker who barely speaks in meetings but somehow ships the entire product? That is inaction with real action. The monk meditating under a tree is doing more for the world than the influencer posting 47 Instagram stories about 'hustle culture.' This verse is Krishna's way of saying: busyness is not productivity, and stillness is not laziness. The wise see through the illusion."
        },
        {
          chapter: 4,
          sloka: 19,
          devanagari: "यस्य सर्वे समारम्भाः कामसङ्कल्पवर्जिताः ।\nज्ञानाग्निदग्धकर्माणं तमाहुः पण्डितं बुधाः ॥१९॥",
          transliteration: "yasya sarve samārambhāḥ kāma-saṅkalpa-varjitāḥ |\njñānāgni-dagdha-karmāṇaṁ tam āhuḥ paṇḍitaṁ budhāḥ ||19||",
          words: [
            { word: "यस्य", transliteration: "yasya", meaning: "whose" },
            { word: "सर्वे", transliteration: "sarve", meaning: "all" },
            { word: "समारम्भाः", transliteration: "samārambhāḥ", meaning: "undertakings / endeavors" },
            { word: "काम", transliteration: "kāma", meaning: "desire" },
            { word: "सङ्कल्प", transliteration: "saṅkalpa", meaning: "intention / selfish motive" },
            { word: "वर्जिताः", transliteration: "varjitāḥ", meaning: "devoid of / free from" },
            { word: "ज्ञानाग्नि", transliteration: "jñānāgni", meaning: "fire of knowledge" },
            { word: "दग्ध", transliteration: "dagdha", meaning: "burned" },
            { word: "कर्माणम्", transliteration: "karmāṇam", meaning: "whose actions" },
            { word: "तम्", transliteration: "tam", meaning: "him" },
            { word: "आहुः", transliteration: "āhuḥ", meaning: "they call" },
            { word: "पण्डितम्", transliteration: "paṇḍitam", meaning: "a wise person / scholar" },
            { word: "बुधाः", transliteration: "budhāḥ", meaning: "the knowledgeable ones" }
          ],
          translation: "One whose every undertaking is free from desire and selfish motive, and whose actions have been burned in the fire of knowledge — such a person is called wise by the knowledgeable.",
          modernInterpretation: "The fire of knowledge is the ultimate antivirus software — it burns the karmic malware right off your hard drive. A truly wise person still does things — starts projects, builds businesses, raises families — but without the desperate clutching of 'what is in it for me?' Imagine a founder who builds a company not for the IPO but because the work itself matters. No desire for the Forbes list, no fantasy about the exit. The work IS the reward. The 'fire of knowledge' is realizing that you were never the doer in the first place — once that hits you, karma has nothing to stick to. It is like trying to write on a whiteboard that has already been flame-cleaned. The wise call this person a pandit — not the astrology-app kind, the real kind."
        },
        {
          chapter: 4,
          sloka: 20,
          devanagari: "त्यक्त्वा कर्मफलासङ्गं नित्यतृप्तो निराश्रयः ।\nकर्मण्यभिप्रवृत्तोऽपि नैव किञ्चित्करोति सः ॥२०॥",
          transliteration: "tyaktvā karma-phalāsaṅgaṁ nitya-tṛpto nirāśrayaḥ |\nkarmaṇy abhipravṛtto 'pi naiva kiñcit karoti saḥ ||20||",
          words: [
            { word: "त्यक्त्वा", transliteration: "tyaktvā", meaning: "having abandoned" },
            { word: "कर्मफल", transliteration: "karma-phala", meaning: "fruits of action" },
            { word: "आसङ्गम्", transliteration: "āsaṅgam", meaning: "attachment" },
            { word: "नित्य", transliteration: "nitya", meaning: "always" },
            { word: "तृप्तः", transliteration: "tṛptaḥ", meaning: "satisfied / content" },
            { word: "निराश्रयः", transliteration: "nirāśrayaḥ", meaning: "without dependence / shelter" },
            { word: "कर्मणि", transliteration: "karmaṇi", meaning: "in action" },
            { word: "अभिप्रवृत्तः", transliteration: "abhipravṛttaḥ", meaning: "fully engaged" },
            { word: "अपि", transliteration: "api", meaning: "even though" },
            { word: "न", transliteration: "na", meaning: "not" },
            { word: "एव", transliteration: "eva", meaning: "certainly" },
            { word: "किञ्चित्", transliteration: "kiñcit", meaning: "anything" },
            { word: "करोति", transliteration: "karoti", meaning: "does" },
            { word: "सः", transliteration: "saḥ", meaning: "he" }
          ],
          translation: "Having abandoned attachment to the fruits of action, ever content, depending on nothing — such a person, even though fully engaged in action, does nothing at all.",
          modernInterpretation: "This is the ultimate paradox and the ultimate flex. This person is FULLY engaged — shipping code, running meetings, building things — yet karmically, they are doing absolutely nothing. How? Because there is zero attachment. No refreshing the inbox for praise. No checking LinkedIn for likes on that post. No mentally rehearsing the acceptance speech while the award is still being decided. They work like their life depends on it, but live like none of it matters. It is the spiritual equivalent of a surgeon who performs a 12-hour operation with total focus and then goes home and sleeps like a baby — no replaying, no anxiety, no 'what if.' Krishna just described the rarest human being on earth: someone who works without needing the work to complete them. The rest of us are still refreshing our notifications."
        },
