#!/usr/bin/env python3
"""
Runtime audit of every solution in interview/data/questions.json.

Python solutions are exec()'d inside a sandboxed namespace with the same
prelude as the in-browser playground, plus a canonical demo invocation
when we can pattern-match the function name. Failures (parse error or
runtime exception) are reported.

SQL solutions are run against an in-memory SQLite DB whose tables are
generated by interview/scripts/extract_schemas.py output (the same way
the playground does it). Statements that legitimately use
Snowflake/PostgreSQL-only syntax are flagged but counted separately.

Usage:  python3 interview/scripts/audit_solutions.py [--write-report]
"""

from __future__ import annotations

import argparse
import ast
import io
import json
import sqlite3
import sys
import traceback
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
QUESTIONS = ROOT / "interview" / "data" / "questions.json"
SCHEMAS   = ROOT / "interview" / "data" / "question_schemas.json"
REPORT    = ROOT / "interview" / "data" / "audit_report.json"

# ─── canonical demo args (mirror demo-gen.js) ───────────────────────────
FUNC_CANONICAL = {
    "minWindow":                '"ADOBECODEBANC", "ABC"',
    "lengthOfLongestSubstring": '"abcabcbb"',
    "characterReplacement":     '"AABABBA", 1',
    "checkInclusion":           '"ab", "eidbaooo"',
    "isAnagram":                '"anagram", "nagaram"',
    "longestPalindrome":        '"babad"',
    "isPalindrome":             '"A man, a plan, a canal: Panama"',
    "groupAnagrams":            '["eat","tea","tan","ate","nat","bat"]',
    "wordBreak":                '"leetcode", ["leet","code"]',
    "twoSum":                   '[2, 7, 11, 15], 9',
    "threeSum":                 '[-1, 0, 1, 2, -1, -4]',
    "maxArea":                  '[1,8,6,2,5,4,8,3,7]',
    "trap":                     '[0,1,0,2,1,0,1,3,2,1,2,1]',
    "productExceptSelf":        '[1, 2, 3, 4]',
    # `rotate` is overloaded across LeetCode problems — leave to per-question
    # demo override or skip canonical handling.
    "containsDuplicate":        '[1, 2, 3, 1]',
    "topKFrequent":             '[1,1,1,2,2,3], 2',
    "subarraySum":              '[1, 1, 1], 2',
    "longestConsecutive":       '[100, 4, 200, 1, 3, 2]',
    "search":                   '[-1, 0, 3, 5, 9, 12], 9',
    "searchInsert":             '[1, 3, 5, 6], 5',
    "findMin":                  '[3, 4, 5, 1, 2]',
    "climbStairs":              '5',
    "fib":                      '10',
    "coinChange":               '[1, 2, 5], 11',
    "rob":                      '[2, 7, 9, 3, 1]',
    "maxProfit":                '[7, 1, 5, 3, 6, 4]',
    "uniquePaths":              '3, 7',
    "longestCommonSubsequence": '"abcde", "ace"',
    "alienOrder":               '["wrt","wrf","er","ett","rftt"]',
    "merge":                    '[[1,3],[2,6],[8,10],[15,18]]',
    "insert":                   '[[1,3],[6,9]], [2, 5]',
    "eraseOverlapIntervals":    '[[1,2],[2,3],[3,4],[1,3]]',
    "ladderLength":             '"hit", "cog", ["hot","dot","dog","lot","log","cog"]',
    "canFinish":                '2, [[1, 0]]',
    "numIslands":               '[["1","1","0","0","0"],["1","1","0","0","0"],["0","0","1","0","0"],["0","0","0","1","1"]]',
    "evalRPN":                  '["2", "1", "+", "3", "*"]',
    "isValid":                  '"()[]{}"',
    "decodeString":             '"3[a2[c]]"',
    "validTree":                '5, [[0,1],[0,2],[0,3],[1,4]]',
    "compare":                  None,  # signature varies per question — skip
}

PRELUDE_PY = """
import sys, io, json, math, re, random, itertools, functools
from collections import Counter, defaultdict, deque, OrderedDict
import heapq
"""

# ─── synthetic SQLite generator (mirror sample-gen.js, simplified) ─────
def _seed(qid):
    h = 0
    for c in qid:
        h = ((h << 5) - h + ord(c)) & 0xFFFFFFFF
    return h or 1


def _infer_type(col):
    c = col.lower()
    if c == "id" or c.endswith("_id"):
        return "INTEGER"
    if c.startswith("is_"):
        return "INTEGER"
    if any(k in c for k in (
        "amount", "price", "total", "revenue", "salary", "bonus", "cost",
        "budget", "spend", "spent", "weight", "score", "rate", "value",
        "profit", "fee", "tax", "discount", "balance", "due_amount",
        "paid_amount", "cogs", "avg_",
    )):
        return "REAL"
    if any(k in c for k in (
        "qty", "quantity", "count", "views", "likes", "comments", "clicks",
        "impressions", "sessions", "wau", "dau", "mau", "days", "seconds",
        "minutes", "hours", "capacity",
    )) or c == "age":
        return "INTEGER"
    return "TEXT"


def _sample_value(col, i):
    t = _infer_type(col)
    c = col.lower()
    if t == "INTEGER":
        if c == "id" or c.endswith("_id"):
            return i
        if c.startswith("is_"):
            return i % 2
        return (i * 7) % 500 + 1
    if t == "REAL":
        return round(((i * 13.7) % 1000) + 10, 2)
    if "date" in c or c.endswith("_on"):
        return f"2024-{(i % 12) + 1:02d}-{(i % 27) + 1:02d}"
    if c.endswith("_at") or c.endswith("_ts") or c == "timestamp":
        return f"2024-01-{(i % 27) + 1:02d} 12:00:00"
    if "email" in c:
        return f"user{i}@example.com"
    if "country" in c:
        return ["IN", "US", "DE", "BR", "JP"][i % 5]
    if c == "city":
        return ["BLR", "NYC", "LON", "TYO", "SFO"][i % 5]
    if "category" in c:
        return ["Electronics", "Books", "Home"][i % 3]
    if c == "status":
        return ["pending", "active", "completed"][i % 3]
    if c.endswith("_name") or c == "name":
        return f"Name_{i}"
    return f"{col}_{i}"


def _build_db(spec, n_rows=12):
    con = sqlite3.connect(":memory:")
    for table in spec:
        cols = table["columns"]
        defs = ", ".join(f'"{c}" {_infer_type(c)}' for c in cols)
        con.execute(f'CREATE TABLE "{table["table"]}" ({defs})')
        rows = [tuple(_sample_value(c, i) for c in cols) for i in range(1, n_rows + 1)]
        ph = ",".join("?" * len(cols))
        con.executemany(f'INSERT INTO "{table["table"]}" VALUES ({ph})', rows)
    return con


# ─── Python audit ──────────────────────────────────────────────────────
def audit_python(q):
    src = q.get("solution") or ""
    if not src.strip():
        return {"qid": q["id"], "status": "empty"}
    # Honour the runtime tag from extract: pyspark / third-party / pandas
    # are intentionally not runnable in this audit (no Pyodide here).
    rt = q.get("runtime")
    if rt in ("pyspark", "third-party", "pandas"):
        return {"qid": q["id"], "status": "skipped_runtime", "runtime": rt}
    try:
        ast.parse(src)
    except SyntaxError as e:
        return {"qid": q["id"], "status": "parse_error", "msg": str(e)}

    # Try to find a top-level function and call it with canonical args.
    fn = None
    cls = None
    try:
        tree = ast.parse(src)
        for node in tree.body:
            if isinstance(node, ast.FunctionDef) and not fn:
                fn = node.name
            if isinstance(node, ast.ClassDef) and not cls:
                cls = node.name
    except Exception:
        pass

    demo = ""
    if fn and fn in FUNC_CANONICAL:
        demo = f"\n_result = {fn}({FUNC_CANONICAL[fn]})\nprint(_result)\n"
    elif fn:
        # Skip — running with bogus args produces noise. Just verify it imports + parses.
        pass

    full = PRELUDE_PY + src + demo
    g = {"__name__": "__main__"}
    out, err = io.StringIO(), io.StringIO()
    try:
        with redirect_stdout(out), redirect_stderr(err):
            exec(compile(full, q["id"], "exec"), g)
    except SystemExit:
        pass
    except Exception as e:
        return {
            "qid": q["id"],
            "status": "runtime_error" if not demo else "runtime_error_demo",
            "msg": f"{type(e).__name__}: {e}",
            "fn": fn,
            "had_demo": bool(demo),
        }
    return {"qid": q["id"], "status": "ok", "fn": fn, "had_demo": bool(demo)}


# ─── SQL audit ─────────────────────────────────────────────────────────
SNOWFLAKE_ONLY = (
    "QUALIFY ", "ILIKE", "IFF(", "DATE_TRUNC", "TIMESTAMPDIFF", "TO_VARIANT",
    "FLATTEN", "::", "ARRAY_AGG", "OBJECT_AGG", "STRING_AGG", "LISTAGG",
    "REGEXP_LIKE", "REGEXP_SUBSTR", "TIMESTAMP_NTZ", "TIMESTAMP_TZ",
    "MERGE INTO", "MATCH_RECOGNIZE", "TRY_CAST", "DIV0(", "ZEROIFNULL",
    "NVL(",
)
PG_ONLY = (
    "DATE_PART(", "GENERATE_SERIES", "::REGCLASS", "RETURNING", "ARRAY[",
    "JSONB", "->>", "@>", "INTERVAL '",   # PG/Snowflake interval literals
    "TO_CHAR(", "TO_DATE(", "SPLIT_PART(", "REGEXP_MATCHES(",
    "REGEXP_REPLACE(", "STDDEV(", "VARIANCE(", "PERCENTILE_",
    "GROUPING SETS", "CUBE(", "ROLLUP(", "UNNEST(", "ANY(",
    "DAYOFWEEK(", "DAYOFMONTH(", "WEEKOFYEAR(", "DATE_FORMAT(",
    "FROM_UNIXTIME(", "UNIX_TIMESTAMP(", "SHA2(", "MD5(",
    "CONCAT_WS(", "STRING_TO_ARRAY(",
)


def detect_dialect(sql):
    up = sql.upper()
    if any(tok in up for tok in SNOWFLAKE_ONLY):
        return "snowflake"
    if any(tok in up for tok in PG_ONLY):
        return "postgres"
    # EXTRACT works in SQLite via builtins on some platforms; some questions
    # use it idiomatically. Treat as PG to be safe (it'll still execute via
    # the playground's friendlier banner).
    if "EXTRACT(" in up and "FROM" in up:
        return "postgres"
    return "sqlite"


def audit_sql(q, schemas):
    src = (q.get("solution") or "").strip()
    if not src:
        return {"qid": q["id"], "status": "empty"}
    if q.get("runtime") == "non-sqlite":
        return {"qid": q["id"], "status": "skipped_dialect", "token": q.get("dialect_token")}
    spec = schemas.get(q["id"], [])
    dialect = detect_dialect(src)
    if dialect != "sqlite":
        return {"qid": q["id"], "status": "skipped_dialect", "dialect": dialect}

    if not spec:
        return {"qid": q["id"], "status": "no_schema"}

    try:
        con = _build_db(spec)
    except Exception as e:
        return {"qid": q["id"], "status": "schema_build_error", "msg": str(e)}

    # Some questions have multi-statement DDL; let executescript handle them.
    try:
        con.executescript(src)
    except sqlite3.Error as e:
        return {
            "qid": q["id"],
            "status": "runtime_error",
            "msg": str(e),
            "tables": [t["table"] for t in spec],
        }
    finally:
        con.close()
    return {"qid": q["id"], "status": "ok", "tables": [t["table"] for t in spec]}


# ─── main ──────────────────────────────────────────────────────────────
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write-report", action="store_true")
    args = ap.parse_args()

    questions = json.loads(QUESTIONS.read_text())
    schemas = json.loads(SCHEMAS.read_text()) if SCHEMAS.exists() else {}

    py_results = [audit_python(q) for q in questions if q.get("language") == "python"]
    sql_results = [audit_sql(q, schemas) for q in questions if q.get("language") == "sql"]

    def tally(results):
        from collections import Counter
        return Counter(r["status"] for r in results)

    print(f"PYTHON ({len(py_results)} solutions):")
    for k, v in sorted(tally(py_results).items()):
        print(f"  {k:24s} {v:4d}")
    print()
    print(f"SQL ({len(sql_results)} solutions):")
    for k, v in sorted(tally(sql_results).items()):
        print(f"  {k:24s} {v:4d}")

    # Show worst offenders
    py_bad = [r for r in py_results if r["status"] not in ("ok",)]
    sql_bad = [r for r in sql_results if r["status"] not in ("ok", "skipped_dialect")]

    print(f"\nPython issues: {len(py_bad)}")
    for r in py_bad[:30]:
        print(f"  [{r['qid']}] {r['status']}: {r.get('msg','')[:120]}")

    print(f"\nSQL issues (sqlite only): {len(sql_bad)}")
    for r in sql_bad[:30]:
        print(f"  [{r['qid']}] {r['status']}: {r.get('msg','')[:120]}")

    if args.write_report:
        REPORT.write_text(json.dumps(
            {"python": py_results, "sql": sql_results},
            indent=2, ensure_ascii=False,
        ))
        print(f"\nWrote {REPORT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
