/* ============================================================
   Interview Studio — Jobs board
   Renders interview.app/jobs/data/jobs.json. Every role links two ways:
   into the question bank filtered by that company (?company=Name), and out
   to apply. No backend, no tracking — the data file is regenerated by
   interview/scripts/build_jobs.py.
   ============================================================ */
(function () {
  "use strict";

  var $ = function (sel) { return document.querySelector(sel); };
  var listEl = $("#jobs-list");
  var countEl = $("#jobs-count");
  var noteEl = $("#jobs-note");
  var filterEl = $("#jobs-filter");
  var updatedEl = $("#jobs-updated");

  var all = [];

  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }

  function countLabel(counts) {
    var n = (counts && counts.total) || 0;
    var bits = [];
    if (counts && counts.sql) bits.push(counts.sql + " SQL");
    if (counts && counts.python) bits.push(counts.python + " Py");
    var breakdown = bits.length ? " (" + bits.join(" · ") + ")" : "";
    return { n: n, breakdown: breakdown };
  }

  function cardHTML(job) {
    var c = countLabel(job.counts);
    var practice =
      c.n > 0
        ? '<a class="job-practice" href="' +
          esc(job.practice_url) +
          '" title="Open the ' +
          esc(job.company) +
          " questions in the bank\">▸ Practice <span class=\"pct\">" +
          c.n +
          "</span> " +
          esc(job.company) +
          " question" + (c.n === 1 ? "" : "s") +
          "</a>"
        : "";
    var apply = job.apply_url
      ? '<a class="job-apply" href="' +
        esc(job.apply_url) +
        '" target="_blank" rel="noopener nofollow">Apply on source →</a>'
      : "";
    var loc = job.location ? '<span class="job-loc">' + esc(job.location) + "</span>" : "";
    var tag = job.sample ? '<span class="job-tag">sample</span>' : "";

    return (
      '<div class="job-card">' +
      "<div>" +
      '<h2 class="job-role">' + esc(job.role) + "</h2>" +
      '<div class="job-meta">' +
      '<span class="job-co">' + esc(job.company) + "</span>" +
      loc +
      (c.breakdown ? '<span>' + esc(c.breakdown.trim()) + "</span>" : "") +
      tag +
      "</div>" +
      "</div>" +
      '<div class="job-actions">' + practice + apply + "</div>" +
      "</div>"
    );
  }

  function render(rows) {
    if (!rows.length) {
      listEl.innerHTML =
        '<div class="jobs-empty">No roles match that filter. <a href="#" id="jobs-clear">Clear it</a> to see them all.</div>';
      var clr = $("#jobs-clear");
      if (clr)
        clr.addEventListener("click", function (e) {
          e.preventDefault();
          filterEl.value = "";
          apply();
        });
      countEl.innerHTML = "<strong>0</strong> roles";
      return;
    }
    listEl.innerHTML = rows.map(cardHTML).join("");
    countEl.innerHTML = "<strong>" + rows.length + "</strong> role" + (rows.length === 1 ? "" : "s");
  }

  function apply() {
    var q = (filterEl.value || "").trim().toLowerCase();
    if (!q) return render(all);
    render(
      all.filter(function (j) {
        return (
          (j.company || "").toLowerCase().indexOf(q) !== -1 ||
          (j.role || "").toLowerCase().indexOf(q) !== -1 ||
          (j.location || "").toLowerCase().indexOf(q) !== -1
        );
      })
    );
  }

  function boot(data) {
    all = (data && data.jobs) || [];
    if (noteEl) noteEl.hidden = !(data && data.mode === "sample");
    if (updatedEl && data && data.generated_at) {
      updatedEl.textContent = data.generated_at.slice(0, 10);
    }
    render(all);
    if (filterEl) filterEl.addEventListener("input", apply);
  }

  fetch("./data/jobs.json", { cache: "no-cache" })
    .then(function (r) {
      if (!r.ok) throw new Error("HTTP " + r.status);
      return r.json();
    })
    .then(boot)
    .catch(function (err) {
      listEl.innerHTML =
        '<div class="jobs-error"><p>Couldn’t load the jobs board (' +
        esc(err.message) +
        ").</p><p style=\"font-family:var(--font-mono);font-size:12px;color:var(--text-3)\">Meanwhile, the full <a href=\"../\">question bank</a> is company-filterable.</p></div>";
      countEl.textContent = "";
    });
})();
