#!/usr/bin/env node
/**
 * Every Arrow Is a Decision — build and check, both editions.
 *
 * EDITION 3 is archived at articles/every-arrow/edition-3.html and built by the code
 * in this file (steps 1–7 below). EDITION 4, the live essay at
 * articles/every-arrow-is-a-decision.html, is built by edition4.mjs, which this file
 * runs last — so one command covers both.
 *
 *   node scripts/every_arrow/build.mjs            write: regenerate everything below
 *   node scripts/every_arrow/build.mjs --check    CI: fail if anything is stale or inconsistent
 *   EA_DEPS=/dir/with/node_modules node scripts/every_arrow/build.mjs --pdf
 *                                                 also render the printable PDF (needs playwright)
 *
 * What it does, in order:
 *   1. articles/every-arrow/northstar.js — the subset of the Command Center's synthetic
 *      Northstar dataset (privacy-command-center/v10/data.js) that the essay reads. ONE dataset
 *      for both experiences: the essay never types a Northstar number.
 *   2. Every static fallback in the essay (<div … data-static="X">…</div><!-- /static:X -->):
 *      the no-JS, print and PDF version of each figure, rendered from the SAME data, model
 *      and trail engine the interactive figures use (data.js, model.js, trails.js).
 *   3. The Sources list, from sources.js — and a check that every inline citation
 *      (data-src) has an entry and every entry is cited.
 *   4. Counts and reading times (chapters, scenes, figures, full and executive path), stamped
 *      into every data-ea span, the JSON-LD, article_metadata.json, the /articles/ deck card
 *      and the homepage feature — so they agree everywhere.
 *   5. ?v=<hash> on the essay's own CSS/JS links, so new HTML never meets an old script.
 *   6. With --pdf: the printable edition (articles/every-arrow/every-arrow-is-a-decision.pdf)
 *      and pdf.json (page count + a hash of the source it was rendered from). --check fails
 *      when the PDF is older than its source.
 */
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const A = (p) => path.join(ROOT, p);
const ESSAY = 'articles/every-arrow/edition-3.html';   // the archived edition 3 (edition 4 is edition4.mjs)
const DIR = 'articles/every-arrow';
const WPM = 230;            // words per minute for prose
const FIG_SECONDS = 20;     // time allowed per interactive figure on the full path
const args = new Set(process.argv.slice(2));
const CHECK = args.has('--check');
const problems = [];

/* ── load the browser files in a sandbox ─────────────────────────── */
function load(files) {
  const ctx = { console };
  ctx.window = ctx; ctx.globalThis = ctx;
  vm.createContext(ctx);
  for (const f of files) vm.runInContext(fs.readFileSync(A(f), 'utf8'), ctx, { filename: f });
  return ctx;
}
const pcc = load(['privacy-command-center/v10/data.js', 'privacy-command-center/v10/data-life.js']).NS;

/* 1 · the Northstar subset ─────────────────────────────────────── */
function pickNS(NS) {
  const v = NS.vendors.find((x) => x.id === 'v_helphub');
  return {
    TODAY: NS.TODAY,
    consentConsumers: NS.consentConsumers,
    deletionTargets: NS.deletionTargets,
    rightsDeadlines: NS.rightsDeadlines.map(({ region, rights, days, ext }) => ({ region, rights, days, ext })),
    dp: NS.dp,
    incidents: NS.incidents.map(({ id, title, type, people, opened, status }) => ({ id, title, type, people, opened, status })),
    accessEvents: NS.accessEvents.map(({ who, what, flag }) => ({ who, what, flag })),
    datasets: NS.datasets.map((d) => ({ id: d.id, name: d.name, retention: d.retention, lastAudit: d.lastAudit || null })),
    vendors: NS.vendors.map(({ id, name, attestation, infraOnly }) => ({ id, name, attestation: attestation || null, infraOnly: !!infraOnly })),
    controls: NS.controls.map(({ id, name, level, health }) => ({ id, name, level, health })),
    vendor: { name: v.name, data: v.data, region: v.region, retention: v.retention, attestation: v.attestation, people: v.people },
    helphubSubs: v.subprocessors.map((id) => (NS.subprocessors.find((s) => s.id === id) || { name: id }).name + ((NS.subprocessors.find((s) => s.id === id) || {}).region ? ' (' + NS.subprocessors.find((s) => s.id === id).region.toUpperCase() + ')' : '')),
    persona: { name: NS.persona.name, facts: NS.persona.facts.map(({ origin, a, ds, path: p, kind, tier }) => ({ origin, a, ds, path: p, kind, tier })) },
    identifiers: NS.identifiers.map(({ id, name }) => ({ id, name })),
    assumptionTests: NS.assumptionTests,
    life: NS.life
  };
}
const NSX = pickNS(pcc);
const northstarJs = '/* GENERATED by scripts/every_arrow/build.mjs from privacy-command-center/v10/data.js — do not edit.\n' +
  ' * The subset of Northstar\'s synthetic dataset the essay reads, so both experiences share one dataset. */\n' +
  'window.EA_NS = ' + JSON.stringify(NSX) + ';\n';

/* essay-side files, with the generated NS in place */
const ctx = load([`${DIR}/data.js`, `${DIR}/model.js`, `${DIR}/trails.js`, `${DIR}/sources.js`]);
ctx.EA_NS = NSX;
vm.runInContext(fs.readFileSync(A(`${DIR}/house.js`), 'utf8'), ctx, { filename: 'house.js' });
const D = ctx.EA_DATA, M = ctx.EA_MODEL, T = ctx.EA_TRAILS, SRC = ctx.EA_SOURCES, HS = ctx.EA_HOUSE;

/* ── HTML helpers ──────────────────────────────────────────────── */
const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
/* data-h repeats the column heading on each cell, so the table can stack into cards on phones */
const plain = (h) => String(h).replace(/<[^>]+>/g, '').replace(/"/g, '&quot;');
const table = (cap, head, rows, cls = 'st-t') => `<table class="${cls}${rows.length > 9 ? ' st-t--long' : ''}"><caption>${cap}</caption><thead><tr>${head.map((h) => `<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map((r) => `<tr${r.hot ? ' class="hot"' : ''}>${r.cells.map((c, i) => (i === 0 ? `<th scope="row">${c}</th>` : `<td data-h="${plain(head[i])}">${c}</td>`)).join('')}</tr>`).join('')}</tbody></table>`;
const cite = (k) => { const s = SRC[k]; if (!s) { problems.push(`sources.js: unknown source key "${k}" used by a figure`); return ''; } return s.u ? ` <a class="src" data-src="${k}" href="${esc(s.u)}">${esc(label(k))}</a>` : ` <span class="src" data-src="${k}">${esc(label(k))}</span>`; };
function label(k) {
  const m = { carlini21: 'Carlini et al., 2021', carlini23: 'Carlini et al., 2023', nasr23: 'Nasr et al., 2023', shokri17: 'Shokri et al., 2017', morris23: 'Morris et al., 2023', bourtoule21: 'Bourtoule et al., 2021', cooper24: 'Cooper et al., 2024', owasp: 'OWASP LLM Top 10', gdpr: 'GDPR', aiact: 'AI Act' };
  return m[k] || k;
}
const fmtS = M.fmtSecs;

/* 2 · static renderers ─────────────────────────────────────────── */
const R = {};
R.person = () => {
  const modes = D.person.modes;
  const res = modes.map((m) => M.person(D.person, m.id));
  return table('Which inferences about Dana exist under each join policy', ['Inference (what it needs)'].concat(modes.map((m) => esc(m.t))),
    D.person.inf.map((f, i) => ({ cells: [`${esc(f.v)} <small>(${esc(f.src)})</small>`].concat(res.map((r) => (r[i].on ? '<b>Yes</b>' : `No &mdash; ${esc(r[i].why)}`))) })));
};
R.inventory = () => {
  const idn = Object.fromEntries(NSX.identifiers.map((i) => [i.id, i.name]));
  return table('What Northstar holds about Dana, by origin', ['What', 'Origin', 'Tier', 'Kind', 'Joins needed to know it'],
    NSX.persona.facts.map((f) => ({ hot: f.kind === 'INFERENCE' && f.tier >= 4, cells: [esc(f.a), esc(f.origin || ''), 'T' + f.tier, esc(f.kind.toLowerCase()), f.path.length ? esc(f.path.map((p) => idn[p] || p).join(' → ')) : '—'] })));
};
R.crowd = () => {
  const C = M.crowd();
  const steps = [[{}, 'Nothing'], [{ zip: 1 }, 'ZIP code'], [{ zip: 1, sex: 1 }, '+ sex'], [{ zip: 1, sex: 1, year: 1 }, '+ birth year'], [{ zip: 1, sex: 1, year: 1, day: 1 }, '+ birthday']];
  return table('How many of 1,000 synthetic people match what you know', ['What you know', 'People who match'], steps.map(([on, t]) => { const n = M.crowdMatch(C, on); return { hot: n === 1, cells: [t, n === 1 ? '<b>1 — the target, identified</b>' : n.toLocaleString('en-US')] }; }));
};
R.spectrum = () => table('Identifier classes, from links everything to links nothing', ['Class', 'Example', 'Links a person across', 'Use when'], D.spectrum.map((s) => ({ cells: s.map(esc) })));
R.wrong = () => {
  const W = D.wrong, gt = Object.fromEntries(W.guards.map((g) => [g.id, g.t]));
  return table('The same wrong merge, used five ways', ['Use', 'Harm if wrong', 'What happens to Dana', 'Safeguards this use needs'],
    W.uses.map((u) => ({ hot: u.sev >= 3, cells: [esc(u.t), W.sevWords[u.sev], esc(u.what), u.need.length ? u.need.map((n) => esc(gt[n])).join('; ') : 'A correction path, as courtesy'] }))) +
    `<p class="st-note">With every needed safeguard in place, the harm of each high-stakes use falls to: ${W.uses.map((u) => { const all = Object.fromEntries(W.guards.map((g) => [g.id, true])); return esc(u.t) + ' — ' + W.sevWords[M.wrong(W, u.id, all).residual].toLowerCase(); }).join('; ')}. Illustrative ranking.</p>`;
};
R.eight = () => table('The eight review questions, applied to Dana’s reorder reminder', ['Question', 'Ask', 'Applied to the reminder', 'Red flag'], D.eight.map((q, i) => ({ cells: [`${i + 1}. ${q[0]}`, esc(q[1]), esc(q[2]), esc(q[3])] })));
R.lifecycle = () => table('One question and one control per lifecycle stage', ['Stage', 'Question', 'Control'], D.lifecycle.map((l) => ({ cells: [l[0], esc(l[1]), esc(l[2])] })));
R.flow = () => table('Northstar’s order path: every arrow as a privacy object (orange = leaves the boundary or changes purpose)', ['Arrow', 'Fields', 'Purpose', 'Retention', 'Owner', 'Control', 'The decision'],
  D.flows.map((e) => ({ hot: !!e.hot, cells: [esc(e.t) + (e.badge ? ` <span class="tag tag--hot">${e.badge}</span>` : ''), esc(e.d.Fields), esc(e.d.Purpose), esc(e.d.Retention), esc(e.d.Owner), esc(e.d.Control), esc(e.dec)] })), 'st-t st-t--wide');
R.purpose = () => table('Six requests to read phone_number, checked at the moment of use', ['Requester', 'Wants to', 'Verdict', 'Why'], D.purpose.map((u) => ({ hot: !u[2], cells: [esc(u[0]), esc(u[1]), u[2] ? 'Allowed' : '<b>Denied</b>', esc(u[3])] })));
R.harm = () => table('From a technical issue to a human consequence', ['Technical issue', 'Privacy harm', 'Human consequence', 'Control'], D.issues.map((it) => ({ cells: [esc(it[0]), esc(it[1]), esc(it[2]), esc(it[4])] })));
R.tradeoff = () => D.tradeoffs.map((t) => table(`${esc(t.t)}: ${esc(t.q)}`, ['', ...t.alts.map((a, i) => `Option ${'ABC'[i]}: ${esc(a.t)}${i === t.rec ? ' (reviewer’s pick)' : ''}`)],
  [['Pros', 'pros'], ['Cons', 'cons'], ['Utility cost', 'utility'], ['Privacy benefit', 'benefit'], ['Trust assumption', 'trust'], ['Residual risk', 'residual']].map(([h, k]) => ({ cells: [h, ...t.alts.map((a) => esc(a[k]))] })), 'st-t st-t--wide') +
  `<p class="st-note"><b>Decision record.</b> Owner: ${esc(t.owner)} · Reviewer: ${esc(t.reviewer)} · Approver: ${esc(t.approver)} · Expires: ${esc(t.expiry)} · Evidence: ${t.evidence.map(esc).join('; ')}.</p>`).join('');
R.ladder = () => table('Six rungs between a promise and a machine that refuses', ['Rung', 'Enforced by', 'Fails when', 'Evidence it leaves'], D.ladder.map((r, i) => ({ cells: [`${i} · ${r.t} <small>(${r.who})</small>`, esc(r.by), esc(r.fails), esc(r.evidence)] })));
R.consent = () => {
  const a = M.consent(NSX, false), b = M.consent(NSX, true);
  return table('Northstar’s consent consumers (synthetic latencies)', ['Consumer', 'How it learns', 'P50', 'P95', 'P99'],
    a.rows.map((r) => ({ hot: r.never, cells: [esc(r.name), esc(r.mode), r.never ? '<b>never</b>' : fmtS(r.p50), r.never ? '<b>never</b>' : fmtS(r.p95), r.never ? '<b>never</b>' : fmtS(r.p99)] }))) +
    table('End-to-end: time until the last consumer honours a revocation', ['', 'P50', 'P95', 'P99'], [
      { hot: true, cells: [`As it is (${a.never} consumers never re-check; ${M.n(a.stale)} people’s choices ignored)`, 'never', 'never', 'never'] },
      { cells: ['With the silent consumers wired to read-time checks', fmtS(b.p50), fmtS(b.p95), fmtS(b.p99)] }]);
};
R.rights = () => table('Six rights, and the systems each must reach (simplified; not legal advice)', ['Right', 'Law', 'Systems it must reach', 'How it fails as a ticket in a queue', 'Proof it worked'],
  D.rights.map((r) => ({ cells: [esc(r.t), esc(r.law), r.systems.map((s) => esc(s[0])).join('; '), esc(r.systems[0][2]) + (r.systems[1] ? '; ' + esc(r.systems[1][2]) : ''), esc(r.proof)] })), 'st-t st-t--wide');
R.retention = () => table('Keeping raw events longer (illustrative model: usefulness halves about every two weeks)', ['Keep raw events', 'Value retained', 'Rows at risk on any day', 'Exposure vs two years'],
  [7, 30, 90, 180, 365, 730].map((d) => { const s = M.retention(d); return { hot: d >= 365, cells: [`${d} days`, s.u + '%', s.rows, s.x + '%'] }; }));
R.forget = () => table('Nine kinds of store a deletion must reach', ['Store', 'How deletion reaches it'], D.forget.map((f) => ({ cells: [esc(f[0]), esc(f[1])] }))) +
  `<p class="st-note">At Northstar a Forget-Me request must reach ${NSX.deletionTargets.length} systems: ${['verified', 'failed', 'waiting', 'unknown'].map((k) => NSX.deletionTargets.filter((t) => t[3] === k).length + ' ' + k).join(', ')}.</p>`;
R.vendorfacts = () => { const v = NSX.vendor; return `<dl class="vd-facts"><dt>Vendor</dt><dd>${esc(v.name)}</dd><dt>Data</dt><dd>${esc(v.data.join(', '))}</dd><dt>Region</dt><dd>${esc(v.region.toUpperCase())}</dd><dt>Retention</dt><dd>${v.retention.contract} days in the contract · <b class="hot">${v.retention.actual} observed</b></dd><dt>Subprocessors</dt><dd>${esc(NSX.helphubSubs.join(', '))}</dd><dt>Deletion attestation</dt><dd>${v.attestation ? esc(v.attestation) : '<b class="unk">none on file</b>'}</dd><dt>People</dt><dd>${M.n(v.people)}</dd></dl>`; };
R.vendor = () => table('One vendor, seven stages', ['Stage', 'Question', 'Northstar today', 'With the control', 'Evidence'], D.vendor.map((v, i) => ({ cells: [`${i + 1}. ${v.t}`, esc(v.q), esc(v.now), esc(v.with), esc(v.ev)] })), 'st-t st-t--wide');
R.aimech = () => table('Thirteen parts of an AI system: mechanism, claims and controls', ['Part', 'What actually happens', 'What you can claim', 'What you can’t', 'Control', 'Evidence'],
  D.aiMech.map((r) => ({ cells: [esc(r[0]), esc(r[1]) + r[6].map(cite).join(''), esc(r[2]), esc(r[3]), esc(r[4]), esc(r[5])] })), 'st-t st-t--wide');
R.worst = () => table('One stolen server, five designs (illustrative index; compares designs, does not predict harm)', ['Design', ...D.designFactors, 'Damage index'],
  D.designs.map((d) => { const s = D.designIndex(d); return { hot: s >= 50, cells: [esc(d.n), ...d.f.map((f) => esc(f[1])), s === 0 ? '0' : s >= 10 ? String(Math.round(s)) : s >= 0.1 ? s.toFixed(1) : '&lt;0.1'] }; }));
R.pets = () => table('From the threat to the technology — and its price', ['Threat', 'Answer', 'Family', 'Utility cost', 'Trust assumption', 'Residual risk'], D.petThreats.map((t) => ({ cells: [esc(t[0]), esc(t[2]), t[3], esc(t[4]), esc(t[5]), esc(t[6])] })), 'st-t st-t--wide');
R.dp = () => {
  const total = NSX.dp.total, rel = NSX.dp.releases.map((r) => r.eps);
  const rows = NSX.dp.releases.map((r) => ({ cells: [r.q, esc(r.desc), r.eps.toFixed(1), 'Answered'] }));
  let spent = rel.slice();
  [[`Q${rel.length + 1}`, 'Weekly reorders by ZIP', 1.0], [`Q${rel.length + 2}`, 'The next analyst question', 1.0]].forEach(([q, d, e]) => {
    const r = M.ledger(total, spent, e);
    rows.push({ hot: !r.ok, cells: [q, esc(d), e.toFixed(1), r.ok ? `Answered — ${(r.rem - e).toFixed(1)} left` : `<b>Refused</b> — ${r.spent.toFixed(1)} + ${e.toFixed(1)} &gt; ${total.toFixed(1)}`] });
    if (r.ok) spent.push(e);
  });
  return table(`The privacy-loss ledger: budget ε = ${total} ${esc(NSX.dp.unit)}`, ['Query', 'What', 'ε', 'Outcome'], rows);
};
R.change = () => {
  const a = M.change(D, D.changes.length, false), b = M.change(D, D.changes.length, true);
  return table('Six changes to the reviewed reorder reminder', ['Change', 'What', 'Breaks condition', 'Without a contract', 'With a contract'],
    D.changes.map((c) => ({ hot: c.breaks >= 0, cells: [esc(c.k), esc(c.t), c.breaks >= 0 ? String(c.breaks + 1) : '—', c.breaks >= 0 ? 'Ships silently' : 'Harmless', c.rule ? 'Blocked; review reopened — ' + esc(c.rule) : 'No alert (correctly)'] }))) +
    `<p class="st-note">After all six: without a contract the review still says <b>${a.status}</b> while ${a.held} of ${D.verdict.length} conditions hold; with a contract it is <b>${b.status}</b>, ${b.detected} changes were caught and ${b.held} of ${D.verdict.length} conditions hold.</p>`;
};
R.slos = () => `<div class="slos">${M.slos(NSX).map((s) => `<div class="slo ${s.status}"><p class="slo-t">${esc(s.t)}</p><p class="slo-v">${esc(s.v)}</p><p class="slo-u">${esc(s.unit)}</p><p class="slo-target"><span>Target</span>${esc(s.target)}</p><p class="slo-rule"><span>Rule</span>${esc(s.rule)} ${esc(s.detail)}</p><p class="slo-st">${s.status === 'ok' ? 'Meeting target' : 'Breaching target'} · <a href="/privacy-command-center/v10/#/${s.route}">Command Center</a></p></div>`).join('')}</div>`;
R.observe = () => { const all = Object.fromEntries(D.monitors.map((m) => [m.id, true])); const res = M.observe(D, NSX, all);
  return table('Which monitor would have caught each of Northstar’s recorded incidents', ['Incident', 'People', 'Caught by'], res.map((r) => ({ cells: [`${esc(r.id)} · ${esc(r.title)}`, M.n(r.people), r.by ? esc(r.by) : '—'] }))) +
    `<p class="st-note">Uptime and error-rate monitoring catches none of them. With a budget of ${D.monitorBudget} monitors, choose from the incidents you have had and the assumptions you have not yet tested.</p>`; };
R.assumptions = () => { const trails = { 'cc-optout': 'optout', 'cc-debug': 'debug', 'cc-csv': 'csv', 'cc-family': 'family', 'cc-forget': 'forget' };
  return table('Northstar’s assumption tests, latest result', ['Assumption', 'Test', 'Result', 'Where', 'Replay'], NSX.assumptionTests.map((t) => ({ hot: t.result === 'fail', cells: [esc(t.k), esc(t.q), t.result === 'fail' ? '<b>Fail</b>' : t.result === 'unknown' ? '<b class="unk">Unknown</b>' : 'Pass', esc(t.where), t.essay ? `<a href="#${t.essay}">${t.essay.replace('cc-', '')}</a>` : '—'] }))); };
R.incident = () => table('Seven decisions after the alert (the Pulse SDK beacon joined to ad IDs)', ['Step', 'When', 'The tempting move', 'The move that holds'],
  D.incident.map((s, i) => ({ cells: [`${i + 1}. ${esc(s.t)}`, esc(s.when), `<b>${esc(s.bad[0])}.</b> ${esc(s.bad[1])}`, `<b>${esc(s.good[0])}.</b> ${esc(s.good[1])}`] })), 'st-t st-t--wide') +
  (() => { const bad = M.incident(D.incident, D.incident.map(() => false)), good = M.incident(D.incident, D.incident.map(() => true));
    return `<p class="st-note">Every tempting move: ${bad.runDays} extra days running, ${bad.copies} copies left, evidence ${bad.evidence}, notification decision ${bad.decided}, no guard. Every move that holds: ${good.runDays} extra days, ${good.copies} copies left, evidence ${good.evidence}, decision ${good.decided}, a guard in place. Simplified model.</p>`; })();
R.kitreview = () => table('The review on one page', ['#', 'Question', 'Red flag', 'Evidence to ask for'], D.eight.map((q, i) => ({ cells: [`${i + 1}. ${q[0]}`, esc(q[1]), esc(q[3]), esc(D.eightEvidence[i])] })));
R.pccmap = () => table('Concepts in this guide, and where to see them run', ['Scene', 'Command Center page', 'What you will see'], D.pccMap.map((m) => ({ cells: [`<a href="#${m[0]}">${esc(m[1])}</a>`, `<a href="/privacy-command-center/v10/#/${m[2]}">${esc(m[3])}</a>`, esc(m[4])] })));
for (const id of Object.keys(T)) if (id[0] !== '_') R['trail-' + id] = () => T._static(id);
for (const id of Object.keys(HS.statics)) R[id] = () => HS.statics[id]();

/* Sources: grouped, in registry order; only the ones cited. */
function sourcesHtml(used) {
  const groups = {};
  for (const [k, s] of Object.entries(SRC)) { if (!used.has(k)) continue; (groups[s.g] = groups[s.g] || []).push([k, s]); }
  return Object.entries(groups).map(([g, list]) => `<h3>${esc(g)}</h3><ol class="src-list">${list.map(([k, s]) => `<li id="src-${k}">${esc(s.c)}${s.u ? ` <a href="${esc(s.u)}">${esc(s.u.replace(/^https?:\/\//, '').replace(/\/$/, ''))}</a>` : ''}</li>`).join('')}</ol>`).join('');
}

/* ── apply ─────────────────────────────────────────────────────── */
const original = fs.readFileSync(A(ESSAY), 'utf8');
let html = original;
const STATIC_RE = /(<div class="([^"]*)" data-static="([\w-]+)"[^>]*>)([\s\S]*?)(<\/div><!-- \/static:\3 -->)/g;
const seen = new Set();
html = html.replace(STATIC_RE, (m, open, cls, name, body, close) => {
  if (name === 'sources') return m; // filled after citations are collected
  seen.add(name);
  if (!R[name]) { problems.push(`${ESSAY}: no static renderer for data-static="${name}"`); return m; }
  return open + R[name]() + close;
});
html = html.replace(/(<div data-static="sources">)([\s\S]*?)(<\/div><!-- \/static:sources -->)/, (m, o) => o + '__SOURCES__' + '</div><!-- /static:sources -->');
for (const name of Object.keys(R)) if (!seen.has(name) && !name.startsWith('trail-')) problems.push(`static renderer "${name}" has no data-static slot in the essay`);
for (const id of Object.keys(T)) if (id[0] !== '_' && !seen.has('trail-' + id)) problems.push(`trail "${id}" has no static slot (data-static="trail-${id}")`);

/* 3 · citations */
const used = new Set();
for (const m of html.matchAll(/data-src="([\w-]+)"/g)) { used.add(m[1]); if (!SRC[m[1]]) problems.push(`${ESSAY}: citation data-src="${m[1]}" is not in sources.js`); }
for (const k of Object.keys(SRC)) if (!used.has(k)) problems.push(`sources.js: "${k}" is never cited in the essay`);
/* a citation's link must match its registry URL */
for (const m of html.matchAll(/<a class="src" data-src="([\w-]+)" href="([^"]+)"/g)) {
  const s = SRC[m[1]]; if (s && s.u && m[2].replace(/&amp;/g, '&') !== s.u) problems.push(`${ESSAY}: citation "${m[1]}" links to ${m[2]}, registry says ${s.u}`);
}
html = html.replace('__SOURCES__', sourcesHtml(used));

/* 4 · counts and reading time */
function words(s) { return (s.replace(/&[a-z#0-9]+;/gi, ' ').match(/[A-Za-z0-9À-ɏ’'-]+/g) || []).length; }
/* A tiny tokenizer: walk tags, keep a stack, count text by layer. */
function countWords(src) {
  const main = src.slice(src.indexOf('<main id="main">'), src.indexOf('</main>'));
  const VOID = new Set(['br', 'img', 'input', 'meta', 'link', 'hr', 'source', 'wbr', 'col']);
  const SKIP = new Set(['script', 'style', 'svg', 'canvas', 'button']);
  const stack = [];
  let full = 0, exec = 0;
  const re = /<(\/?)([a-zA-Z][\w-]*)([^>]*?)(\/?)>|<!--[\s\S]*?-->|([^<]+)/g;
  let m;
  while ((m = re.exec(main))) {
    if (m[5] !== undefined) {
      if (stack.some((f) => f.skip)) continue;
      const w = words(m[5]);
      if (!stack.some((f) => f.noFull)) full += w;
      if (stack.some((f) => f.x) && !stack.some((f) => f.noExec)) exec += w;
      continue;
    }
    if (!m[2]) continue;
    const tag = m[2].toLowerCase();
    if (m[1]) { for (let i = stack.length - 1; i >= 0; i--) if (stack[i].tag === tag) { stack.length = i; break; } continue; }
    if (VOID.has(tag) || m[4]) continue;
    const cls = (/class="([^"]*)"/.exec(m[3]) || [, ''])[1].split(/\s+/);
    const has = (c) => cls.includes(c);
    const f = { tag,
      skip: SKIP.has(tag),
      /* the full path reads prose, briefs and figure lessons; not collapsed notes, not fallbacks shown only without JS */
      noFull: tag === 'details' || (has('fig-static') && !has('fig-static--always')) || has('fig-how') || has('fig-foot') || has('fig-live'),
      x: has('x'),
      /* the executive path reads briefs, chapter arcs and evidence, the thesis, and the six questions — not the reference tables */
      noExec: has('fig-static') || tag === 'details' || has('kit-review') || tag === 'table' };
    if (has('kit-sec') && !/id="north"/.test(m[3])) f.noExec = true;
    stack.push(f);
  }
  return { full, exec };
}
const w = countWords(html);
const nFigs = (html.match(/<figure class="fig[^"]*" id="fig-/g) || []).length;
const nScenes = (html.match(/<p class="eyebrow"><span class="num">\d+<\/span>/g) || []).length;
const nChapters = (html.match(/<div class="chapter[^"]*" id="/g) || []).length;
const readFull = Math.round(w.full / WPM + nFigs * FIG_SECONDS / 60);
const readExec = Math.max(1, Math.round(w.exec / WPM));
const dt = NSX.deletionTargets;
const pdfMeta = fs.existsSync(A(`${DIR}/edition-3.pdf.json`)) ? JSON.parse(fs.readFileSync(A(`${DIR}/edition-3.pdf.json`), 'utf8')) : { pages: 0 };
const STAMP = {
  chapters: nChapters, scenes: nScenes, figures: nFigs,
  'read.full': readFull, 'read.exec': readExec,
  edition: '3.0', revised: '29 September 2026',
  'pdf.pages': pdfMeta.pages,
  'ns.deletion.total': dt.length,
  'ns.deletion.verified': dt.filter((t) => t[3] === 'verified').length,
  'ns.consent.consumers': NSX.consentConsumers.length,
  'ns.retention.violations': NSX.datasets.filter((x) => x.retention && x.retention.required > 0 && x.retention.actual > x.retention.required).length,
  'ns.dp.total': NSX.dp.total
};
html = html.replace(/(<span data-ea="([\w.]+)">)([^<]*)(<\/span>)/g, (m, o, k, v, c) => {
  if (!(k in STAMP)) { problems.push(`${ESSAY}: data-ea="${k}" has no value`); return m; }
  return o + STAMP[k] + c;
});
html = html.replace(/"timeRequired": "PT\d+M"/, `"timeRequired": "PT${readFull}M"`);

/* 5 · fingerprint the essay's own assets */
html = html.replace(/((?:href|src)="\/articles\/every-arrow\/([\w.-]+\.(?:css|js)))(?:\?v=[0-9a-f]+)?"/g, (m, pre, file) => {
  const p = A(`${DIR}/${file}`);
  const content = file === 'northstar.js' ? northstarJs : fs.existsSync(p) ? fs.readFileSync(p) : '';
  return `${pre}?v=${crypto.createHash('sha256').update(content).digest('hex').slice(0, 10)}"`;
});

/* Site-wide stamps (article_metadata.json, the /articles/ card, the homepage feature) belong to
 * the live edition and are written by edition4.mjs. */
const other = [];

/* the printed running header carries the edition and date: keep essay.css in step with the stamps */
{ const css = fs.readFileSync(A(`${DIR}/essay.css`), 'utf8');
  if (!css.includes(`Edition ${STAMP.edition} \\00B7 ${STAMP.revised}`)) problems.push(`${DIR}/essay.css: the @page header must read “Edition ${STAMP.edition} · ${STAMP.revised}”`); }

/* 6 · PDF freshness */
function sourceHash(h) {
  const norm = h.replace(/(<span data-ea="pdf\.pages">)\d+(<\/span>)/g, '$1#$2');
  const css = fs.readFileSync(A(`${DIR}/essay.css`));
  return crypto.createHash('sha256').update(norm).update(css).digest('hex').slice(0, 16);
}

/* 7 · the downloadable field kit, from the same sources as the page */
function fieldKit(h) {
  const text = (x) => x.replace(/<[^>]+>/g, '').replace(/&rsquo;/g, '’').replace(/&ldquo;/g, '“').replace(/&rdquo;/g, '”').replace(/&mdash;/g, '—').replace(/&rarr;/g, '→').replace(/&amp;/g, '&').replace(/&[a-z#0-9]+;/g, ' ').replace(/\s+/g, ' ').trim();
  const six = [...h.slice(h.indexOf('id="north-list"')).split('</ol>')[0].matchAll(/<li[^>]*>([\s\S]*?)<\/li>/g)].map((m) => text(m[1]));
  const ck = h.slice(h.indexOf('id="kit-checklist"'), h.indexOf('class="kit-dl"'));
  const lists = [...ck.matchAll(/<h3>([^<]+)<\/h3><ul class="check">([\s\S]*?)<\/ul>/g)].map((m) => `### ${text(m[1])}\n\n` + [...m[2].matchAll(/<li>([\s\S]*?)<\/li>/g)].map((x) => `- [ ] ${text(x[1])}`).join('\n'));
  return `# Every Arrow Is a Decision — field kit\n\nFrom *Every Arrow Is a Decision: A Visual Field Guide to Privacy Engineering*, edition ${STAMP.edition} (revised ${STAMP.revised}), by Paddy Iyer.\nhttps://paddyspeaks.com/articles/every-arrow/edition-3.html\n\n` +
    `> A privacy policy is a promise written in human language. Privacy engineering is the machinery that makes it remain true after the data starts moving.\n\n` +
    `## The six questions, for every piece of personal data\n\n${six.map((q, i) => `${i + 1}. ${q}`).join('\n')}\n\nIf you cannot answer, the uncertainty is the finding.\n\n` +
    `## The review on one page\n\n| # | Question | Red flag | Evidence to ask for |\n|---|---|---|---|\n${D.eight.map((q, i) => `| ${i + 1}. ${q[0]} | ${q[1]} | ${q[3].replace(/\|/g, '/')} | ${D.eightEvidence[i]} |`).join('\n')}\n\n` +
    `Tier data by what it reveals, not by column type: T0 public · T1 internal · T2 personal · T3 sensitive · T4 special.\n\n` +
    `## Every decision record names\n\nOwner · Reviewer · Approver · Expiry (a date or a trigger) · Evidence (what shows, on a schedule, that each condition holds).\n\n` +
    `## Checklist\n\n${lists.join('\n\n')}\n\n` +
    `## Fourteen questions for every arrow in a connected life\n\n${NSX.life.questions.map((q, i) => `${i + 1}. ${q[1]}`).join('\n')}\n\nAn arrow nobody can answer these for is a finding.\n\n` +
    `## The engineering answers\n\n| Problem | Engineering solution |\n|---|---|\n${NSX.life.solutions.map((x) => `| ${x.problem} | ${x.parts.join('; ')} |`).join('\n')}\n\n` +
    `## In the Privacy Command Center\n\n${D.pccMap.map((m) => `- ${m[1]} → [${m[3]}](https://paddyspeaks.com/privacy-command-center/v10/#/${m[2]}) — ${m[4]}`).join('\n')}\n\n` +
    `Northstar and Dana are fictional; Northstar's data is synthetic. Nothing here is legal advice.\n`;
}

/* ── write or check ────────────────────────────────────────────── */
const outputs = [[`${DIR}/northstar.js`, northstarJs], [ESSAY, html], [`${DIR}/field-kit.md`, fieldKit(html)], ...other.map(([f, fn]) => [f, fn()])];
if (CHECK) {
  for (const [f, content] of outputs) {
    const cur = fs.existsSync(A(f)) ? fs.readFileSync(A(f), 'utf8') : '';
    if (cur !== content) problems.push(`${f} is stale — run: node scripts/every_arrow/build.mjs`);
  }
  if (!pdfMeta.pages) problems.push(`${DIR}/pdf.json missing — run the build with --pdf`);
  else if (pdfMeta.source !== sourceHash(html)) problems.push(`${DIR}/edition-3.pdf is older than the essay — run: EA_DEPS=… node scripts/every_arrow/build.mjs --pdf`);
} else {
  for (const [f, content] of outputs) {
    const cur = fs.existsSync(A(f)) ? fs.readFileSync(A(f), 'utf8') : '';
    if (cur !== content) { fs.writeFileSync(A(f), content); console.log('  wrote', f); }
  }
  if (args.has('--pdf')) {
    const { renderPdf } = await import('./pdf.mjs');
    let pages = await renderPdf(ROOT, A(`${DIR}/edition-3.pdf`), '/' + ESSAY + '?path=full');
    if (pages !== pdfMeta.pages) {
      /* the page count is printed in the essay: stamp it and render once more */
      const h2 = fs.readFileSync(A(ESSAY), 'utf8').replace(/(<span data-ea="pdf\.pages">)\d+(<\/span>)/g, `$1${pages}$2`);
      fs.writeFileSync(A(ESSAY), h2);
      pages = await renderPdf(ROOT, A(`${DIR}/edition-3.pdf`), '/' + ESSAY + '?path=full');
    }
    const final = fs.readFileSync(A(ESSAY), 'utf8');
    fs.writeFileSync(A(`${DIR}/edition-3.pdf.json`), JSON.stringify({ pages, source: sourceHash(final), note: 'Written by scripts/every_arrow/build.mjs --pdf. source = hash of the essay HTML (page count masked) + essay.css.' }, null, 2) + '\n');
    console.log(`  rendered PDF: ${pages} pages`);
  }
}
console.log(`  edition 3 (archived): ${nChapters} chapters · ${nScenes} scenes · ${nFigs} figures · full ${readFull} min (${w.full} words) · executive ${readExec} min (${w.exec} words)`);

/* edition 4, the live essay */
{ const { buildEdition4 } = await import('./edition4.mjs');
  const e4 = await buildEdition4({ check: CHECK, pdf: args.has('--pdf') });
  console.log(e4.log.join('\n')); problems.push(...e4.problems); }
if (problems.length) { console.error(problems.map((p) => '✗ ' + p).join('\n')); process.exit(1); }
console.log(CHECK ? '✓ every-arrow: up to date' : '✓ every-arrow: built');
