/* Every Arrow Is a Decision, edition 4 — the lens switches.
 *
 * Everything is already in the page (generated by scripts/every_arrow/edition4.mjs
 * from compare.js), so without JavaScript, and in print, every lens shows. This file
 * only chooses which lens is visible:
 *   - the whole picture (#fig-overview): one lens at a time, Security first;
 *   - each product (#fig-signin …): all four lenses, or one.
 * A radiogroup per figure (arrow keys move, Home/End jump), a spoken reading of what
 * is now shown, and ?f=<figure>:<lens> so every view is a link. Nothing is stored. */
(function () {
  'use strict';
  var NAMES = { all: 'All four lenses', sec: 'Security', pri: 'Privacy', qa: 'QA', gov: 'Data governance' };
  var KIND = [['doc', 'documented', 'documented'], ['set', 'setting', 'settings'], ['lim', 'limit', 'limits'], ['test', 'test', 'tests']];
  var figs = {};

  function counts(fig, overview) {
    var n = { doc: 0, set: 0, lim: 0, test: 0 };
    var els = fig.querySelectorAll(overview ? '.ov-set:not([hidden]) .h .k' : 'tbody tr:not([hidden]) .it');
    [].forEach.call(els, function (el) { n[overview ? kindOf(el) : el.getAttribute('data-k')]++; });
    return KIND.map(function (k) { return n[k[0]] + ' ' + (n[k[0]] === 1 ? k[1] : k[2]); }).join(', ');
  }
  function kindOf(tag) { return tag.classList.contains('k--set') ? 'set' : tag.classList.contains('k--lim') ? 'lim' : tag.classList.contains('k--test') ? 'test' : 'doc'; }
  function companies(fig) {
    var th = fig.querySelectorAll('thead th[scope="col"]');
    var names = [].slice.call(th, 1).map(function (x) { return x.firstChild.textContent.trim(); });
    return names.length > 1 ? names.slice(0, -1).join(', ') + ' and ' + names[names.length - 1] : names.join('');
  }

  function apply(id, lens, fromUser) {
    var f = figs[id]; if (!f || !f.opts[lens]) return;
    f.lens = lens;
    f.buttons.forEach(function (b) { var on = b.getAttribute('data-l') === lens; b.setAttribute('aria-checked', on); b.tabIndex = on ? 0 : -1; });
    var read = f.fig.querySelector('.cmp-read');
    if (id === 'overview') {
      [].forEach.call(f.fig.querySelectorAll('.ov-set'), function (s) { s.hidden = s.getAttribute('data-l') !== lens; });
      read.innerHTML = '<b>' + NAMES[lens] + '</b> across ' + f.fig.querySelectorAll('.ov-set:not([hidden]) tbody tr').length + ' products: ' + counts(f.fig, true) + '.';
    } else {
      [].forEach.call(f.fig.querySelectorAll('tbody tr[data-l]'), function (r) { r.hidden = lens !== 'all' && r.getAttribute('data-l') !== lens; });
      read.innerHTML = '<b>' + NAMES[lens] + '</b> for ' + companies(f.fig) + ': ' + counts(f.fig, false) + '.';
    }
    if (fromUser && window.history && history.replaceState) {
      try {
        var rest = location.search.replace(/^\?/, '').split('&').filter(function (kv) { return kv && !/^f=/.test(kv); });
        if (lens !== f.first) rest.push('f=' + id + ':' + lens);   /* written by hand: URLSearchParams would encode the colon */
        var sec = f.fig.closest('section');
        history.replaceState(null, '', location.pathname + (rest.length ? '?' + rest.join('&') : '') + (sec ? '#' + sec.id : location.hash));
      } catch (e) { /* a view that cannot be linked still works */ }
    }
  }

  [].forEach.call(document.querySelectorAll('.cmp[data-fig]'), function (fig) {
    var id = fig.getAttribute('data-fig'), ctl = fig.previousElementSibling;
    if (!ctl || !ctl.classList.contains('cmp-ctl')) return;
    var buttons = [].slice.call(ctl.querySelectorAll('[role="radio"]'));
    var opts = {}; buttons.forEach(function (b) { opts[b.getAttribute('data-l')] = true; });
    var first = (buttons.filter(function (b) { return b.getAttribute('aria-checked') === 'true'; })[0] || buttons[0]).getAttribute('data-l');
    figs[id] = { fig: fig, buttons: buttons, opts: opts, first: first, lens: first };
    ctl.hidden = false;
    buttons.forEach(function (b, i) {
      b.addEventListener('click', function () { apply(id, b.getAttribute('data-l'), true); });
      b.addEventListener('keydown', function (e) {
        var j = { ArrowRight: i + 1, ArrowDown: i + 1, ArrowLeft: i - 1, ArrowUp: i - 1, Home: 0, End: buttons.length - 1 }[e.key];
        if (j === undefined) return;
        e.preventDefault();
        j = (j + buttons.length) % buttons.length;
        apply(id, buttons[j].getAttribute('data-l'), true);
        buttons[j].focus();
      });
    });
    apply(id, first, false);
  });

  /* ?f=<figure>:<lens> opens a figure on that lens */
  var m = /[?&]f=([\w-]+):([\w-]+)/.exec(location.search);
  if (m && figs[m[1]]) apply(m[1], m[2], false);
})();
