"""Derive data/site-registry.json from the content itself.

The registry is the ONE place a public statistic comes from. Nothing in here
is typed by hand: every number is counted from the files that hold the
content. The hand-authored part (what exists and where) lives in
data/platform/catalog.json; this module only counts.

Live JobSignal numbers are deliberately NOT here. They change every four hours
and are read at runtime from jobs/data/stats.json, so a registry snapshot of
them would be stale by design.
"""
from __future__ import annotations

import re
from collections import Counter

from .common import ROOT, read_json

CATALOG = "data/platform/catalog.json"
REGISTRY = "data/site-registry.json"

# Skill Check headline sections, mirrored from interview/scripts/update_counts.py
# (the evaluate page's "N-Question Bank" is the sum of exactly these pools).
SKILL_CHECK_SECTIONS = {
    "sql": "sql", "python": "python", "design": "design",
    "topics2026": "hot-topics-2026", "ai": "ai",
    "communication": "communication", "dashboarding": "dashboarding",
}

DECK_RE = re.compile(r'<a href="([^"]+)" class="deck-card[^"]*" data-category="([a-z]+)"')


def homepage_deck() -> list[tuple[str, str]]:
    """(href, category) for every archive card on the hand-crafted homepage."""
    return DECK_RE.findall((ROOT / "index.html").read_text(encoding="utf-8"))


def article_counts(catalog) -> dict:
    meta = read_json("article_metadata.json")
    cats = [c["id"] for c in catalog["article_categories"]]
    by = Counter(m["category"] for m in meta)
    return {
        "total": len(meta),
        "by_category": {c: by.get(c, 0) for c in cats},
        "latest": max(m["date"] for m in meta)[:10],
        "earliest": min(m["date"] for m in meta)[:10],
    }


def deck_counts(catalog) -> dict:
    deck = homepage_deck()
    cats = [c["id"] for c in catalog["article_categories"]]
    by = Counter(c for _, c in deck)
    return {
        "total": len(deck),
        "articles": sum(1 for h, _ in deck if h.startswith("articles/")),
        "by_category": {c: by.get(c, 0) for c in cats},
    }


def interview_counts(catalog) -> dict:
    qs = read_json("interview/data/questions.json")
    langs = Counter(q["language"] for q in qs)
    companies = read_json("interview/data/companies.json")

    pools = {}
    for key, stem in SKILL_CHECK_SECTIONS.items():
        p = ROOT / "interview.app" / "evaluate" / "data" / f"{stem}.json"
        if p.exists():
            pools[key] = len(read_json(p.relative_to(ROOT)).get("questions", []))

    dm = (ROOT / "interview.app/design/data-modeling.html").read_text(encoding="utf-8")
    scenarios = sorted(set(re.findall(r'id="h-sc-([a-z0-9-]+)"', dm)))
    problems = sorted(p.name for p in (ROOT / "interview.app/design").glob("the-*-problem.html"))

    return {
        "questions": len(qs),
        "by_language": dict(sorted(langs.items())),
        "companies": len(companies),
        "skill_check": {"total": sum(pools.values()), "sections": pools},
        "data_model_scenarios": len(scenarios),
        "design_problems": len(problems),
        "tracks": len(catalog["interview_tracks"]),
    }


def build(catalog=None) -> dict:
    catalog = catalog or read_json(CATALOG)
    arts = article_counts(catalog)
    deck = deck_counts(catalog)
    iv = interview_counts(catalog)
    reg = {
        "$comment": "GENERATED by scripts/platform_build/build.py — do not edit. Counts are derived from content; see docs/PLATFORM-DATA.md.",
        "articles": arts,
        "homepage_deck": deck,
        "interview": iv,
        "sacred_texts": {
            "count": len(catalog["sacred_texts"]),
            "by_tradition": dict(sorted(Counter(t["tradition"] for t in catalog["sacred_texts"]).items())),
            "by_language": dict(sorted(Counter(t["language"] for t in catalog["sacred_texts"]).items())),
            "devotional_resources": len(catalog["devotional_resources"]),
        },
        "demos": {"count": len(catalog["demos"])},
        "jobs": {
            "products": len(catalog["jobs_products"]),
            "live_stats": "/jobs/data/stats.json",
        },
        "journeys": [j["id"] for j in catalog["journeys"]],
    }
    return reg


def stats(reg: dict) -> dict[str, int]:
    """Flat key → value map that `data-ps-stat` elements may reference."""
    iv = reg["interview"]
    out = {
        "articles.total": reg["articles"]["total"],
        "deck.total": reg["homepage_deck"]["total"],
        "interview.questions": iv["questions"],
        "interview.companies": iv["companies"],
        "interview.skill_check": iv["skill_check"]["total"],
        "interview.data_models": iv["data_model_scenarios"],
        "interview.design_problems": iv["design_problems"],
        "interview.tracks": iv["tracks"],
        "sacred.texts": reg["sacred_texts"]["count"],
        "demos.total": reg["demos"]["count"],
    }
    for c, n in reg["articles"]["by_category"].items():
        out[f"articles.{c}"] = n
    for c, n in reg["homepage_deck"]["by_category"].items():
        out[f"deck.{c}"] = n
    for lang, n in iv["by_language"].items():
        out[f"interview.questions.{lang}"] = n
    for sec, n in iv["skill_check"]["sections"].items():
        out[f"interview.skill_check.{sec}"] = n
    return out
